### ISSUE TITLE
根据教程run-all添加设备类型时出错

### ISSUE THREAD

**Issue by chechuanxin** [jetlinks/jetlinks-community#1]
![image](https://user-images.githubusercontent.com/37929450/76404913-458e9980-63c2-11ea-9583-73947a485b4d.png)

docker在虚拟机里运行的，这里应该是虚拟机的地址

**Comment by chechuanxin** [comment]
哦，得改下配置文件

**Comment by zhou-hao** [comment]
修改docker-compose中jetlinks的环境变量配置:`hsweb.file.upload.static-location`
