### ISSUE TITLE
地理位置通过字符串分割的形式上报，系统展示异常

### ISSUE THREAD

**Issue by Lmathewli** [jetlinks/jetlinks-community#102]
网址：http://doc.jetlinks.cn/advancement-guide/mqtt-connection.html#%E5%9C%B0%E7%90%86%E4%BD%8D%E7%BD%AE%E4%B8%8A%E6%8A%A5
![image](https://user-images.githubusercontent.com/19689037/139782121-fedb9080-5256-4939-a456-dc8e4de85973.png)
![image](https://user-images.githubusercontent.com/19689037/139782179-fc3e84b8-b871-4994-9738-c62b498bed75.png)
![image](https://user-images.githubusercontent.com/19689037/139782192-568c3144-4a6d-481a-b361-c6b6b5d6dbf4.png)
点击刷新，值消失。查看日志也没有值。
![image](https://user-images.githubusercontent.com/19689037/139782231-99b8aa48-6103-4a9c-ab33-ada40403e92e.png)
![image](https://user-images.githubusercontent.com/19689037/139782239-31665232-b115-4430-89d8-e3350aa03d09.png)

**Comment by zhou-hao** [comment]
存储模式使用的什么。 经纬度需要是一个合法的经纬度值。

**Comment by Lmathewli** [comment]
存储模式：默认-列式存储

**Comment by zhou-hao** [comment]
经纬度需要是一个合法的经纬度值。 经度 0-180，纬度 0-90
