### ISSUE TITLE
最新版的TCP认证配置在哪？

### ISSUE THREAD

**Issue by z987z** [jetlinks/jetlinks-community#108]
“AuthRequest.of(deviceId,key) 第一个参数为设备id，第二参数为设备型号中配置的TCP认证配置。”中的“TCP认证配置"在哪里？看以前版本好像在产品信号下设置，新版本找不到了。

**Comment by zhou-hao** [comment]
产品选择demo，tcp 协议没

**Comment by z987z** [comment]
选了TCP了啊

> 产品选择demo，tcp协议没

**Comment by z987z** [comment]
我现在是想模拟设备上线，文档上说要生成一串2进制的编码：
![1638414661(1)](https://user-images.githubusercontent.com/62694818/144350988-174bdf67-91f7-4e5b-abfe-662f1c56145b.png)
需要2个参数，设备ID和TCP认证配置。这两个参数都有问题，设备ID可以写英语的，参数里要求一定是INT。TCP认证配置叶不知道哪里找。
我是哪里出错了，希望大神指点。谢谢

**Comment by zhou-hao** [comment]
提供一下你产品配置界面截图。

**Comment by z987z** [comment]
![1638425948(1)](https://user-images.githubusercontent.com/62694818/144368591-f9c16f8f-82d1-4934-9a6b-dfa1e069cc22.png)
是这个吗？

**Comment by zhou-hao** [comment]
点开产品详情

**Comment by z987z** [comment]
![1638426359(1)](https://user-images.githubusercontent.com/62694818/144369360-f01e7713-eaf0-4dbe-9b1b-283a7fbe9a1e.png)
然后呢

**Comment by zhou-hao** [comment]
你这前端是啥版本，正常应该是这样的
![image](https://user-images.githubusercontent.com/7791838/144369492-00c5260b-a577-4eb8-b191-5b4e2f270cad.png)

**Comment by z987z** [comment]
我前端也是官网推荐的地方下载的啊，这里。。
![1638426565(1)](https://user-images.githubusercontent.com/62694818/144369746-2fe4d24d-2d14-42a9-a466-46c856c1d5c6.png)

**Comment by z987z** [comment]
我再下载一次试试

**Comment by z987z** [comment]
重新下载了一次还是一样。。

**Comment by z987z** [comment]
请问应该下我们版本的前台，可以的话提供下下载地址，感激不尽

**Comment by zhou-hao** [comment]
demo协议是在哪获取的 下载最新的试试 https://github.com/jetlinks/demo-protocol

**Comment by z987z** [comment]
好的，我先试试，谢谢

**Comment by z987z** [comment]
还是不行。。我去http://demo.jetlinks.cn/上看了都没有：
![1638431033(1)](https://user-images.githubusercontent.com/62694818/144379022-c61c0047-6e56-4aa0-b1ed-18c968eac179.png)
是不是取消了，如果是有最新的连接说明文档吗？

**Comment by zhou-hao** [comment]
你本地打包最新的 demo协议试试

**Comment by z987z** [comment]
搞清楚了，和上传的JAR包有关系，也就是和协议有关系，谢谢了
