### ISSUE TITLE
standalone打包时编译出错

### ISSUE THREAD

**Issue by kevinwang2k** [jetlinks/jetlinks-community#110]
JDK版本也没问题的嘛，请问是什么原因呢？
![image](https://user-images.githubusercontent.com/35440938/144705013-95a313a0-794a-4cbc-a020-a299be9509ff.png)

**Comment by zhou-hao** [comment]
执行mvn -version看看



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kevinwang2k ***@***.***&gt;
发送时间: 2021年12月4日 17:46
收件人: jetlinks/jetlinks-community ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [jetlinks/jetlinks-community] standalone打包时编译出错 (Issue #110)





 
JDK版本也没问题的嘛，请问是什么原因呢？

**Comment by kevinwang2k** [comment]
谢谢大佬的快速回复！确实版本不对。
![1638614253(1)](https://user-images.githubusercontent.com/35440938/144706469-44d62d2f-c74d-40de-acab-c9d65b86979b.png)
