### ISSUE TITLE
关于规则引擎和数据转发的一些问题

### ISSUE THREAD

**Issue by toskeyfine** [jetlinks/jetlinks-community#111]
Jetlinks用了一段时间，功能确实强大，但在二次开发协议的过程中会有一些官方文档上没有说明的问题。麻烦大佬抽时间解答一下，感谢.

场景：服务器A和B均部署jetlinks，设备直连服务器A， A收到报文后本地存储使用，同时将收到的报文通过MQTT转发给服务器B，使服务器B同样可以看到数据并存储.

疑问：
1. 服务器A到服务器B的数据转发，能否使用网络组件MQTT客户端配合规则引擎来实现？
2. 网络组件MQTT客户端如何自定义协议规则？例如：用户名和密码加密. （目前只能使用创建网络组件时配置好的用户名密码）.

注： 1. 疑问2中自定义协议规则是希望两台服务器之间的通讯使用自定义的私有协议. 2. 不想让服务器B使用MQTT订阅的来订阅A的消息总线。

**Comment by zhou-hao** [comment]
> 1. 服务器A到服务器B的数据转发，能否使用网络组件MQTT客户端配合规则引擎来实现？
不太明白这个需求。是Jetlinks集群时的实时数据传递？

> 2. 网络组件MQTT客户端如何自定义协议规则？例如：用户名和密码加密. （目前只能使用创建网络组件时配置好的用户名密码）.

`MqttClientProvider`中指出使用spel表达式来构造clientId ,用户名,密码。或者修改这部分代码来实现。

**Comment by happygod-lyc** [comment]
自动回复：来信收到

**Comment by toskeyfine** [comment]
> > 1. 服务器A到服务器B的数据转发，能否使用网络组件MQTT客户端配合规则引擎来实现？
> 
> 不太明白这个需求。是Jetlinks集群时的实时数据传递？
> 
> > 2. 网络组件MQTT客户端如何自定义协议规则？例如：用户名和密码加密. （目前只能使用创建网络组件时配置好的用户名密码）.
> 
> `MqttClientProvider`中指出使用spel表达式来构造clientId ,用户名,密码。或者修改这部分代码来实现。

首先感谢大佬及时给出的解答。 
第一个问题其实是服务器A/B不在同一网络下，例如服务器A和服务器B使用APN/VPN通信，B希望拿到设备数据 并可以下发指令，此时就需要与服务器A进行MQTT的对接。

**Comment by zhou-hao** [comment]
方式1: 使用独立的消息中间件
方式2: B当成一个网关设备连接到A(企业版的边缘网关就是类似的实现)
具体还是得看需求，服务器A,B的设备在对方系统上怎么体现。

**Comment by toskeyfine** [comment]
好的，了解了。
能再问个问题吗？设备影子如何使用？功能调用后若设备离线，怎么把下发的报文暂存到设备影子中

**Comment by zhou-hao** [comment]
平台开放度很高，设备影子本质上就是设备的缓存信息：可以直接在协议包中使用`device.getSelfConfig`以及`device.setConfig`自己管理缓存信息。

**Comment by dongbaibai** [comment]
大佬 看了一下规则引擎的实现，是先扔到es然后去读吗

**Comment by zhou-hao** [comment]
不是的哟。规则引擎也是基于事件驱动的，你指的是 数据转发里的SQL语句吧，这个是基于 [ReactorQL](https://github.com/jetlinks/reactor-ql) 来进行实时数据处理的。
