### ISSUE TITLE
通过第三方MQTT服务接入设备测试不通过

### ISSUE THREAD

**Issue by LenardWilliam** [jetlinks/jetlinks-community#117]
模拟设备上下线一直没有反应，都是按照教程做的，也读取到MQTT了，
![image](https://user-images.githubusercontent.com/95908160/145781651-3a191b91-7570-46a4-bd5a-89a06efca15c.png)
就是设备始终离线状态啊
![image](https://user-images.githubusercontent.com/95908160/145782106-76d5d142-a206-4e05-924f-919d5c959ca1.png)
有没有大佬帮忙看看啊
http://doc.jetlinks.cn/advancement-guide/third-mqtt.html#%E6%A8%A1%E6%8B%9F%E8%AE%BE%E5%A4%87%E4%B8%8A%E4%B8%8B%E7%BA%BF

**Comment by zhou-hao** [comment]
提供一下：
1. 设备网关里选择的协议包
2. 设备网关里配置的topic

**Comment by LenardWilliam** [comment]
1. 设备网关里选择的协议包：
![image](https://user-images.githubusercontent.com/95908160/145917075-23ecea70-15bd-499c-9965-fc0873457407.png)
这个就是官网上下载的我一个字没动直接用的
2.设备网关里配置的话题
![image](https://user-images.githubusercontent.com/95908160/145917305-150f5e4c-a97b-44af-b207-f5a59982ca8d.png)

**Comment by LenardWilliam** [comment]
> 提供一下：
> 
> 1. 设备网关里选择的协议包
> 2. 设备网关里配置的话题

![image](https://user-images.githubusercontent.com/95908160/145917711-135e70b9-d2f2-4f3a-bceb-66842175cd43.png)
其实我之前上传的时候，就是批量导入设备，显示成功了，但实际上服务直接就崩溃了
![image](https://user-images.githubusercontent.com/95908160/145917906-b397a333-8b36-495b-ab98-5f262bdd4fdd.png)
我是直接手写了一个设备，因为我查看了一下上传的配置好像也没什么问题
![image](https://user-images.githubusercontent.com/95908160/145918067-eff0b82b-a179-4f7d-a65e-084a82ceb454.png)
会是这个问题吗？

**Comment by zhou-hao** [comment]
看文档 官方协议说明



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: LenardWilliam ***@***.***&gt;
发送时间: 2021年12月14日 09:44
收件人: jetlinks/jetlinks-community ***@***.***&gt;
抄送: 老周 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [jetlinks/jetlinks-community] 通过第三方MQTT服务接入设备测试不通过 (Issue #117)





  
设备网关里选择的协议包：
 
 这个就是官网上下载的我一个字没动直接用的
 2.设备网关里配置的话题

**Comment by LenardWilliam** [comment]
![image](https://user-images.githubusercontent.com/95908160/145920748-ad160b6b-e487-4a87-b83d-5bf5c5b16aef.png)
这个？我看了啊，是下下来还要改什么地方吗？这上面也没说啊。大佬能说的详细一点吗？配置小白

**Comment by zhou-hao** [comment]
设备网关配置订阅 协议相关的topic. 客户端推送相应的topic，会自动上线。   不同的协议的topic不同。
