### ISSUE TITLE
Swagger登录授权后，访问接口提示401未登录

### ISSUE THREAD

**Issue by jeeknet** [jetlinks/jetlinks-community#121]
运行项目，打开Swagger后通过/authorize/login接口登录后获取token，之后点击Authorized按钮，并将token加入到value文本框后进行认证，之后点击需要验证的接口还是提示401 用户未登录，请教哪点操作错误吗

**Comment by jeeknet** [comment]
经测试，通过Postman获取token后，通过加Header X-Access-Token 可以实现带权限接口访问，Swagger的Authorized功能没有加X-Access-Token到Header中

**Comment by zhou-hao** [comment]
![image](https://user-images.githubusercontent.com/7791838/146356480-1bbb12bf-53f1-446c-a555-6d56bae39168.png)
在这里设置也可以
