### ISSUE TITLE
源码解读@interface Subscribe具体实现

### ISSUE THREAD

**Issue by codeMark1** [jetlinks/jetlinks-community#131]
![image](https://user-images.githubusercontent.com/19514412/147812371-6357830a-1350-4b04-b4af-79de26b42ea3.png)

请问下这个@Subscribe这个注解的实现是在哪里的呢？源码中也没有找到切面这样的类，是如何实现这个自定义注解的呢

**Comment by zhou-hao** [comment]
***@***.***



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: codeMark1 ***@***.***&gt;
发送时间: 2021年12月31日 16:32
收件人: jetlinks/jetlinks-community ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [jetlinks/jetlinks-community] ***@***.*** Subscribe具体实现 (Issue #131)





 

 
***@***.***这个注解的实现是在哪里的呢？源码中也没有找到切面这样的类，是如何实现这个自定义注解的呢

**Comment by zhou-hao** [comment]
`SpringMessageBroker`
![image](https://user-images.githubusercontent.com/7791838/147998318-568b816c-a89b-4ed9-9284-759cd8d48058.png)
