### ISSUE TITLE
事物无法回滚

### ISSUE THREAD

**Issue by tom055** [jetlinks/jetlinks-community#135]
老周 问下 插入无法回滚要怎么处理呢
![微信图片_20220107141109](https://user-images.githubusercontent.com/17687356/148500328-aa5a45bf-289b-4e58-aeb7-20d772a4dcb1.png)

**Comment by zhou-hao** [comment]
抛出异常了么。

**Comment by tom055** [comment]
有的
![微信图片22](https://user-images.githubusercontent.com/17687356/148500814-80838dc4-5f72-4585-9206-930e747d6b22.png)

**Comment by zhou-hao** [comment]
异常是RuntimeException才行。可以通过 `@Transactional(rollbackFor = )`来设置

**Comment by tom055** [comment]
可以了 非常感谢~~
