### ISSUE TITLE
运行一段时间，后端服务就会崩了，ReadTimeoutException

### ISSUE THREAD

**Issue by kevinwang2k** [jetlinks/jetlinks-community#141]
![image](https://user-images.githubusercontent.com/35440938/150973948-f182f821-7b2e-4228-b9ca-9fe59246d77b.png)

**Comment by zhou-hao** [comment]
检查一下es的状态。看上去是es操作超时



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kevinwang2k ***@***.***&gt;
发送时间: 2022年1月25日 20:06
收件人: jetlinks/jetlinks-community ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [jetlinks/jetlinks-community] 运行一段时间，后端服务就会崩了，ReadTimeoutException (Issue #141)
