### ISSUE TITLE
设备可视化界面无法删除与编辑

### ISSUE THREAD

**Issue by qiaoyurensheng** [jetlinks/jetlinks-community#145]
在设备管理>设备>可视化界面，能新建可视化表格，但是新建完成之后就无法编辑和删除了，编辑与删除按钮点击无效，
![1W5]V[0YW6UW$9R8S5]FU%T.png](https://ae03.alicdn.com/kf/H2d1350bcccbb4caabb14a4b042b4b9f49.png)

**Comment by zhou-hao** [comment]
此功能已停止维护。
