### ISSUE TITLE
通过第三方MQTT服务接入设备，离线状态

### ISSUE THREAD

**Issue by mervyned** [jetlinks/jetlinks-community#147]
通过第三方MQTT服务接入设备时，设备网关设备网路断开，平台无法检测到网关设备离线了，始终在线，是我配置问题吗？
MQTT Broker：EMQ 4.4.1
协议：官方协议jetlinks-official-protocol-2.0-SNAPSHOT.jar

另外，我在【设备网关】中，不知该如何指定【Topics】，我使用/*无法获取消息，必须使用具体的，如/product1/device1/properties/report。

**Comment by zhou-hao** [comment]
1. 你使用emq，设备状态是emq管理的，可以订阅emq的系统topic来获取设备连接断开
2. mqtt的topic通配符是+和#&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mervyn ***@***.***&gt;
发送时间: 2022年3月13日 00:34
收件人: jetlinks/jetlinks-community ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [jetlinks/jetlinks-community] 通过第三方MQTT服务接入设备，离线状态 (Issue #147)





 
通过第三方MQTT服务接入设备时，设备网路断开，平台无法检测到设备离线了，是我配置问题吗？
 MQTT Broker：EMQ 4.4.1
 协议：官方协议jetlinks-official-protocol-2.0-SNAPSHOT.jar
 
另外，我在【设备网关】中，不知该如何指定【Topics】，我使用/*无法获取消息，必须使用具体的，如/product1/device1/properties/report。

**Comment by mervyned** [comment]
1.我可以订阅emq的状态管理消息，是否意味着，我需要二次开发，在合适的位置，将emq的设备状态信息，转换为平台统一消息？
2.【操作手册】【设备接入】【设备网关】【MQTT客户端设备网关】章节中，使用的是/chiefddata/*，没使用+。
另外即使我使用了/product1/+这样的通配符，平台并不能收到该topic下的消息。
![image](https://user-images.githubusercontent.com/20469436/158060654-9cc1c369-2885-4b33-b800-d5e51c011d3e.png)

**Comment by happygod-lyc** [comment]
自动回复：来信收到
