### ISSUE TITLE
资产分配无法过滤

### ISSUE THREAD

**Issue by mervyned** [jetlinks/jetlinks-community#148]
在分配资产时，进入设备tab页，会查询出所有设备，未根据orgid进行过滤，原因看起来是后台没有把orgid作为where条件进行查询。
<img width="1649" alt="image" src="https://user-images.githubusercontent.com/20469436/158427822-ade1e0af-3c67-4a9a-a415-064723f5990f.png">

后台sql文如下：
SELECT
	dev_device_instance."product_id" AS "productId",
	dev_device_instance."configuration" AS "configuration",
	dev_device_instance."creator_id" AS "creatorId",
	dev_device_instance."creator_name" AS "creatorName",
	dev_device_instance."derive_metadata" AS "deriveMetadata",
	dev_device_instance."registry_time" AS "registryTime",
	dev_device_instance."org_id" AS "orgId",
	dev_device_instance."parent_id" AS "parentId",
	dev_device_instance."product_name" AS "productName",
	dev_device_instance."features" AS "features",
	dev_device_instance."create_time" AS "createTime",
	dev_device_instance."name" AS "name",
	dev_device_instance."describe" AS "describe",
	dev_device_instance."id" AS "id",
	dev_device_instance."state" AS "state" 
FROM
	PUBLIC.dev_device_instance dev_device_instance 
ORDER BY
	dev_device_instance."id" DESC 
	LIMIT 10 OFFSET 0

**Comment by zhou-hao** [comment]
社区版暂不支持此功能
