### ISSUE TITLE
协议管理-发布协议-提示无法加载协议

### ISSUE THREAD

**Issue by liweihappyman** [jetlinks/jetlinks-community#15]
![无法加载协议](https://user-images.githubusercontent.com/19857835/91010819-ca3e3e80-e615-11ea-8042-7a8cab2eefe6.png)

**Comment by zhou-hao** [comment]
http://doc.jetlinks.cn/common-problems/install.html#%E4%BD%BF%E7%94%A8docker%E5%90%AF%E5%8A%A8ui%E5%90%8E%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE%E7%B3%BB%E7%BB%9F%E6%88%96%E8%80%85%E6%8F%90%E7%A4%BA%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%86%85%E9%83%A8%E9%94%99%E8%AF%AF

**Comment by liweihappyman** [comment]
之前也按照文档的方式来设置环境变量了，但是不知道哪里出了问题？想请教一下作者和各位高手

![image](https://user-images.githubusercontent.com/19857835/91131042-3769d680-e6df-11ea-84bc-85457b3cdd53.png)

![image](https://user-images.githubusercontent.com/19857835/91133029-ef977f00-e6df-11ea-8fce-1aa220277bf3.png)


![image](https://user-images.githubusercontent.com/19857835/91131125-5c5e4980-e6df-11ea-9dd1-066e463c856b.png)

**Comment by 790712946** [comment]
171后面是不是多了个“/”？还有就是这个问题请确保运行jetlinks的服务器能访问static-location的地址




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jetlinks/jetlinks-community"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月25日(星期二) 下午2:36
收件人:&nbsp;"jetlinks/jetlinks-community"<jetlinks-community@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [jetlinks/jetlinks-community] 协议管理-发布协议-提示无法加载协议 (#15)





 
之前也按照文档的方式来设置环境变量了，但是不知道哪里出了问题？想请教一下作者和各位高手

**Comment by liweihappyman** [comment]
> static-location

嗯嗯，已经修改，docker部署版的地址没有错误，想请教一下这个static-location是哪一个模块的？

**Comment by liweihappyman** [comment]
嗯嗯，已经修改，docker部署版的地址没有错误，想请教一下这个static-location是哪一个模块的？


> 171后面是不是多了个“/”？还有就是这个问题请确保运行jetlinks的服务器能访问static-location的地址
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jetlinks/jetlinks-community" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月25日(星期二) 下午2:36 收件人:&nbsp;"jetlinks/jetlinks-community"<jetlinks-community@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [jetlinks/jetlinks-community] 协议管理-发布协议-提示无法加载协议 (#15) 之前也按照文档的方式来设置环境变量了，但是不知道哪里出了问题？想请教一下作者和各位高手 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by 790712946** [comment]
这个是hsweb里的，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wayne Lee"<notifications@github.com&gt;; 
发送时间: 2020年8月25日(星期二) 下午2:55
收件人: "jetlinks/jetlinks-community"<jetlinks-community@noreply.github.com&gt;; 
抄送: "本 心"<790712946@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [jetlinks/jetlinks-community] 协议管理-发布协议-提示无法加载协议 (#15)





  
static-location
  
嗯嗯，已经修改，docker部署版的地址没有错误，想请教一下这个static-location是哪一个模块的？
