### ISSUE TITLE
能否在规则引擎中加入聚合条件的判断逻辑

### ISSUE THREAD

**Issue by qq517634644** [jetlinks/jetlinks-community#151]
## 问题背景
在流程制造行业中，对于原材料进料的监测可能会由于原材料搅拌不均匀造成某一时刻或者某一时间段的指标偏离阈值，但是在长时间的维度上是可以接受这种偏差的，只需要在时间段之内的平均指标合格就行

## 项目功能
目前JetLinks对于这种业务的支持略显乏力，如果通过协议中撰写逻辑，则略显臃肿

## 综上
即JetLinks的规则引擎只对采集指标能做出逻辑响应，无法针对诸如 五分钟内的平均温度（或者其他指标）的 判断提供支撑

**Comment by zhou-hao** [comment]
可以利用`ReactorQL`来处理, http://doc.jetlinks.cn/dev-guide/reactor-ql.html
