### ISSUE TITLE
MySQL 对应的sql文件在哪里呀

### ISSUE THREAD

**Issue by 1226676454** [jetlinks/jetlinks-community#154]
MySQL 对应的sql文件在哪里呀

**Comment by zhou-hao** [comment]
手动建库，自动建表



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 1226676454 ***@***.***&gt;
发送时间: 2022年4月14日 17:37
收件人: jetlinks/jetlinks-community ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [jetlinks/jetlinks-community] MySQL 对应的sql文件在哪里呀 (Issue #154)





 
MySQL 对应的sql文件在哪里呀

**Comment by 1226676454** [comment]
想问下还有更详细的文档吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月14日(星期四) 下午5:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jetlinks/jetlinks-community] MySQL 对应的sql文件在哪里呀 (Issue #154)





 手动建库，自动建表 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: 1226676454 ***@***.***&amp;gt; 
 发送时间: 2022年4月14日 17:37 
 收件人: jetlinks/jetlinks-community ***@***.***&amp;gt; 
 抄送: Subscribed ***@***.***&amp;gt; 
 主题: Re: [jetlinks/jetlinks-community] MySQL 对应的sql文件在哪里呀 (Issue #154) 
 
 
 
 
 
   
 MySQL 对应的sql文件在哪里呀

**Comment by zhou-hao** [comment]
http://doc.jetlinks.cn/
