### ISSUE TITLE
Tcp透传方式接入设备---设备状态还是离线状态

### ISSUE THREAD

**Issue by 1226676454** [jetlinks/jetlinks-community#157]

**Comment by 1226676454** [comment]
![image](https://user-images.githubusercontent.com/46528198/163539444-37bf76f3-2b31-4ea0-83dc-1a572128f18a.png)
![image](https://user-images.githubusercontent.com/46528198/163539485-19860ef6-a925-47ef-92c8-2b1afe0ca9d6.png)
![image](https://user-images.githubusercontent.com/46528198/163539538-b7bb6c0d-48fc-4eb7-bdac-d42d2f3d6faf.png)
想知道为什么这个设备会上线不了 按照文档的流程来走的

**Comment by zhou-hao** [comment]
要保持长连接不要断

**Comment by 1226676454** [comment]
![image](https://user-images.githubusercontent.com/46528198/163540011-546de472-954d-4a0f-9889-f9be7e29acd5.png)
这个工具选的是长连接的
