### ISSUE TITLE
jetlinks 社区版调用 API 问题 

### ISSUE THREAD

**Issue by qiaoyurensheng** [jetlinks/jetlinks-community#158]
jetlinks 社区版在使用 API 调用测试时提示没有登陆怎么办 ? 用 API 请求应该怎样鉴权呢？
我在 jetlinks 文档和 api 文档中都未找到相关描述

![image](https://user-images.githubusercontent.com/28298760/164171826-bfb917f2-0bae-4c59-a7b1-71ff52f6028e.png)

**Comment by zhou-hao** [comment]
调用`/authorize/login`接口登录 获取token。或者参照登录接口实现生成token。或者f12 复制浏览器中的 请求头 `X-Access-Token` 到文档全局设置中。

**Comment by qiaoyurensheng** [comment]
> 调用`/authorize/login`接口登录头获取令牌。或者参照登录接口生成令牌。或者实现12复制请求`X-Access-Token`到浏览器获取文档中的令牌设置中。

调用 `/authorize/login` 接口，传入账号密码，也是提示有错误，没有什么返回，

![image](https://user-images.githubusercontent.com/28298760/164232978-7c72cd2e-5a1b-47ee-844c-5d5e9c5a2979.png)
![image](https://user-images.githubusercontent.com/28298760/164233222-c7271d93-4373-4784-a07b-1b15a793e95b.png)

**Comment by qiaoyurensheng** [comment]
> 指定ContentType 发自己的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 巧遇人生 ***@***.***&gt; 发送时间: 2022年4月20日 20:47 收件人: jetlinks/jetlinks-community ***@***.***&gt; 抄送: 老周 ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [jetlinks/jetlinks-community] jetlinks 社区版调用 API 问题 (Issue #158) 调用/authorize/login接口登录头获取令牌。或者参照登录接口生成令牌。或者实现12复制请求X-Access-Token到浏览器获取文档中的令牌设置中。 调用 /authorize/login 接口，传入账号密码，也是提示有错误，没有什么返回， — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;


指定 `ContentType`为 `application/x-www-form-urlencoded`，一样报错，详见截图：
![image](https://user-images.githubusercontent.com/28298760/164245202-c1369be4-635f-4413-85e9-a1dd68d1eed0.png)

**Comment by lengjiaxin** [comment]
![image](https://user-images.githubusercontent.com/11784736/169495968-65c38a02-cd33-4aa0-84a7-334076a48af2.png)
swagger-ui:全局设置Token无效，提示未登录。请求头也未携带【X-Access-Token】；

**Comment by zhou-hao** [comment]
访问 `doc.html` ,  
<img width="973" alt="image" src="https://user-images.githubusercontent.com/7791838/169499481-68ac22ff-caf9-4db5-af7c-fa7163efd9a1.png">
