### ISSUE TITLE
建议通过0xAA这样的字符串来提供十六进制的协议分隔符支持

### ISSUE THREAD

**Issue by qinqoushui** [jetlinks/jetlinks-community#159]
固定分隔符只能使用字符串来描述，但很多协议的头未必是可见字符 ，无法描述，需要类似0x7f这样的表达式。
```
protected RecordParser createParser(ValueObject config) {
        String delimited = StringEscapeUtils.unescapeJava(config.getString("delimited")
            .orElseThrow(() -> new IllegalArgumentException("delimited can not be null")));
        log.info("固定分隔符解析器" + delimited);
        //增加以HEX开头的分隔器
        if (delimited.startsWith("0x")) {
            try {
                Buffer buffer = Buffer.buffer(Hex.decodeHex(delimited.substring(2).replace(" ", "")));
                return RecordParser.newDelimited(buffer);
            } catch (DecoderException e) {
                log.error("无效的分隔符" + delimited);
                return null;
            }
        } else
            return RecordParser.newDelimited(delimited);
    }
```

**Comment by zhou-hao** [comment]
使用unicode码也可以的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: QinQouShui ***@***.***&gt;
发送时间: 2022年4月30日 11:36
收件人: jetlinks/jetlinks-community ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [jetlinks/jetlinks-community] 建议通过0xAA这样的字符串来提供十六进制的协议分隔符支持 (Issue #159)





 
固定分隔符只能使用字符串来描述，但很多协议的头未必是可见字符 ，无法描述，需要类似0x7f这样的表达式。
 protected RecordParser createParser(ValueObject config) {         String delimited = StringEscapeUtils.unescapeJava(config.getString("delimited")             .orElseThrow(() -&gt; new IllegalArgumentException("delimited can not be null")));         log.info("固定分隔符解析器" + delimited);         //增加以HEX开头的分隔器         if (delimited.startsWith("0x")) {             try {                 Buffer buffer = Buffer.buffer(Hex.decodeHex(delimited.substring(2).replace(" ", "")));                 return RecordParser.newDelimited(buffer);             } catch (DecoderException e) {                 log.error("无效的分隔符" + delimited);                 return null;             }         } else             return RecordParser.newDelimited(delimited);     }

**Comment by zhou-hao** [comment]
比如:  `\u0055\u00aa`
