### ISSUE TITLE
如何修改docker-compose.yml文件中的端口？

### ISSUE THREAD

**Issue by mulanshandi** [jetlinks/jetlinks-community#16]
背景：我的环境中，分配给我一段独立的端口范围（如20000~20100）。其余端口范围不允许占用

我看docker-compose.yml中暴露的端口有许多：
  kibana:
    ports:
      - "5602:5601"
  postgres:
    ports:
      - "5432:5432"
  ui:
    ports:
      - 9000:80
  jetlinks:
    ports:
      - 8848:8848 # API端口
      - 1883-1890:1883-1890 # 预留
      - 8000-8010:8000-8010 # 预留
    environment:
      - "hsweb.file.upload.static-location=http://127.0.0.1:8848/upload"  #上传的静态文件访问根地址,为ui的地址.
      - "spring.r2dbc.url=r2dbc:postgresql://postgres:5432/jetlinks" #数据库连接地址
      - "elasticsearch.client.post=9200"
      - "spring.redis.port=6379"

准备把ports中绑定到的主机端口全部修改掉。那上面environment中的4个端口是否需要修改？

谢谢！

**Comment by WangScaler** [comment]
Please learn docker first

**Comment by zhou-hao** [comment]
可以修改。不过相应使用到此端口的配置也要修改
