### ISSUE TITLE
树莓派演示设备操作手册物模型缺失

### ISSUE THREAD

**Issue by amorZhu** [jetlinks/jetlinks-community#160]
[树莓派演示设备操作手册](http://doc.jetlinks.cn/basics-guide/DemoDevice.html#%E5%88%9B%E5%BB%BA%E4%BA%A7%E5%93%81)
这个文档涉及到的物模型能否提供一下，仅用作学习。

**Comment by zhou-hao** [comment]
这个暂时无法提供。可以百度一下`nodejs mqtt` 或者 `python mqtt`， 使用平台的官方协议或者demo协议来接入。
