### ISSUE TITLE
数据库连接池无法获取连接

### ISSUE THREAD

**Issue by chanlk** [jetlinks/jetlinks-community#161]
版本：1.9 RELEASE
最近程序跑得好好的会突然出现所有接口都无响应的情况，排查之后发现只要用到了Mysql的接口才有问题；

用Arthas工具查了查连接池，一个idle连接都没有了；
![image](https://user-images.githubusercontent.com/31768716/168747963-0ea19cef-3dbf-4d7f-947b-17270bc8966f.png)

ReactorNettyClient 类
![image](https://user-images.githubusercontent.com/31768716/168751907-f0b33391-9dd6-4dc7-a72b-b465017bb56f.png)

另外日志上有这个日志：
[dev.miku.r2dbc.mysql.client.MessageDuplexCodec.channelInactive][136] [Connection has been closed by peer]

### 我做过的尝试
1. 在Mysql用Show processlist列出所有jetlinks的连接，然后直接将连接Kill了（Kill Processid）
2. 此时执行查询接口，应用会出错并打印错误日志，同时也有打印 [Connection has been closed by peer]
3. 但是过一会儿连接就重新建立了（show processlist可以看到），程序也恢复正常

### 我的猜测
在mysql驱动和pool的github issues上都有类似的pool挂了的问题，似乎还没有被最终解决，驱动作者应该在忙着其他事情；
issues 链接如下：
   https://github.com/mirromutth/r2dbc-mysql/issues/82

不知老周有没有遇到此问题，感谢解惑~
PS: 老周代码功力真强！

**Comment by zhou-hao** [comment]
https://github.com/jetlinks/jetlinks-community/tree/master/jetlinks-components/configure-component/src/main/java/org/jetlinks/community/configure/r2dbc 
看这里。把这个配置复制到你的代码。

**Comment by zhou-hao** [comment]
通过设置连接有效期，让连接在超过有效期后自动断开。

**Comment by zhou-hao** [comment]
`max-life-time`,  这个配置在`spring-boot 2.3.x` 是不生效的。

**Comment by chanlk** [comment]
感谢！
这个链接可以说明确实是2.4.x 才支持
https://github.com/spring-projects/spring-boot/pull/21219

另外我看了下连接确实lifeTime很大
![image](https://user-images.githubusercontent.com/31768716/168768709-c6fee70d-0f9d-479f-b848-f55091a432d0.png)

我增加配置后重新部署一下，如果14天内问题不再发生，我就将此issue关闭！

**Comment by chanlk** [comment]
增加配置后，问题仍然出现，liftTime已经生效，为配置文件的默认值 10分钟。
更新了reactor-core版本，再上线观察

**Comment by zhou-hao** [comment]
现在情况如何

**Comment by FreedomOFO** [comment]
> https://github.com/jetlinks/jetlinks-community/tree/master/jetlinks-components/configure-component/src/main/java/org/jetlinks/community/configure/r2dbc 看这里。把这个配置复制到你的代码。

遇到了相似的问题，这个配置的链接已经失效，能麻烦再把配置给出来吗

**Comment by zhou-hao** [comment]
最新master分支直接配置 `spring.r2dbc.pool.max-life-time`即可

**Comment by yuchunyi** [comment]
> 增加配置后，问题仍然出现，liftTime已经生效，为配置文件的默认值 10分钟。 更新了reactor-core版本，再上线观察

你好，你遇到的问题解决了没
