### ISSUE TITLE
join关联查询使用AbstractTermFragmentBuilder

### ISSUE THREAD

**Issue by tom055** [jetlinks/jetlinks-community#163]
生成的sql 如何去掉或者变化where的位置呢？非常Thanks♪(･ω･)ﾉ
createQuery().where("id$product-term$location",uid).fetch();
![微信截图_111](https://user-images.githubusercontent.com/17687356/169240830-40ae3909-9e9f-421f-a57d-6b0c482effab.png)

**Comment by zhou-hao** [comment]
不要使用join。应该使用   `exists(   )`

**Comment by tom055** [comment]
已解决，Thanks♪(･ω･)ﾉ
