### ISSUE TITLE
createQuery().where().in("org_id",dimens).setParam(param).fetch() 分页条件查询时生成的sql不包含in参数

### ISSUE THREAD

**Issue by tom055** [jetlinks/jetlinks-community#164]
createQuery().where().in("org_id",dimens).setParam(param).fetch()
分页查询中 in中的条件在生成的sql中不包含，要怎么处理呢？
非常感谢
![7](https://user-images.githubusercontent.com/17687356/170633859-f83de6f1-fe39-4604-965f-d041b95d52f6.png)

**Comment by zhou-hao** [comment]
`setParam(param)`放到前面: `setParam(param).in(DeviceInstanceEntity::getOrgId,dimens).fetc()`

**Comment by tom055** [comment]
Thanks♪(･ω･)ﾉ  ღ( ´･ᴗ･` )比心
