### ISSUE TITLE
Docker run-all 目录下，使用docker-compose up启动异常

### ISSUE THREAD

**Issue by jinyangzh** [jetlinks/jetlinks-community#166]
首页统计分析，CPU使用率 和JVM内存使用情况加载不出来
![image](https://user-images.githubusercontent.com/26991722/171586804-be1e258e-4035-4e49-b81a-3498f5f4eaba.png)

**Comment by zhou-hao** [comment]
检查websocket连接

**Comment by jinyangzh** [comment]
我是用docker run-all 下面的 docker-compose.yml一键运行的，这个如何查看websocket连接，具体在哪个文件配置？
如图，docker-compose中几个注释的端口是否需要放开？
![image](https://user-images.githubusercontent.com/26991722/172079470-300c21aa-9011-4503-8134-4acaed051077.png)
![image](https://user-images.githubusercontent.com/26991722/172079570-220acc23-8b64-4515-802c-92679e12cfca.png)

**Comment by zhou-hao** [comment]
如果需要通过公网访问则需要开放端口。用户密码 默认没有设置，需要自己配置es后才有用
