### ISSUE TITLE
本地运行后，只有登录页和仪表盘可以显示，点击其他按钮白页

### ISSUE THREAD

**Issue by luck-zhz** [jetlinks/jetlinks-community#167]
![image](https://user-images.githubusercontent.com/57172653/172132075-c60ad284-ae62-49bd-b0a8-220fdfd01dae.png)

![image](https://user-images.githubusercontent.com/57172653/172132018-0a1a1464-0763-4fec-89b1-834e4c06a8c9.png)

**Comment by luck-zhz** [comment]
刷新页面才会显示

**Comment by zhou-hao** [comment]
emmm，每次登陆后都这样？

**Comment by luck-zhz** [comment]
发布后反倒没问题了，本地启动有这个问题
