### ISSUE TITLE
接入200个设备之后 出现 io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files 的问题

### ISSUE THREAD

**Issue by go136** [jetlinks/jetlinks-community#169]
在接入200多个设备并运行一段时候以后〔设备内容是通过自定义协议来解析〕，系统就无法接受设备发送的数据了。同时打开jetlinks的页面也很慢
后台出现如下报错
![image](https://user-images.githubusercontent.com/30484303/172582342-df002739-6f00-4c3d-94d4-163b4cf8fac9.png)

**Comment by go136** [comment]
这个报错 就持续的出现。

**Comment by zhou-hao** [comment]
检查 `ulimit -n` 配置。 设置大一些

**Comment by KyleWong123** [comment]
请问如何解决的

**Comment by zhou-hao** [comment]
@KyleWong123 搜索引擎: linux  ulimit配置
