### ISSUE TITLE
请问社区版本，是否缺少“规则模型”和“规则实例”两个功能？

### ISSUE THREAD

**Issue by mulanshandi** [jetlinks/jetlinks-community#17]
按照http://doc.jetlinks.cn/install-deployment/docker-start.html，下载了docker版本，并启动。但在系统的菜单中，看不到“规则模型”和“规则实例”两个功能。

**Comment by zhou-hao** [comment]
规则模型功能已经被淘汰，规则实例 属于专业版中的功能。

**Comment by mulanshandi** [comment]
我是在demo中看到的规则模型和规则实例。http://demo.jetlinks.cn/jetlinks/rule-editor/index.html#flow/test-rule

也就是说：社区版中，并没有“规则实例”这个功能，对吧？

**Comment by mulanshandi** [comment]
明白了。在https://github.com/jetlinks/jetlinks-community看到了相关说明。谢谢！
