### ISSUE TITLE
上传操作失败

### ISSUE THREAD

**Issue by CCN-COM** [jetlinks/jetlinks-community#172]
docker远程部署，按文档把static-location改为ui的ip后仍然上传不了
![image](https://user-images.githubusercontent.com/88022484/173608573-5ff38efd-511b-4c80-aad2-2a7c1822e8eb.png)
![image](https://user-images.githubusercontent.com/88022484/173610355-836427e5-9550-4cab-ba85-bac899584eaa.png)
其他的一些涉及post的操作都会失败

**Comment by zhou-hao** [comment]
更新最新代码试试？

**Comment by CCN-COM** [comment]
换成latest后可以上传了，谢谢

**Comment by zhou-hao** [comment]
`docker-compose pull jetlinks` 更新镜像
