### ISSUE TITLE
PEM证书Base64库不一致问题，导致证书解析时异常

### ISSUE THREAD

**Issue by mervyned** [jetlinks/jetlinks-community#173]
起初发现lllegal base64 character 2d错误，调查发现代码中用了java.utils.Base64，但是上传的controller用的是org.apache.commons.codec.binary.Base64，统一改为了后者，并且强制升级到1.15(1.14有bug)。
就是多个模块中，Base64库不一致，且java.utils.Base64在jdk1.8版本，不能正确处理证书文件中的换行。我统一为apache的Base64后问题解决。

**Comment by zhou-hao** [comment]
您使用的是哪个版本？我看master分支上是使用的 `org.apache.commons.codec.binary.Base64`
