### ISSUE TITLE
why do u use R2DBC 

### ISSUE THREAD

**Issue by fizz12344321** [jetlinks/jetlinks-community#176]
Hi, i am reading your project and i am interested in this, but i have a question, why do you use R2DBC instead of other non blocking IO like Hibernate Reactive or others... can you tell me your purpose, the pros and cons of R2DBC, thank you so much

**Comment by zhou-hao** [comment]
Because R2DBC is the only relational database driver that supports reactive in 3 years ago, and more important : R2DBC base on `netty` and `project reactor` , I think that is better for me.
