### ISSUE TITLE
vue通过mqtt直连平台问题

### ISSUE THREAD

**Issue by keain123** [jetlinks/jetlinks-community#178]
vue端使用浏览器建立mqtt连接直连平台，会自动转为websocket的url地址，如mqtt://127.0.0.1:1883 会自动变为ws://127.0.0.1:1883/mqtt的url，此时服务器会提示：invalid QoS: 3 []。用mqttx可以复现此情况。
请问平台是否有其他调用方式解决这个问题？

**Comment by zhou-hao** [comment]
平台不支持websocket方式连接mqtt

**Comment by keain123** [comment]
> 平台不支持websocket方式连接mqtt

那请问是否支持设备直接使用WebSocket与平台建立连接呢？

**Comment by zhou-hao** [comment]
社区版不支持。但是你可以改造一下MqttServer，应该比较容易



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: keain123 ***@***.***&gt;
发送时间: 2022年6月29日 08:59
收件人: jetlinks/jetlinks-community ***@***.***&gt;
抄送: 老周 ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [jetlinks/jetlinks-community] vue通过mqtt直连平台问题 (Issue #178)





  
平台不支持websocket方式连接mqtt
  
那请问是否支持设备直接使用WebSocket与平台建立连接呢？
