### ISSUE TITLE
数据库连接报错 caching_sha2_password

### ISSUE THREAD

**Issue by NowisNo1** [jetlinks/jetlinks-community#179]
我在两台不同的电脑上运行同一份后端代码的时候一台电脑可以正常启动，另一台报错
在出现了`Jetlinks`图标之后
首先出现了 
`WARN 4812 --- [actor-tcp-nio-1] d.m.r.mysql.client.MessageDuplexCodec    : Connection has been closed by peer`
数据库已经检查过有相关的库了
接下来就是这个错误和上面那个错误交替出现
`ERROR 4812 --- [actor-tcp-nio-1] d.m.r.mysql.client.ReactorNettyClient    : Exchange cancelled while exchange is active. This is likely a bug leading to unpredictable outcome.`
之后就是报一连串嵌套的错误，从下面这个开始
`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultNotifierManager' defined in class path resource `
这个嵌套中最后出现的一个错误是
`nested exception is io.r2dbc.spi.R2dbcPermissionDeniedException: [HY000] Authentication type 'caching_sha2_password' must require SSL in full authentication phase`
我不太清楚这是什么问题，尝试过更改过数据库的相关配置，但是这个错误依然没有被解决
两台电脑使用的均是`mysql 8.x`

**Comment by zhou-hao** [comment]
数据库连接加上参数: ssl=false试试

**Comment by NowisNo1** [comment]
`url: r2dbc:mysql://localhost:3306/jetlinks?ssl=false&serverZoneId=Asia/Shanghai`
您是指这样吗，这个已经设置过了

**Comment by zhou-hao** [comment]
mysql的默认认证方式是`caching_sha2_password `,应该需要设置ssl。
https://github.com/mirromutth/r2dbc-mysql#url-connection-factory-discovery

或者修改mysql的认证方式为`mysql_native_password `

**Comment by NowisNo1** [comment]
数据库问题解决了，原因是之前修改认证方式时没有修改成功
但是出现了新的错误
` ERROR 6940 --- [           main] o.h.web.bean.FastBeanCopier              : 创建bean copy 代理对象失败:`
之后报的全是
`module java.base does not "opens java.lang" to unnamed module @4d339552`
这是否与我电脑上存在多个jdk有关呢

**Comment by NowisNo1** [comment]
问题已经解决，谢谢
