### ISSUE TITLE
docker-compose启动时，一直报连接不上es的localhost:9200地址

### ISSUE THREAD

**Issue by mulanshandi** [jetlinks/jetlinks-community#18]
错误日志如下：
2020-09-03 15:37:06.553 ERROR 6 --- [or-http-epoll-4] o.j.c.t.m.TimeSeriesMeterRegistry        : failed to send metrics [jetlinks-metrics]
jetlinks-ce      |
jetlinks-ce      | org.springframework.data.elasticsearch.client.NoReachableHostException: Host 'localhost:9200' not reachable. Clusterstate is offline.
jetlinks-ce      |      at org.springframework.data.elasticsearch.client.reactive.SingleNodeHostProvider.lambda$null$4(SingleNodeHostProvider.java:106)
jetlinks-ce      |      at reactor.core.publisher.MonoErrorSupplied.call(MonoErrorSupplied.java:76)
jetlinks-ce      |      at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
jetlinks-ce      |      at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
jetlinks-ce      |      at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
jetlinks-ce      |      at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
jetlinks-ce      |      at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344)
jetlinks-ce      |      at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2152)
jetlinks-ce      |      at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onSubscribe(FluxOnErrorResume.java:68)
jetlinks-ce      |      at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
jetlinks-ce      |      at reactor.core.publisher.Mono.subscribe(Mono.java:4213)
jetlinks-ce      |      at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:97)
jetlinks-ce      |      at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165)
jetlinks-ce      |      at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2021)
jetlinks-ce      |      at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:390)
jetlinks-ce      |      at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:251)
jetlinks-ce      |      at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onError(FluxMap.java:252)
jetlinks-ce      |      at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:894)
jetlinks-ce      |      at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:894)
jetlinks-ce      |      at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:894)
jetlinks-ce      |      at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:87)
jetlinks-ce      |      at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:197)
jetlinks-ce      |      at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
jetlinks-ce      |      at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:213)
jetlinks-ce      |      at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:255)
jetlinks-ce      |      at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:406)
jetlinks-ce      |      at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:243)
jetlinks-ce      |      at reactor.core.publisher.DirectProcessor$DirectInner.onNext(DirectProcessor.java:333)
jetlinks-ce      |      at reactor.core.publisher.DirectProcessor.onNext(DirectProcessor.java:142)
jetlinks-ce      |      at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
jetlinks-ce      |      at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:180)
jetlinks-ce      |      at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:185)
jetlinks-ce      |      at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$TcpClientSubscriber.onError(HttpClientConnect.java:352)
jetlinks-ce      |      at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:185)
jetlinks-ce      |      at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onError(PooledConnectionProvider.java:500)
jetlinks-ce      |      at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:408)
jetlinks-ce      |      at reactor.netty.internal.shaded.reactor.pool.SimplePool.lambda$drainLoop$5(SimplePool.java:233)
jetlinks-ce      |      at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:172)
jetlinks-ce      |      at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:185)
jetlinks-ce      |      at reactor.netty.resources.PooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.operationComplete(PooledConnectionProvider.java:281)
jetlinks-ce      |      at reactor.netty.resources.PooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.operationComplete(PooledConnectionProvider.java:231)
jetlinks-ce      |      at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
jetlinks-ce      |      at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
jetlinks-ce      |      at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
jetlinks-ce      |      at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
jetlinks-ce      |      at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
jetlinks-ce      |      at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
jetlinks-ce      |      at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
jetlinks-ce      |      at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:636)
jetlinks-ce      |      at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:655)
jetlinks-ce      |      at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:529)
jetlinks-ce      |      at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:465)
jetlinks-ce      |      at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
jetlinks-ce      |      at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
jetlinks-ce      |      at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
jetlinks-ce      |      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
jetlinks-ce      |      at java.lang.Thread.run(Thread.java:748)
jetlinks-ce      |
jetlinks-ce      | 保存ElasticSearch数据失败:
jetlinks-ce      | io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:9200
jetlinks-ce      | Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
jetlinks-ce      |      at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124)
jetlinks-ce      |      at io.netty.channel.unix.Socket.finishConnect(Socket.java:243)
jetlinks-ce      |      at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:672)
jetlinks-ce      |      at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:649)
jetlinks-ce      |      at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:529)
jetlinks-ce      |      at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:465)
jetlinks-ce      |      at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
jetlinks-ce      |      at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
jetlinks-ce      |      at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
jetlinks-ce      |      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
jetlinks-ce      |      at java.lang.Thread.run(Thread.java:748)

进入jetlinks-ce的docker中，查看其配置文件/application/BOOT-INF/classes/application.yml。有如下配置：
elasticsearch:
  client:
    host: localhost
    port: 9200
    max-conn-total: 128
    connect-timeout: 5000
    socket-timeout: 5000
    connection-request-timeout: 8000

会不会问题就出在这个localhost参数上？因为该docker中明显不会启动es

在docker的命令行中，执行curl localhost:9200，得到：
curl: (7) Failed to connect to localhost port 9200: Connection refused

访问docker所在主机的IP地址：curl 192.168.1.73:9200，可以发现es服务是OK的：
{
  "name" : "koWFGVt",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "1AzvR2FhS4yqWg4T_FZJLg",
  "version" : {
    "number" : "6.8.11",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "00bf386",
    "build_date" : "2020-07-09T19:08:08.940669Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.3",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

**Comment by zhou-hao** [comment]
更新最新代码试试

**Comment by mulanshandi** [comment]
您是说采用docker拉取的镜像，可以不如拉取最新的代码更好，对吧？

那我试试看

**Comment by Edisonboy** [comment]
拉了最新的代码，用docker-compose 跑的，当前版本1.20.0-SNAPSHOT，也是报这个错误。

**Comment by zhou-hao** [comment]
@Edisonboy es 没有启动成功。

**Comment by Edisonboy** [comment]
es 启动成功的。
<img width="1667" alt="image" src="https://user-images.githubusercontent.com/19949495/182272253-898f0b02-5876-44b2-a52d-862ff1021495.png">

**Comment by zhou-hao** [comment]
看一下这个配置 
<img width="917" alt="image" src="https://user-images.githubusercontent.com/7791838/182285362-17d75534-23c0-4578-8e27-37b0251c08a6.png">
