### ISSUE TITLE
日志页超过1000页后查看报错，导致以前的数据无法显示

### ISSUE THREAD

**Issue by qiaoyukeji** [jetlinks/jetlinks-community#180]
日志页超过1000页后查看报错，导致以前的数据无法显示

![image](https://user-images.githubusercontent.com/45252025/178390222-a2d2908b-31cb-46dc-8057-3f94daf8a273.png)

`Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed], Elasticsearch exception [type=illegal_argument_exception, reason=Result window is too large, from + size must be less than or equal to: [10000] but was [10020]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.]`

![image](https://user-images.githubusercontent.com/45252025/178389763-43938c7e-aa3b-4c30-b56e-5fc1420a1445.png)

**Comment by zhou-hao** [comment]
es 分页深度限制问题。 需要查看对应的数据建议使用更细的筛选条件，而不是通过深度分页来查找数据。

**Comment by qiaoyukeji** [comment]
请问这个应该怎么操作呢，如何使用更细的筛选条件，这个我没有太理解；我并没有修改程序的任何相关代码

**Comment by qiaoyukeji** [comment]
> 需要查看建议使用更细的筛选条件，而不是通过详细页面来查找数据。

请问这个应该怎么操作呢，如何使用更细的筛选条件，这个我没有太理解；我并没有修改程序的任何相关代码
