### ISSUE TITLE
最新master分支代码，运行报Failure to find org.jetlinks.community:authentication-manager:pom:1.20.0-SNAPSHOT in https://maven.aliyun.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of aliyun-nexus has elapsed or updates are forced

### ISSUE THREAD

**Issue by 1234567890bm** [jetlinks/jetlinks-community#182]
Failure to find org.jetlinks.community:authentication-manager:pom:1.20.0-SNAPSHOT in https://maven.aliyun.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of aliyun-nexus has elapsed or updates are forced
尝试修改和删除setting.xml中 <mirrors>都无效

**Comment by zhou-hao** [comment]
删除本地仓库的相关依赖文件。去掉settings.xml里配置的私服



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 1234567890bm ***@***.***&gt;
发送时间: 2022年7月23日 10:52
收件人: jetlinks/jetlinks-community ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [jetlinks/jetlinks-community] 最新master分支代码，运行报Failure to find org.jetlinks.community:authentication-manager:pom:1.20.0-SNAPSHOT in https://maven.aliyun.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of aliyun-nexus has elapsed or updates are forced (Issue #182)





 
Failure to find org.jetlinks.community:authentication-manager:pom:1.20.0-SNAPSHOT in https://maven.aliyun.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of aliyun-nexus has elapsed or updates are forced
 尝试修改和删除setting.xml中 都无效

**Comment by 1234567890bm** [comment]
> 未能找到 org.jetlinks.community：authentication-manager：pom：1.20.0-SNAPSHOT [https://maven.aliyun.com/nexus/content/groups/public/ 被](https://maven.aliyun.com/nexus/content/groups/public/)缓存在本地存储库中，则在 aliyun-nexus 的更新间隔过去或强制更新之前，不会重新尝试解析.xml中 都无效



> 删除本地仓库的相关依赖文件。去掉settings.xml里配置的私服 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 1234567890bm ***@***.***&gt; 发送时间: 2022年7月23日 10:52 收件人: jetlinks/jetlinks-community ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [jetlinks/jetlinks-community] 最新master分支代码，运行报Failure to find org.jetlinks.community:authentication-manager:pom:1.20.0-SNAPSHOT in https://maven.aliyun.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of aliyun-nexus has elapsed or updates are forced (Issue #182) Failure to find org.jetlinks.community:authentication-manager:pom:1.20.0-SNAPSHOT in https://maven.aliyun.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of aliyun-nexus has elapsed or updates are forced 尝试修改和删除setting.xml中 都无效 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

修改Local repository目录，还原settings.xml设置都不行，maven3.6.3，jdk1.8u333，idea2020.1

**Comment by zhou-hao** [comment]
执行`mvn compile` 看看
