### ISSUE TITLE
mysql 启动报错怎么办？？？什么编码？不是utf8???

### ISSUE THREAD

**Issue by jianye112** [jetlinks/jetlinks-community#183]
![image](https://user-images.githubusercontent.com/59075587/180935012-e327b67b-db4f-4aeb-819d-2a97c84f30ae.png)

**Comment by zhou-hao** [comment]
使用 `mysql 5.7` 及以上

**Comment by jianye112** [comment]
意动广告点击王  自动换IP点击广告位，随机二次点击、深度点击
http://www.ydtuiguang.com/wztgSEO/ydggdjw/index.html 
  
意动邮件群发 自动生成收信邮箱（支持139手机邮箱）、自动查找QQ号码邮箱、百度搜索邮箱
http://www.ydtuiguang.com/wztgSEO/ydyjqf/index.html
 
 
意动刷流量 让站长们更快提高IP、PV，更好提高网站排名
刷搜索关键字、刷微博广告、博客广告、QQ空间广告、支持刷弹窗广告、支持脚本刷投票。免费刷流量
http://www.ydtuiguang.com/wztgSEO/ydsll/index.html
