### ISSUE TITLE
启动项目时报错 Unknown token [VALUE_NULL] in alias [device_metrics_alias]

### ISSUE THREAD

**Issue by marshalby2** [jetlinks/jetlinks-community#184]
es版本：8.3.2
`Elasticsearch exception [type=illegal_argument_exception, reason=Unknown token [VALUE_NULL] in alias [device_metrics_alias]]`

**Comment by zhou-hao** [comment]
es 什么版本

**Comment by marshalby2** [comment]
> 
es是最新的8.3.2版本

**Comment by zhou-hao** [comment]
请使用7.x版本

**Comment by marshalby2** [comment]
> 请使用7.x版本

谢谢，使用7.17.5版本，已解决
