### ISSUE TITLE
Parameter 2 of method fileManager in org.jetlinks.community.io.file.FileManagerConfiguration required a bean of type 'org.hswebframework.ezorm.rdb.mapping.ReactiveRepository' that could not be found.

### ISSUE THREAD

**Issue by jianye112** [jetlinks/jetlinks-community#185]
![image](https://user-images.githubusercontent.com/59075587/181405524-009e7b11-546a-4d12-8544-9ba06151582f.png)

**Comment by yuanxu-xsmy** [comment]
看源码，改了

package org.jetlinks.community.io.file;

import org.hswebframework.ezorm.rdb.mapping.ReactiveRepository;
import org.hswebframework.web.crud.annotation.EnableEasyormRepository;
import org.jetlinks.core.rpc.RpcManager;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
@EnableConfigurationProperties(FileProperties.class)
@EnableEasyormRepository("**org.jetlinks.community.io.file.FileEntity**")
public class FileManagerConfiguration {


    @Bean
    public FileManager fileManager(RpcManager rpcManager,
                                   FileProperties properties,
                                   ReactiveRepository<FileEntity, String> repository){
        return new ClusterFileManager(rpcManager,properties,repository);
    }

}
