### ISSUE TITLE
docker-compose方式一键部署能修改docker-compose.yml里面的环境变量配置吗？

### ISSUE THREAD

**Issue by GoldenSunZ** [jetlinks/jetlinks-community#189]
如下：kibana报错
![image](https://user-images.githubusercontent.com/26991722/182551374-a4434f3a-6eae-490e-b669-ca8a874de1ab.png)
修改了ES密码：
![image](https://user-images.githubusercontent.com/26991722/182551638-8e2e9dcc-d053-4407-bda2-e1ff1f3367db.png)

**Comment by zhou-hao** [comment]
百度一下吧，应该是可以的。
