### ISSUE TITLE
在导入1.20版本的时候  jetlinks-community-1.20/jetlinks-components/configure-component/src/main/java/org/jetlinks/community/configure/device/DeviceSessionMonitor.java 提示语法错误

### ISSUE THREAD

**Issue by go136** [jetlinks/jetlinks-community#190]
将1.20版本 通过idea 导入后， 发现jetlinks-community-1.20/jetlinks-components/configure-component/src/main/java/org/jetlinks/community/configure/device/DeviceSessionMonitor.java  这个类显示语法错误，导致整个项目无法编译通过。我使用的是 java版本是：jdk-8u341-windows-x64
![image](https://user-images.githubusercontent.com/30484303/183364482-cf4d7060-a448-4e00-89ee-0af445287700.png)

**Comment by zhou-hao** [comment]
更新最新代码
