### ISSUE TITLE
自己编写的协议引用了其他类库，接入JetLinks系统后报错

### ISSUE THREAD

**Issue by marshalby2** [jetlinks/jetlinks-community#192]
报错信息：
```
java.lang.NoClassDefFoundError: cn/hutool/core/util/HexUtil
	at com.hiscene.hilink.protocol.TXEventCodec.lambda$decode$0(TXEventCodec.java:58)
```

**Comment by zhou-hao** [comment]
使用shade plugin打包&nbsp;


http://doc.jetlinks.cn/protocol/faq.html#如何在协议包中使用第三方的依赖或者sdk

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: marshalby2 ***@***.***&gt;
发送时间: 2022年8月10日 17:41
收件人: jetlinks/jetlinks-community ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [jetlinks/jetlinks-community] 自己编写的协议引用了其他类库，接入JetLinks系统后报错 (Issue #192)





 
报错信息：
 java.lang.NoClassDefFoundError: cn/hutool/core/util/HexUtil at com.hiscene.hilink.protocol.TXEventCodec.lambda$decode$0(TXEventCodec.java:58)

**Comment by marshalby2** [comment]
谢谢
