### ISSUE TITLE
子设备KeepAliveTime过期无法自动离线

### ISSUE THREAD

**Issue by Xuyilinya** [jetlinks/jetlinks-community#195]
场景：同一个通道，多个设备消息，消息用ChildrenDeviceMessage<DeviceMessage>封装
![image](https://user-images.githubusercontent.com/33318261/186646350-af233a00-52d4-4804-b4e7-aa1326a73fca.png)

1.子设备KeepAliveTime过期无法自动离线，查看代码是因为只能为父设备的session去设置keepOnlineTimeoutSeconds
2.查看代码是有单独处理子设备离线消息的，请问这个触发机制是怎样的。

**Comment by zhou-hao** [comment]
jetlinks什么版本

**Comment by zhou-hao** [comment]
升级到1.20试试

**Comment by Xuyilinya** [comment]
jetlinks-core需要1.1.9，但是还是会有问题，因为DefaultDeviceSessionManager的checkSession方法并不会去检测children中ChildrenDeviceSession的isAlive()，只有网关离线后才回去处理子设备的离线；
![image](https://user-images.githubusercontent.com/33318261/186851630-a5e732c5-4af4-4eba-a533-66e0dd3bd3e5.png)
![image](https://user-images.githubusercontent.com/33318261/186851721-3fac31bd-8df4-4f14-ac3b-990d3c4c3b05.png)

**Comment by zhou-hao** [comment]
升级到1.20吧。这一部分逻辑进行了完全重写。
