### ISSUE TITLE
子设备标签在codec中获取不到

### ISSUE THREAD

**Issue by marshalby2** [jetlinks/jetlinks-community#196]
网关设备的codec中getDevice可以获取的网关设备的DeviceOperator,通过getDevice(childDeviceId)获取到子设备的DeviceOperator,再通过子设备的DeviceOerator.getSelfConfig()或getConfig均无法获取到标签数据。

1.如何在codec.encode方法中如何获取子设备的DeviceOperator?
![image](https://user-images.githubusercontent.com/31735120/187896010-13d16a68-caa9-46e8-91c9-2f2d3da753d3.png)
2.如何获取设备自定义标签和子设备自定义的标签。

**Comment by zhou-hao** [comment]
使用`DeviceDataManager`
