### ISSUE TITLE
上下线日志错乱

### ISSUE THREAD

**Issue by chanlk** [jetlinks/jetlinks-community#198]
背景：使用官方提供的标准mqtt协议
           用手机的mqtt客户端App模拟设备

设备上线之后，手机开启飞行模式，杀死mqtt app， 此目的为模拟设备断网/断电/程序crash等异常情况；
然后恢复手机网络，打开mqtt app再次重连，能正常连接上。

查看后台的设备日志，发现有重复的上线日志，见下图所示；

![image](https://user-images.githubusercontent.com/31768716/188403043-790a10d0-8e01-4b32-b058-6e8b1b97de90.png)

期望：
   上述操作应该产生3条日志，上线 - 下线 - 上线；

**Comment by zhou-hao** [comment]
jetlinks什么版本
