### ISSUE TITLE
【需求】可以制作一个代码生成器吗

### ISSUE THREAD

**Issue by sunw31** [jetlinks/jetlinks-community#2]
虽然 spring boot 倡导可以代码生成就应该内置在框架中

但是不可能不写重复业务，DRY也是相对的。

代码生成器让新手更快上手 平台CRUD业务，菜鸟友好。

++++++++++++++++
附注：特别是 react antd 写起来真不如 vue 方便。

**Comment by zhou-hao** [comment]
目前jetlinks里crud和权限是使用的hsweb4，orm使用的是easyorm4 , crud已经足够精简(最精简只需要写一个实体类和Controller)可以[看看CRUD文档](http://doc.jetlinks.cn/dev-guide/crud.html)，平台的原则还是轻sql重java，不会有复杂的sql语句，代码生成器的场景我认为还是在传统mybatis里用处比较大。但是在jetlinks，增删改查基本上就是写个实体类，动态SQL条件通过ORM已经实现了，复杂查询条件可以直接由前端通过参数传递，无需修改代码。 至于业务功能，其实相对复杂的业务不推荐直接在jetlinks里取做，使用微服务的方式应该更合适。

**Comment by zhou-hao** [comment]
至于前端，历史原因，资源有限。我们欢迎第三方的前端实现！！！有偿的那种。
