### ISSUE TITLE
🐛[BUG]设备属性点击列表查询内容为空

### ISSUE THREAD

**Issue by LiShiLin4510** [jetlinks/jetlinks-community#20]
### 🐛 bug 描述
设备属性点击列表查询内容为空，实际可以从es上查询出来属性上报的内容

### 📷 复现步骤
设备管理---》设备---》运行状态---》属性右上角列表按钮

### 💻 复现代码

![image](https://user-images.githubusercontent.com/27464785/93549662-656bcf00-f99c-11ea-9f98-fe17f1300e05.png)
![image](https://user-images.githubusercontent.com/27464785/93549774-9ea43f00-f99c-11ea-921f-283dfc5a175e.png)
![image](https://user-images.githubusercontent.com/27464785/93549831-c4c9df00-f99c-11ea-8c3c-2204b4d3a687.png)
![image](https://user-images.githubusercontent.com/27464785/93549848-ce534700-f99c-11ea-9241-8bc2fe57910f.png)

### © 版本信息

- Jetlinks-ui-antd 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by LiShiLin4510** [comment]
![image](https://user-images.githubusercontent.com/27464785/93570804-2783a080-f9c6-11ea-814b-19578bddbd75.png)
es日志里有，还是没有查到

**Comment by zhou-hao** [comment]
重新上传数据呢

**Comment by LiShiLin4510** [comment]
日志删除了，重新上传了，1.3版本得时候还可以

**Comment by zhou-hao** [comment]
为啥会有这个参数 

![image](https://user-images.githubusercontent.com/7791838/93572371-53a02100-f9c8-11ea-997c-e3d2497b2012.png)

**Comment by LiShiLin4510** [comment]
这是设备的其中一个属性

**Comment by zhou-hao** [comment]
远程看看？

**Comment by LiShiLin4510** [comment]
![image](https://user-images.githubusercontent.com/27464785/93572491-80543880-f9c8-11ea-96a3-fa69beb77080.png)

**Comment by LiShiLin4510** [comment]
OK

**Comment by LiShiLin4510** [comment]
582646239
4749

**Comment by qiaoyukeji** [comment]
我也是这个问题，点击右上角列表按钮，无法显示数据，请问怎么解决呢，全docker启动，
![image](https://user-images.githubusercontent.com/45252025/221331478-9ef1bc0a-29d8-4617-957e-89f31ef064e3.png)
