### ISSUE TITLE
子设备自注册比较严重的问题

### ISSUE THREAD

**Issue by mervyned** [jetlinks/jetlinks-community#207]
环境说明：
所有代码均是刚刚从git上下载部署的，es使用内嵌（之前测试服务器版es也是同样问题），数据库postgresql（之前测试mysql也是同样问题），服务器运行前redis也是干净的，协议使用的是官方3.0版本（之前测试2.0版本也是同样问题）整个过程如下：
在云平台添加2台网关设备，产品ID为AB001
网关1：设备ID为5c1ff00d0099d10d1ba9（在线）
网关2：设备ID为1c1eceba2aaa01dd1516（在线）
添加一个网关子设备，产品ID为324，设备ID为1000
![image](https://user-images.githubusercontent.com/20469436/197238671-0324870f-764b-466d-8a87-2c95d3356040.png)
①MQTT发送子设备自注册（OK），子设备正常出现在网关1下面，子设备状态为离线；
②子设备属性上报（OK），子设备状态更新为在线；
③在云平台子设备详情页面，【设备功能】里调用功能（OK）
④子设备自注册到网关2下面（OK），子设备正常出现在网关1下面，子设备状态不变；
**⑤在云平台子设备详情页面，【设备功能】里调用功能（NG），云平台发送的TOPIC，网关的设备ID是网关1的；**
之前在群里讨论过好多次这个问题，但是一直没有解决，在git的4a9977903e101b6be05c4c168a796dc726ae4d16这次提交就是针对这个问题优化的，但仍然没解决，希望作者能够重视下这个问题，我这里也会继续调试，我在QQ群里叫蜗牛，有问题随时沟通。
非常感谢平台的开源贡献。

**Comment by mervyned** [comment]
补充下，经过测试，发生这个问题后，在云平台禁用该子设备，再启用，再次进行功能调用，这个时候就会为正常了。

**Comment by mervyned** [comment]
> 补充下，经过测试，发生这个问题后，在云平台禁用该子设备，再启用，再次进行功能调用，这个时候就会为正常了。

上面这句话条件是子设备自注册时selfManageState为true，否则也无效。

**Comment by zhou-hao** [comment]
好的，我们尽快复现一下。 麻烦再提供一个细节，第④步后，如果 子设备离线，然后重新上线，是正常的吗？

**Comment by zhou-hao** [comment]
更新一下，https://github.com/jetlinks/jetlinks-community/commit/eda3a24a805cdc5974a0c645f1ced0810cb928c6 试试。

**Comment by mervyned** [comment]
> 好的，我们尽快复现一下。 麻烦再提供一个细节，第④步后，如果 子设备离线，然后重新上线，是正常的吗？

在子设备自注册到新网关前，旧网关发送子设备离线消息后，子设备自注册到新网关，该条件下没问题的。

**Comment by mervyned** [comment]
> 更新一下，[eda3a24](https://github.com/jetlinks/jetlinks-community/commit/eda3a24a805cdc5974a0c645f1ced0810cb928c6) 试试。

这一版代码经测试可以解决这个问题。
