### ISSUE TITLE
属性数据类型为array, 元素类型为enum时，枚举项保存后会丢失

### ISSUE THREAD

**Issue by oufrank** [jetlinks/jetlinks-community#208]
jetlinks：jetlinks-standalone:1.20.0-SNAPSHOT
直接用 docker-compose up 运行

在产品添加属性时，如果属性数据类型为array, 元素类型为enum时，枚举项保存后提示成功，但再次打开枚举项又变为空白了。
![1666445216794](https://user-images.githubusercontent.com/48525257/197341587-58b53680-38b8-4682-9c42-c31a112f91ac.png)

**Comment by zhou-hao** [comment]
@bestfeng1020 应该是前端的问题，看能否处理。

**Comment by zhou-hao** [comment]
暂时没有时间维护1.20，将在后续版本中进行优化。
