### ISSUE TITLE
在IDEAJ编译时出现 Error:java: java.lang.AssertionError

### ISSUE THREAD

**Issue by leonlee723** [jetlinks/jetlinks-community#21]
Error:java: java.lang.AssertionError
Error:java: 	at jdk.compiler/com.sun.tools.javac.util.Assert.error(Assert.java:155)
我本地的JDK是11，run standalone时出现这个错误

**Comment by zhou-hao** [comment]
请使用java8



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: leonlee723 <notifications@github.com&gt;
发送时间: 2020年9月19日 15:03
收件人: jetlinks/jetlinks-community <jetlinks-community@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[jetlinks/jetlinks-community] 在IDEAJ编译时出现 Error:java: java.lang.AssertionError (#21)





 
Error:java: java.lang.AssertionError
 Error:java: at jdk.compiler/com.sun.tools.javac.util.Assert.error(Assert.java:155)
 我本地的JDK是11，run standalone时出现这个错误
