### ISSUE TITLE
2.0docker一键启动404

### ISSUE THREAD

**Issue by PearLinger** [jetlinks/jetlinks-community#214]
![1666850556533](https://user-images.githubusercontent.com/21024206/198203930-9bfd2062-dbbe-404d-bb2a-6be72d2d1e60.png)

**Comment by zhou-hao** [comment]
这个是1.0的前端啊。

**Comment by PearLinger** [comment]
今天下载2.0的代码之后就可以跑起来了，可能是docker2.0的镜像有缓存，感谢大佬解答
