### ISSUE TITLE
2.0启动项目报错

### ISSUE THREAD

**Issue by yangydq** [jetlinks/jetlinks-community#215]
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method relationManager in org.jetlinks.community.relation.configuration.RelationConfiguration required a bean of type 'org.hswebframework.ezorm.rdb.mapping.ReactiveRepository' that could not be found.

Action:

Consider defining a bean of type 'org.hswebframework.ezorm.rdb.mapping.ReactiveRepository' in your configuration.

**Comment by yangydq** [comment]
错误定位：
 Error creating bean with name 'relationManager' defined in class path resource [org/jetlinks/community/relation/configuration/RelationConfiguration.class]: Unsatisfied dependency expressed through method 'relationManager' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.hswebframework.ezorm.rdb.mapping.ReactiveRepository<org.jetlinks.community.relation.entity.RelatedEntity, java.lang.String>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

**Comment by zhou-hao** [comment]
怎么启动的。开发环境，jdk版本

**Comment by yangydq** [comment]
> 怎么启动的。开发环境，jdk版本

开发工具用的eclipse 现在已经换成idea就可以了
