### ISSUE TITLE
部署成功，访问系统初始化信息接口报错！

### ISSUE THREAD

**Issue by feng-dan** [jetlinks/jetlinks-community#216]
[部署成功，访问系统初始化信息接口报错！.md](https://github.com/jetlinks/jetlinks-community/files/10008412/default.md)

**Comment by zhou-hao** [comment]
你的图都在你本地，也看不到啊

**Comment by feng-dan** [comment]
[default.pdf](https://github.com/jetlinks/jetlinks-community/files/10009693/default.pdf)

**Comment by feng-dan** [comment]
![image](https://user-images.githubusercontent.com/29519215/201837553-53bc6c1c-9065-4adf-8cae-d660cb6db703.png)

**Comment by feng-dan** [comment]
老周，有讨论群吗，留一个😁

**Comment by zhou-hao** [comment]
qq 群 780133058
