### ISSUE TITLE
本地打包成docker镜像后无法连接mysql数据库，本地IDEA启动没问题

### ISSUE THREAD

**Issue by fanxavier** [jetlinks/jetlinks-community#218]
将项目本地打包成docker镜像后用docker启动时无法连接mysql数据库，本地IDEA启动没问题，请问这个问题怎么解决？DockerFile我用的时默认的。

**Comment by zhou-hao** [comment]
具体错误信息是啥，是否已经修改了数据库连接配置

**Comment by fanxavier** [comment]
已修改数据库连接
![image](https://user-images.githubusercontent.com/34829124/203214012-18b8da8c-54f4-48a4-b5c1-2ae645438071.png)

**Comment by fanxavier** [comment]
![image](https://user-images.githubusercontent.com/34829124/203241513-59f25d7d-c17c-47fb-a357-4432660d0c64.png)

**Comment by zhou-hao** [comment]
docker里能访问 127.0.0.1 的数据库？

**Comment by fanxavier** [comment]
那数据库要怎么配置？请大神指教一下

**Comment by zhou-hao** [comment]
填写数据库的内网地址和端口
