### ISSUE TITLE
集群配置参数异常，完整配置是什么

### ISSUE THREAD

**Issue by LiShiLin4510** [jetlinks/jetlinks-community#219]

**Comment by zhou-hao** [comment]
？

**Comment by LiShiLin4510** [comment]
![image](https://user-images.githubusercontent.com/27464785/202407580-ecfdad97-5bce-423f-9293-b0014962e942.png)

这些属性的配置内容

**Comment by LiShiLin4510** [comment]
就是我按照这个类里面的属性在application.yml文件中配置了相应的参数，但是启动的时候报错，想咨询一下这个jetlinks.cluster的配置是什么

**Comment by zhou-hao** [comment]
什么错误

**Comment by LiShiLin4510** [comment]
![image](https://user-images.githubusercontent.com/27464785/202419371-01737e5c-3c9d-4fde-86c3-79b4c4058dd3.png)
启动规则引擎的时候报这个错

**Comment by zhou-hao** [comment]
这是企业版吧。 这个应该是依赖不对吧

**Comment by LiShiLin4510** [comment]
嗯嗯，我是专业版，看到了这个rule-engine-cluster的源码想试试，我引的依赖是1.2.0-SNAPSHOT

**Comment by zhou-hao** [comment]
应该是SchedulerRegistry 配置不正确。

**Comment by zhou-hao** [comment]
和这里应该也没关系。你没添加本地的调度器进去吧

**Comment by LiShiLin4510** [comment]
本地的调度器有，就是rpc的没有

**Comment by zhou-hao** [comment]
这个是集群的时候才会有。 没有集群也会选择本地的调度器进行调度。 检查本地调度器以及调度器的worker

**Comment by LiShiLin4510** [comment]
好的我再排查一下
