### ISSUE TITLE
前后端源码启动，启动正常，登录正常，控制台报错，但是功能无法使用

### ISSUE THREAD

**Issue by yangzelinaaaaa** [jetlinks/jetlinks-community#221]
![报错1](https://user-images.githubusercontent.com/112550534/206644112-6174252c-15fa-43d3-912c-fd84a6bb4961.png)
![报错2](https://user-images.githubusercontent.com/112550534/206644116-143a7d8f-da84-4316-96f3-a3cecb2f653f.png)
idea前端后端的控制台都无报错。有没有大佬可以解决啊？？

**Comment by zhou-hao** [comment]
代理地址配置不对吧

**Comment by yangzelinaaaaa** [comment]
proxy.ts三个都改成后端地址了，用的dev启动。

**Comment by yangzelinaaaaa** [comment]
按理说代理地址不对，登录应该也登录不上的

**Comment by zhou-hao** [comment]
websocket代理地址配置的是啥

**Comment by yangzelinaaaaa** [comment]
这个我还真没配置过。。。这个在哪配置啊大佬，我看文档里也没说

**Comment by yangzelinaaaaa** [comment]
这个我还真没配置过。。。这个在哪配置啊大佬，我看文档里也没说

**Comment by yangzelinaaaaa** [comment]
![Uploading 报错3.png…]()
这里面我都给改了

**Comment by yangzelinaaaaa** [comment]
这里面三个dev，test，pre我都把target改成后端ip地址了

**Comment by yangzelinaaaaa** [comment]
![报错3](https://user-images.githubusercontent.com/112550534/206649051-5c1ba3d6-8a3d-4f9b-a0c6-521ecaf1bf5a.png)

**Comment by zhou-hao** [comment]
前端好像还有一个配置文件吧

**Comment by yangzelinaaaaa** [comment]
哪个啊大哥

**Comment by zhou-hao** [comment]
我也不清楚，要不你搜一下 `/jetlinks` ?

**Comment by yangzelinaaaaa** [comment]
![报错5](https://user-images.githubusercontent.com/112550534/206653201-139b7c66-380f-430a-9cb4-40e3ef5ded6c.png)

**Comment by yangzelinaaaaa** [comment]
这个就直接导航到我设置的后端地址里了

**Comment by zhou-hao** [comment]
你这是啥版本，我看现在的和你的不一样啊 https://github.com/jetlinks/jetlinks-ui-antd/blob/master/config/proxy.ts

**Comment by yangzelinaaaaa** [comment]
我是在gitee上面克隆的，前端好像没有版本，就这一个。https://gitee.com/jetlinks/jetlinks-ui-antd

**Comment by yangzelinaaaaa** [comment]
大哥你运行起来没？用的是nodejs什么版本啊

**Comment by zhou-hao** [comment]
<img width="526" alt="image" src="https://user-images.githubusercontent.com/7791838/206655569-dcf898da-cd5d-4a25-87f1-ff2bae1c0567.png">
这不是有ws地址吗，改成`ws://127.0.0.1:8848`

**Comment by yangzelinaaaaa** [comment]
我试试啊
