### ISSUE TITLE
这种编译报错如何解决？

### ISSUE THREAD

**Issue by xuyoqin** [jetlinks/jetlinks-community#225]
这种编译报错如何解决？
jetlinks-components\notify-component\notify-core\src\main\java\org\jetlinks\community\notify\AbstractNotifier.java:22:38
java: 不兼容的类型: reactor.core.publisher.Mono<org.jetlinks.community.notify.template.Template>无法转换为reactor.core.publisher.Mono<? extends capture#1, 共 ? extends org.jetlinks.community.notify.template.Template>

**Comment by zhou-hao** [comment]
注意使用的java8 版本 1.8.0_3xx 。小版本号300+
