### ISSUE TITLE
新功能建议：触发条件的判断

### ISSUE THREAD

**Issue by RodgerLai** [jetlinks/jetlinks-community#228]
<img width="707" alt="image" src="https://user-images.githubusercontent.com/10798088/210374112-78ae8540-8880-47bb-888c-9cfe2bb33ffc.png">

当前场景联动里的触发条件只能是和手动输入的固定值比较，是否能支持和上一值比较呢？  
比如有判断目标物是否发生位移的场景，就需要当前值和上一值进行比较。

希望能支持这个功能，或者给点建议我们自行二次开发，如果我们自行二次开发是否具有可行性？ 谢谢~

**Comment by zhou-hao** [comment]
即将更新的最新版本 将支持此功能。

**Comment by RodgerLai** [comment]
> 即将更新的最新版本 将支持此功能。
最新的vue版本代码还是不支持与上一值比较，还是只能和手动输入的值比较。  这块是做好了在其他分支吗？
<img width="674" alt="image" src="https://github.com/jetlinks/jetlinks-community/assets/10798088/8c26a563-e059-440b-ade5-1704fe592b8b">
