### ISSUE TITLE
org.jetlinks.core这部分代码是不开放的吧？

### ISSUE THREAD

**Issue by tcexeexe** [jetlinks/jetlinks-community#23]
没有看到对应的源码

**Comment by zhou-hao** [comment]
都在 github.com/jetlinks



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tc_exe <notifications@github.com&gt;
发送时间: 2020年10月2日 12:06
收件人: jetlinks/jetlinks-community <jetlinks-community@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[jetlinks/jetlinks-community] org.jetlinks.core这部分代码是不开放的吧？ (#23)





 
没有看到对应的源码

**Comment by tcexeexe** [comment]
看到了
