### ISSUE TITLE
场景联动 手动触发设备下发参数有问题

### ISSUE THREAD

**Issue by guxin-org** [jetlinks/jetlinks-community#232]
环境: dev V2.0 (前后端已更新至最新)
问题: 添加一个手动触发的场景联动,执行动作为修改设备属性值,设备属性为整形.点击触发后下发指令内容如下图

![image](https://user-images.githubusercontent.com/29875822/211461581-59347fb8-5672-4423-8510-1f4c74bdb4a7.png)

正常下发参数如下
```
{"devices":[{"deviceData":{"light008":6},"deviceId":"slave1"}],"messageId":"1612664261448863744"}
```
从设备面板修改属性正常,只有通过场景联动时会把下发参数改成一个对象,这个需要我从协议中处理吗?

**Comment by zhou-hao** [comment]
bug . 更新一下代码试试
