### ISSUE TITLE
elasticsearch 版本支持

### ISSUE THREAD

**Issue by AlecDS** [jetlinks/jetlinks-community#24]
elasticsearch 支持 哪个版本以上？

**Comment by zhou-hao** [comment]
6.8+



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Alec <notifications@github.com&gt;
发送时间: 2020年10月11日 21:35
收件人: jetlinks/jetlinks-community <jetlinks-community@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[jetlinks/jetlinks-community] elasticsearch 版本支持 (#24)





 
elasticsearch 支持 哪个版本以上？
