### ISSUE TITLE
online/offline 为什么分别定义两个topic

### ISSUE THREAD

**Issue by hchw** [jetlinks/jetlinks-community#242]
/{productId}/{deviceId}/child/{childDeviceId}/online
/{productId}/{deviceId}/child/{childDeviceId}/offline
这两个topic主要是用来处理子设备的在线离线。你们用两个topic会导致不同topic之间不能很好的保证消息的到达顺序。真实情况下，网络抖动造成的设备快速上线离线时有发生，两个topic增加了在线一致性的难度。
我建议将这个两个topic合为1个 。

**Comment by zhou-hao** [comment]
在直连平台内置mqtt的情况下,通常不存在顺序问题. 如果使用mqtt broker是有可能出现的。
这个topic是[官方协议](https://github.com/jetlinks/jetlinks-official-protocol)的定义, 您可以通过自定义协议来实现你说的效果。

**Comment by hchw** [comment]
嗯嗯 ，mqttbroker内部通常的实现是单topic有序。可以自己定义一个新的topic实现上下线。官方协议也建议新增一个topic，逐步弃用这两个topic。😊
