### ISSUE TITLE
参照文档中：最佳实践-设备接入-TCP透传接入-TCP模拟器中运行指令后报错:cannot assign requested address。各位大佬能帮忙看下什么问题？？

### ISSUE THREAD

**Issue by qinjinqiao** [jetlinks/jetlinks-community#246]
执行TCP模拟器指令：benchmark tcp --size=1 --name=tcp --host=127.0.0.1 --port=8803 --script=benchmark/tcp/benchmark.js 之后报错：
cannot assign requested address： no further information：/127.0.0.1:8803

**Comment by zhou-hao** [comment]
https://github.com/jetlinks/device-simulator#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
