### ISSUE TITLE
docker部署访问报503

### ISSUE THREAD

**Issue by gogo1008** [jetlinks/jetlinks-community#248]
![image](https://user-images.githubusercontent.com/36293698/223573866-edd72fbc-1bc7-4ee8-a3b8-86f309de9959.png)
Failed to load resource: the server responded with a status of 502 (Bad Gateway)
:9000/api/system/version:1 Failed to load resource: the server responded with a status of 502 (Bad Gateway)
![image](https://user-images.githubusercontent.com/36293698/223573951-f737c206-4479-41e9-869c-627659116e4c.png)

**Comment by zhou-hao** [comment]
看docker jetlinks-ce-ui 的日志
