### ISSUE TITLE
master分支部署菜单不显示

### ISSUE THREAD

**Issue by lccoll** [jetlinks/jetlinks-community#250]
今天基于master分支的前后端部署启动，打开界面只有统计分析模块，不知道是什么问题，截图如下：

![image](https://user-images.githubusercontent.com/16240583/225264455-4ee7ea46-3144-4a83-8551-84f027398066.png)

**Comment by zhou-hao** [comment]
前端版本不对

**Comment by lccoll** [comment]
后端和前端master不是配套的对吧，那我现在用的后端是master，前端应该用那个版本

**Comment by zhou-hao** [comment]
https://gitee.com/jetlinks/jetlinks-ui-antd 你下的不是官方的吧

**Comment by lccoll** [comment]
仓库里面有两个，我下的估计是研发部那个，已经修复了，感谢
