### ISSUE TITLE
jetlinks-community如何接入tdengine

### ISSUE THREAD

**Issue by 823914102** [jetlinks/jetlinks-community#251]

**Comment by zhou-hao** [comment]
修改`application.yml`相关配置 
https://github.com/jetlinks/jetlinks-community/blob/552dfd550b652f5c1d8250a48a91c1d3a1cc5d0d/jetlinks-standalone/src/main/resources/application.yml#L50-L57

**Comment by cxjcloud** [comment]
如何自行调用存储呢

**Comment by zhou-hao** [comment]
注入`TDengineOperations`

**Comment by wzh195879702** [comment]
> 修改`application.yml`相关配置
> 
> [jetlinks-community/jetlinks-standalone/src/main/resources/application.yml](https://github.com/jetlinks/jetlinks-community/blob/552dfd550b652f5c1d8250a48a91c1d3a1cc5d0d/jetlinks-standalone/src/main/resources/application.yml#L50-L57)
> 
> Lines 50 to 57 in [552dfd5](/jetlinks/jetlinks-community/commit/552dfd550b652f5c1d8250a48a91c1d3a1cc5d0d)
> 
>  tdengine: 
>    enabled: false 
>    database: jetlinks 
>    restful: 
>      endpoints: 
>        - http://localhost:6041/ 
>      username: root 
>      password: taosdata

将这个改为true需要将timescale的配置变为false吗
