### ISSUE TITLE
邮件和钉钉的通知模块报错

### ISSUE THREAD

**Issue by 27986** [jetlinks/jetlinks-community#252]
邮件和钉钉的通知模块报错，想问一下是什么问题呢？
![捕获1](https://user-images.githubusercontent.com/100949502/226900573-a06b24ff-bb06-4ede-ac33-c8dcaec23092.PNG)

**Comment by zhou-hao** [comment]
网络问题？ 链接操作。服务器上能访问对应的域名么

**Comment by 27986** [comment]
确实是网络问题，但是解决后又变成这样了
![image](https://user-images.githubusercontent.com/100949502/227764690-f8617cbe-99a8-4d8c-a27f-6d74dacf6029.png)

**Comment by 27986** [comment]
使用的密码是授权码，不是登录密码，邮箱也开启了smtp服务，想不明白是哪里的问题
