### ISSUE TITLE
macOS M1适配

### ISSUE THREAD

**Issue by yyqangular1** [jetlinks/jetlinks-community#254]
您好，
请问Docker镜像能否build一个适配macOS M1 arm64的版本，目前提供的docker镜像无法在M1上启动。
谢谢～

**Comment by zhou-hao** [comment]
是可以构建arm镜像的。可能需要修改`jetlinks-standalone/Dockerfile`。不过目前官方没有提供arm版本的镜像支持。您可以在m1上手动构建。也可以将自动构建配置PR给我们。
