### ISSUE TITLE
网络流量、cpu使用趋势等组件不显示

### ISSUE THREAD

**Issue by 27986** [jetlinks/jetlinks-community#255]
运维管理的仪表盘上方四个参数可以实时更新，但下方的网络流量、cpu使用趋势等组件不显示
![image](https://user-images.githubusercontent.com/100949502/228384614-f20e3a2e-a45f-4bdd-a752-a4c0d10dba83.png)

**Comment by 27986** [comment]
![捕获3](https://user-images.githubusercontent.com/100949502/228385352-1c81d009-80ad-4c72-b108-2b2e472aab98.PNG)
告警功能可以正常使用，但是也是没有记录

**Comment by zhou-hao** [comment]
检查es 索引是否正常

**Comment by 27986** [comment]
es 索引是正常的
![image](https://user-images.githubusercontent.com/100949502/228958424-31f4b489-49f1-496d-989e-3656a944f460.png)
