### ISSUE TITLE
组件不显示

### ISSUE THREAD

**Issue by 27986** [jetlinks/jetlinks-community#256]
运维管理的仪表盘上方四个参数可以实时更新，但下方的网络流量、cpu使用趋势等组件不显示,但es 索引是正常的
![J{MZEB@UOKH5}`) K8@Z~KF](https://user-images.githubusercontent.com/100949502/230557863-20997072-950a-4161-8477-d5ee4e48ceaa.png)
![YF%YNZ%(6)QS(W7N@4$NV3G](https://user-images.githubusercontent.com/100949502/230557881-d05af123-0e59-44f7-9d50-f0fba5e85196.png)

**Comment by zhou-hao** [comment]
看net_monitor相关索引

**Comment by 27986** [comment]
这四个也是显示green
![image](https://user-images.githubusercontent.com/100949502/230568817-4e805bb5-10ea-4e22-9641-89fececeb5b9.png)

**Comment by zhou-hao** [comment]
net_monitor .用kibana看看吧.

**Comment by zhou-hao** [comment]
不对。社区版 应该没有这个统计

**Comment by zhou-hao** [comment]
社区版目前没有网络流量的统计
