### ISSUE TITLE
添加设备的时候。对应的标准deviceType值没有填进去

### ISSUE THREAD

**Issue by luyongcheng** [jetlinks/jetlinks-community#261]
dev_device_instance表的deviceType字段没有值。导致网关设备绑定子设备筛选有问题。搜索的都是空

**Comment by zhou-hao** [comment]
更新最新代码呢

**Comment by zhou-hao** [comment]
新创建的设备 也没有？

**Comment by luyongcheng** [comment]
嗯。我添加的是子设备

**Comment by zhou-hao** [comment]
检查这个类 https://github.com/jetlinks/jetlinks-community/blob/547e495d56752156177887ccbabef10dfcf40b0f/jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/service/DeviceProductNameSynchronizer.java#L64

**Comment by luyongcheng** [comment]
奇怪了。我刚好没有这个类，代码也拉的最新的。我再重新拉一遍代码试试。
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/12641053/231097194-1167fe51-6ab3-4bb0-b5ce-4e2fdb46c71c.png">

**Comment by luyongcheng** [comment]
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/12641053/231098759-58796868-d842-41bc-a76e-285f28eb0923.png">
是2.0分支没有这个代码。

**Comment by zhou-hao** [comment]
用master分支

**Comment by luyongcheng** [comment]
好的
