### ISSUE TITLE
@Subscribe注解为什么监听不到消息

### ISSUE THREAD

**Issue by 16621737823** [jetlinks/jetlinks-community#271]
我参照了文档的消息订阅写法，想监听所有设备的属性上报消息并使用kafka转发出去，不知为何属性上报后下面这个方法并没有运行
```
    @Subscribe("/device/*/*/message/property/report")//订阅设备的属性上报
    public Mono<Void> propertyReport(ReportPropertyMessage msg){
        return Mono.fromRunnable(()->{
            sendMessageToKafka(msg);
        }).flatMap(mono -> Mono.empty());
    }

    private void sendMessageToKafka(ReportPropertyMessage msg) {
        //将消息通过kafka转发出去
        kafka.send("test", JSON.toJSONString(msg));
    }
```

**Comment by zhou-hao** [comment]
类是否注册到 spring

**Comment by 16621737823** [comment]
> 类是否注册到 spring
使用的@Component注册

**Comment by zhou-hao** [comment]
`kafka.send` 使用的哪个API

**Comment by 16621737823** [comment]
> `kafka.send` 使用的哪个API

KafkaTemplate

**Comment by zhou-hao** [comment]
看一下是否真的注册到spring了？

**Comment by 16621737823** [comment]
> 看一下是否真的注册到spring了？

注册进去了

**Comment by 16621737823** [comment]
> 看一下是否真的注册到spring了？

我在这个方法上打了个断点，但是这个方法就没有执行

**Comment by zhou-hao** [comment]
怎么确定注册进去了？

**Comment by 16621737823** [comment]
> 怎么确定注册进去了？

我在别的类中尝试着注入了我的这个类

**Comment by zhou-hao** [comment]
完整类看看

**Comment by 16621737823** [comment]
@Component
public class DeviceStatusMeasurementProvider extends StaticMeasurementProvider {
    @Autowired
    KafkaTemplate<String, String> kafka;

    private final MeterRegistry registry;

    public DeviceStatusMeasurementProvider(MeterRegistryManager registryManager,
                                           LocalDeviceInstanceService instanceService,
                                           TimeSeriesManager timeSeriesManager,
                                           EventBus eventBus) {
        super(DeviceDashboardDefinition.instance, DeviceObjectDefinition.status);

        addMeasurement(new DeviceStatusChangeMeasurement(timeSeriesManager, eventBus));

        addMeasurement(new DeviceStatusRecordMeasurement(instanceService, timeSeriesManager));

        registry = registryManager.getMeterRegister(DeviceTimeSeriesMetric.deviceMetrics().getId(),
                                                    "target", "msgType", "productId");
    }

    @Subscribe("/device/*/*/online")
    public Mono<Void> incrementOnline(DeviceMessage msg) {
        return Mono.fromRunnable(() -> {
            String productId = parseProductId(msg);
            registry
                .counter("online", "productId", productId)
                .increment();
        });
    }

    @Subscribe("/device/*/*/offline")
    public Mono<Void> incrementOffline(DeviceMessage msg) {
        return Mono.fromRunnable(() -> {
            String productId = parseProductId(msg);
            registry
                .counter("offline", "productId", productId)
                .increment();
        });
    }

    @Subscribe("/device/*/*/message/property/report")//订阅设备的属性上报
    public Mono<Void> propertyReport(ReportPropertyMessage msg){
        return Mono.fromRunnable(()->{
            sendMessageToKafka(msg);
        }).flatMap(mono -> Mono.empty());
    }

    private void sendMessageToKafka(ReportPropertyMessage msg) {//Kafka转发消息模块
        //将消息通过kafka转发出去
        kafka.send("test", JSON.toJSONString(msg));
    }

    private String parseProductId(DeviceMessage msg) {
        return msg
            .getHeader("productId")
            .map(String::valueOf)
            .orElse("unknown");
    }
}

**Comment by 16621737823** [comment]
> 完整类看看

```
@Component
public class DeviceStatusMeasurementProvider extends StaticMeasurementProvider {
    @Autowired
    KafkaTemplate<String, String> kafka;

    private final MeterRegistry registry;

    public DeviceStatusMeasurementProvider(MeterRegistryManager registryManager,
                                           LocalDeviceInstanceService instanceService,
                                           TimeSeriesManager timeSeriesManager,
                                           EventBus eventBus) {
        super(DeviceDashboardDefinition.instance, DeviceObjectDefinition.status);

        addMeasurement(new DeviceStatusChangeMeasurement(timeSeriesManager, eventBus));

        addMeasurement(new DeviceStatusRecordMeasurement(instanceService, timeSeriesManager));

        registry = registryManager.getMeterRegister(DeviceTimeSeriesMetric.deviceMetrics().getId(),
                                                    "target", "msgType", "productId");
    }

    @Subscribe("/device/*/*/online")
    public Mono<Void> incrementOnline(DeviceMessage msg) {
        return Mono.fromRunnable(() -> {
            String productId = parseProductId(msg);
            registry
                .counter("online", "productId", productId)
                .increment();
        });
    }

    @Subscribe("/device/*/*/offline")
    public Mono<Void> incrementOffline(DeviceMessage msg) {
        return Mono.fromRunnable(() -> {
            String productId = parseProductId(msg);
            registry
                .counter("offline", "productId", productId)
                .increment();
        });
    }

    @Subscribe("/device/*/*/message/property/report")//订阅设备的属性上报
    public Mono<Void> propertyReport(ReportPropertyMessage msg){
        return Mono.fromRunnable(()->{
            sendMessageToKafka(msg);
        }).flatMap(mono -> Mono.empty());
    }

    private void sendMessageToKafka(ReportPropertyMessage msg) {//Kafka转发消息模块
        //将消息通过kafka转发出去
        kafka.send("test", JSON.toJSONString(msg));
    }

    private String parseProductId(DeviceMessage msg) {
        return msg
            .getHeader("productId")
            .map(String::valueOf)
            .orElse("unknown");
    }
}
```

**Comment by zhou-hao** [comment]
没有报错？

**Comment by 16621737823** [comment]
控制台一直有一个
io.vertx.mqtt.MqttConnectionException: Connection failed: CONNECTION_REFUSED_BAD_USER_NAME_OR_PASSWORD
	at io.vertx.mqtt.impl.MqttClientImpl.handleConnack(MqttClientImpl.java:1258)
	at io.vertx.mqtt.impl.MqttClientImpl.handleMessage(MqttClientImpl.java:929)
	at io.vertx.mqtt.impl.MqttClientImpl.lambda$null$0(MqttClientImpl.java:271)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
	at io.vertx.core.impl.ContextBase.emit(ContextBase.java:239)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:394)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:157)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java

**Comment by 16621737823** [comment]
> 没有报错？

控制台一直有一个
io.vertx.mqtt.MqttConnectionException: Connection failed: CONNECTION_REFUSED_BAD_USER_NAME_OR_PASSWORD
at io.vertx.mqtt.impl.MqttClientImpl.handleConnack(MqttClientImpl.java:1258)
at io.vertx.mqtt.impl.MqttClientImpl.handleMessage(MqttClientImpl.java:929)
at io.vertx.mqtt.impl.MqttClientImpl.lambda$null$0(MqttClientImpl.java:271)
at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
at io.vertx.core.impl.ContextBase.emit(ContextBase.java:239)
at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:394)
at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:157)
at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java

**Comment by zhou-hao** [comment]
这个是mqtt都没连上来

**Comment by 16621737823** [comment]
> 这个是mqtt都没连上来

这个mqtt的连接我应该在哪里配置呢

**Comment by zhou-hao** [comment]
设备连接的时候

**Comment by 16621737823** [comment]
> 设备连接的时候
但是我启动服务以后设备的属性上报是正常的

**Comment by zhou-hao** [comment]
设备日志里类型是啥

**Comment by 16621737823** [comment]
![image](https://user-images.githubusercontent.com/98886401/233252445-af9d8731-7425-4fdd-9046-79689169f4b1.png)

**Comment by zhou-hao** [comment]
看看 `DeviceStatusMeasurementProvider `这个类 编译后的class，反编译后和源代码是否一致

**Comment by zhou-hao** [comment]
请问问题解决了吗？

**Comment by 16621737823** [comment]
> 请问问题解决了吗？

这个功能是不是只有企业版才有
