### ISSUE TITLE
项目导入eclipse项目异常，jdk 1.8.260

### ISSUE THREAD

**Issue by zyy71897** [jetlinks/jetlinks-community#272]
pom异常：Plugin execution not covered by lifecycle configuration: org.codehaus.gmavenplus:gmavenplus-plugin:1.6.1:compile (execution: default, phase: compile)
pom异常：Missing artifact com.sun:tools:jar:1.8.0

**Comment by zhou-hao** [comment]
命令行中执行 `mvn compile` 看是否报错.
ps. eclipse对多模块maven支持似乎不太好,建议使用Idea作为开发环境

**Comment by zyy71897** [comment]
编译是正常的

**Comment by zhou-hao** [comment]
那说明程序是没问题的。 应该是eclipse哪里没识别对
