### ISSUE TITLE
设备接入问题

### ISSUE THREAD

**Issue by pengyong25** [jetlinks/jetlinks-community#280]
我想问下，jetlinks平台社区版和企业版分别支持设备接入的最大值大概是多少啊

**Comment by zhou-hao** [comment]
程序上并没有做限制，能接入多少取决于服务器性能以及消息持久化方式。  
企业版支持集群,可以横向拓展, 在8核16G的服务器上,大概10万长连接,2w/s消息上报是比较合适的，实际影响因素有很多。

**Comment by pengyong25** [comment]
> 程序上并没有做限制，能接入多少取决于服务器性能以及消息持久化方式。 企业版支持集群，可以横向拓展， 在8核16G的服务器上，大概10万长连接，2w/s消息上报是比较合适的，实际影响因素有很多。

现在我们有个50W设备连接的需求，在我们服务器资源充足的前提下，企业版的集群部署可以满足这个需求么，有没有过这种的案例

**Comment by zhou-hao** [comment]
可以满足的。连接数量其实对系统资源占用不会太大，主要是看消息的并发数，以及对消息的处理逻辑，比如 消息是否持久化，是否转发到其他地方如kafka等。
