### ISSUE TITLE
设备上线下线等状态变化话好像没有往eventbus中发送消息

### ISSUE THREAD

**Issue by 16621737823** [jetlinks/jetlinks-community#282]
![image](https://github.com/jetlinks/jetlinks-community/assets/98886401/1a81db95-a0eb-4b43-a654-594d44d810e7)
设备发生了状态变化，但是并没有在eventbus中监听到任何消息，设备接入流程参考的最佳实践中的MQTT接入

**Comment by 16621737823** [comment]
是上传的协议jar包出问题了吗

**Comment by zhou-hao** [comment]
什么版本。 怎么监听的。 这个日志记录也是从eventbus中监听的数据 然后写入的数据库。

**Comment by 16621737823** [comment]
2.0版本，可是设备上下线的时候系统自带的这两个方法也没触发断点并没有执行
![image](https://github.com/jetlinks/jetlinks-community/assets/98886401/85572289-25bb-49a7-8e76-30816e8231d6)

**Comment by iyeee** [comment]
> 2.0版本，可是设备上下线的时候系统自带的这两个方法也没触发断点并没有执行 ![image](https://user-images.githubusercontent.com/98886401/237279837-85572289-25bb-49a7-8e76-30816e8231d6.png)

您好，请问问题解决了吗

**Comment by zhou-hao** [comment]
未能复现此问题，有更多进展请再次回复此issues。
