### ISSUE TITLE
Is jetlink-vew only for commercial use?

### ISSUE THREAD

**Issue by nadeda** [jetlinks/jetlinks-community#285]
Is jetlink-vew only for commercial use?
where i see price policy?

**Comment by zhou-hao** [comment]
https://www.jetlinks.cn/#/contact_us

**Comment by nadeda** [comment]
thanks for reply.
i'm in korea so i can't use qq.
can i contact another method?

**Comment by zhou-hao** [comment]
do you have wechat?

**Comment by nadeda** [comment]
yes i have wechat
