### ISSUE TITLE
设备管理-设备-物模型

### ISSUE THREAD

**Issue by choupoem** [jetlinks/jetlinks-community#287]
物模型这一块是否能够增加设备影子这个功能，这个功能针对网络连接不稳定的设备或者短连接的设备，期望状态同步很重要

**Comment by zhou-hao** [comment]
对于设备状态。可以在DeviceMessage的headers中增加 `keepOnline`和`keepOnlineTimeoutSeconds` 头信息来让设备保存在线:
```java
message.addHeader(Headers.keepOnline,true);
message.addHeader(Headers.keepOnlineTimeoutSeconds,3600);// -1为永远在线
```

**Comment by choupoem** [comment]
您这个是相当于平台上是假在线，如果设备刚好不在线的时候，进行数据下发，实际上并没有执行啊。我看了1.X版本的说明文档，里面有设备影子这个功能的，为啥2.X版本就把这个功能给去掉了呢

**Comment by zhou-hao** [comment]
目前可以通过在协议包里通过拦截器 处理设备离线时的指令，缓存到`DeviceOperator#setConfig`中，在后续可通过`DeviceOperator#getSelfConfig`获取缓存信息进行处理。

1.x 的设备影子功能其实只是缓存的设置可查看放到了界面上,平台并没有自动化处理，最终是需要在协议包里处理的。因此2.0中暂时将此功能取消了,后续根据需求可能会进行重新设计。

**Comment by choupoem** [comment]
感谢指导，我觉着这个功能还是很有必要的，希望能早点看到有完整的设备影子功能。谢谢！
