### ISSUE TITLE
自定义协议开发，接入设备问题（无法从TCP消息中获取设备信息）

### ISSUE THREAD

**Issue by wpeng-coder** [jetlinks/jetlinks-community#288]
获取设备信息，session.getOperator()这里始终都是null
![image](https://github.com/jetlinks/jetlinks-community/assets/73539392/f5c80995-7e80-4897-b197-785a2e06066e)

![image](https://github.com/jetlinks/jetlinks-community/assets/73539392/8eef017f-1509-4b04-abd0-ced965923361)

**Comment by zhou-hao** [comment]
`0030310011`这个设备， 没有在平台里添加或者没有启用。

**Comment by wpeng-coder** [comment]
这个设备在平台是有的，是启用状态

**Comment by zhou-hao** [comment]
> 这个设备在平台是有的，是启用状态

检查设备ID是否完全一致，重新启用一下试试。

**Comment by wpeng-coder** [comment]
> > 这个设备在平台是有的，是启用状态
> 
> 检查设备ID是否完全一致，重新启用一下试试。

我刚试了启用和禁用，感觉和设备的这个状态没有关系

**Comment by wpeng-coder** [comment]
> > 这个设备在平台是有的，是启用状态
> 
> 检查设备ID是否完全一致，重新
