### ISSUE TITLE
告警日志包含了没有设置的属性告警

### ISSUE THREAD

**Issue by tangguofeng** [jetlinks/jetlinks-community#289]
温湿度传感器设备设置了属性温度不在0-20区间告警，但是没设置属性湿度的告警，但是在告警日志里却包含了湿度的告警日志，这是不是bug

**Comment by zhou-hao** [comment]
麻烦截图看一下日志内容，有可能是你上报的时候同时携带了湿度值的吧。 场景联动的逻辑时： 订阅设备属性上报消息，匹配配置的条件，然后出发。如果你没有上报温度，应该也会满足不在0-20的区间，可以使用 大于0并且小于等于20试试？

**Comment by tangguofeng** [comment]
![image](https://github.com/jetlinks/jetlinks-community/assets/30994750/ae361db8-2685-4b69-90bd-4e1f604eb79e)
![image](https://github.com/jetlinks/jetlinks-community/assets/30994750/b63f876f-10b1-4aea-b7c0-1cb67a6e615d)
![image](https://github.com/jetlinks/jetlinks-community/assets/30994750/81451377-318b-43bf-ac2b-1a0dc2fec2ec)
这几个是我的场景配置、告警湿度日志和设备的属性配置，按照场景的配置，我选的是温度，不应该有湿度的吧？还有场景配置里没有大于、小于这种条件，只有在...之中，不在....之中这种
![image](https://github.com/jetlinks/jetlinks-community/assets/30994750/f5b930dd-aaef-4943-864d-4280feb98308)

**Comment by zhou-hao** [comment]
物模型的类型使用float类型试试。不要使用字符串类型。
