### ISSUE TITLE
源码在本地用 Docker部署的话，项目的数据库在哪里找？

### ISSUE THREAD

**Issue by abc123321123321123** [jetlinks/jetlinks-community#293]
![image](https://github.com/jetlinks/jetlinks-community/assets/125645559/347734c0-7e97-4142-99e5-6f7d677580c1)

**Comment by zhou-hao** [comment]
jetlinks-ce-postgres 就是数据库

**Comment by abc123321123321123** [comment]
感谢，已经知晓
