### ISSUE TITLE
设备详情空白页面

### ISSUE THREAD

**Issue by JeffYoungL** [jetlinks/jetlinks-community#3]
选择设备实例列表中的单个设备，点击“查看”按钮，偶尔会出现加载出来空白的页面
![bug](https://user-images.githubusercontent.com/19849571/78348004-e3e1d980-75d3-11ea-93a6-40cbcf8c3189.png)

**Comment by zhou-hao** [comment]
麻烦提供一下浏览器控制台的错误日志信息

**Comment by JeffYoungL** [comment]
![bug1](https://user-images.githubusercontent.com/19849571/78351020-b64b5f00-75d8-11ea-9743-b49b545bea58.png)

**Comment by zhou-hao** [comment]
能不能看到接口返回的结果 
![image](https://user-images.githubusercontent.com/7791838/78352446-e98eed80-75da-11ea-823f-32ac3a90164c.png)

**Comment by JeffYoungL** [comment]
![bug2](https://user-images.githubusercontent.com/19849571/78771542-e624a900-79c2-11ea-8c13-4c611d4cd499.png)

**Comment by JeffYoungL** [comment]
qq群里我也提问了，这个应该是设备刚创建还没连接过的时候的bug

**Comment by zhou-hao** [comment]
已修复 https://github.com/jetlinks/jetlinks-community/commit/91a678e5ad5cffc8657abdaeae4eefc766807e6f
