### ISSUE TITLE
添加产品的时候提示：Not Found /device-product/1663782613685121024/1663782450077904896/config-metadata

### ISSUE THREAD

**Issue by OKCrash** [jetlinks/jetlinks-community#300]
版本：社区版

安装方式：按照版本要求源码安装

在安装成功后进入系统，按照步骤开始创建产品，在给产品配置“接入方式”的时候报这个错：
Not Found /device-product/1663782613685121024/1663782450077904896/config-metadata
[https://github.com/OKCrash/law-cn-ai-new/blob/main/error.png](url)

日志：2023-05-31 14:26:47.898 DEBUG 32608 --- [or-http-epoll-4] o.h.w.s.j.CustomJackson2jsonEncoder      : [08ec61e8-884] Encoding [{timestamp=Wed May 31 14:26:47 CST 2023, path=/device-product/1663782613685121024/166117975234703769 (truncated)...]

**Comment by zhou-hao** [comment]
使用最新master分支代码试试
