### ISSUE TITLE
使用docker部署到，添加协议时报错

### ISSUE THREAD

**Issue by me126132** [jetlinks/jetlinks-community#301]
使用docker部署的，能正常打开，但无法添加协议，上传了协议jar文件后，点击确认就报错

无法加载协议:finishConnect(..) failed: Connection refused: localhost/127.0.0.1:9000; nested exception is io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:9000

**Comment by zhou-hao** [comment]
<img width="945" alt="image" src="https://github.com/jetlinks/jetlinks-community/assets/7791838/37bd9e30-22e6-4575-b8b5-ea5c623d1131">
这个地址修改为ip地址。

**Comment by me126132** [comment]
请问下是这么改吗，改了好像也是不行

![image](https://github.com/jetlinks/jetlinks-community/assets/29776529/2db38e80-9135-4a3c-8641-457e940dcd9a)
![image](https://github.com/jetlinks/jetlinks-community/assets/29776529/15d86c31-7cc2-4193-820c-06990c52a763)

**Comment by me126132** [comment]
解决了，万分感谢
