### ISSUE TITLE
http协议支持对属性读写问题，es无最新数据

### ISSUE THREAD

**Issue by wnsojn** [jetlinks/jetlinks-community#306]
http协议支持对属性读写问题，手动实现读写http接口,日志管理存在读取属性回复，存储数据es数据未写入

**Comment by wnsojn** [comment]
如果http平台对接，需要实现属性读写功能，是否需要调用http接口读取数据，然后在数据上报，以实现网联网平台存储数据

**Comment by zhou-hao** [comment]
在协议包里调用就行。
