### ISSUE TITLE
用户登录问题

### ISSUE THREAD

**Issue by chuck199202104** [jetlinks/jetlinks-community#31]
> `` return beforeEvent
                                    .publish(eventPublisher)
                                    .then(authenticationManager
                                            .authenticate(Mono.just(new PlainTextUsernamePasswordAuthenticationRequest(username, password)))
                                            .switchIfEmpty(Mono.error(() -> new AuthenticationException(AuthenticationException.ILLEGAL_PASSWORD,"密码错误")))
                                            .flatMap(auth -> {
                                                //触发授权成功事件
                                                AuthorizationSuccessEvent event = new AuthorizationSuccessEvent(auth, parameterGetter);
                                                event.getResult().put("userId", auth.getUser().getId());
                                                return event
                                                        .publish(eventPublisher)
                                                        .then(Mono.fromCallable(event::getResult));
                                            }));

用户登录的这段代码中，如果用户已经删除了，那么如果用删除的用户名去登录，我认为需要去做特殊处理.而不能所有的归咎为密码错误这种异常

**Comment by zhou-hao** [comment]
为了防止用户名碰撞攻击，所以无法获取到认证信息时,均返回密码错误。如果先自定义提示信息,可在自定义authenticationManager中进行提示
