### ISSUE TITLE
设置轮训参数+告警，不相干的设备也会产生告警。

### ISSUE THREAD

**Issue by PengyuDeng** [jetlinks/jetlinks-community#311]
我现在有两个产品A、B，A产品只有一个设备X，B产品只有一个设备Y，
操作：规则引擎-产品联动，设置轮训产品A的所有设备属性值。当某个属性=72的时候告警。
现象：会出现两个告警，Y设备也会出现这个告警。
如图所示：
设置轮训
![image](https://github.com/jetlinks/jetlinks-community/assets/89559616/2340b155-6e08-45ec-8556-1a5417a00f91)
配置告警
![image](https://github.com/jetlinks/jetlinks-community/assets/89559616/55ab908b-ef35-4eef-9850-ac6b884cc75c)
产品旗下的设备只有一个
![image](https://github.com/jetlinks/jetlinks-community/assets/89559616/1626aeba-1193-4170-a890-cecdec29fd88)
告警是两个
![image](https://github.com/jetlinks/jetlinks-community/assets/89559616/0af688ea-002c-4f82-9a64-add85f771207)
![image](https://github.com/jetlinks/jetlinks-community/assets/89559616/e1c3b3bb-33a4-4cfe-afbd-82359c5d8c49)

**Comment by PengyuDeng** [comment]
补充一下，还有一个问题，轮训下发topic。不相干的设备收到了轮训消息。
一下是我们的软件网关的日志
![image](https://github.com/jetlinks/jetlinks-community/assets/89559616/1f00a88f-0fd1-461e-858d-d824dffd2014)

**Comment by PengyuDeng** [comment]
好的我试一试

> 更新最新代码再试试

**Comment by zhou-hao** [comment]
如何

**Comment by PengyuDeng** [comment]
棒，CN最好用的物联网平台！
