### ISSUE TITLE
CONNECTION_REFUSED_SERVER_UNAVAILABLE

### ISSUE THREAD

**Issue by MoonBottle** [jetlinks/jetlinks-community#315]
今天遇到设备集体掉线，发现是这里显示获取不到 handled
请问下可能是什么原因

org.jetlinks.community.network.mqtt.server.vertx.VertxMqttServer#handleConnection(org.jetlinks.community.network.mqtt.server.vertx.VertxMqttConnection)
```java
    private void handleConnection(VertxMqttConnection connection) {
        boolean anyHandled = emitNext(sink, connection);

        for (List<Sinks.Many<MqttConnection>> value : sinks.values()) {
            if (value.size() == 0) {
                continue;
            }
            Sinks.Many<MqttConnection> sink = value.get(ThreadLocalRandom.current().nextInt(value.size()));
            if (emitNext(sink, connection)) {
                anyHandled = true;
            }
        }
        if (!anyHandled) {
            log.error("no anyHandled，MQTT 服务拒绝创建连接");
            connection.reject(MqttConnectReturnCode.CONNECTION_REFUSED_SERVER_UNAVAILABLE);
        }
    }
```

**Comment by zhou-hao** [comment]
检查设备接入网关是否启动正常。

**Comment by MoonBottle** [comment]
服务是正常运行中，设备全部掉线，然后上述代码报错，服务重启后设备就正常注册上来了
![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/24d849a6-1367-4eef-96f9-a71a66710da2)

**Comment by MoonBottle** [comment]
> 检查设备接入网关是否启动正常。

网关应该是正常起动了吧 - -

**Comment by zhou-hao** [comment]
你使用的是哪个版本。中间是否有报错。

**Comment by MoonBottle** [comment]
master 分支，截至到图中的 commit 
![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/d3fd7fdd-2d9f-460b-9eae-866be65b4e9f)

前面发现报了一次内存不足
![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/65fede24-da45-48c8-a214-acaa5f3f9d2d)

**Comment by zhou-hao** [comment]
这个处理实际上好像意义不大，我删掉了，用最新代码再试试？出现问题时的 内存占用高不高。

**Comment by MoonBottle** [comment]
这个处理 指的是 anyHandled 还是 内存啊

我合并下最新代码，下次发版带上去试试

**Comment by MoonBottle** [comment]
> 这个处理实际上好像意义不大，我删掉了，用最新代码再试试？出现问题时的 内存占用高不高。

没装监控程序，看不到历史占用了，尴尬 - -

**Comment by zhou-hao** [comment]
> 这个处理 指的是 anyHandled 还是 内存啊
> 
> 我合并下最新代码，下次发版带上去试试

内存判断没有意义。

**Comment by MoonBottle** [comment]
我发上去了，观察观察

**Comment by zhou-hao** [comment]
先关了，有问题直接回复。
