### ISSUE TITLE
添加好的产品和设备，经过一段时间后查看详情会报 “不支持的协议：。。。“

### ISSUE THREAD

**Issue by tangguofeng** [jetlinks/jetlinks-community#316]
第一、点击产品或者设备会报
![image](https://github.com/jetlinks/jetlinks-community/assets/30994750/65da859a-f8f8-4eef-9fd4-36e57e5c791a)
第二、项目启动的时候会报
![image](https://github.com/jetlinks/jetlinks-community/assets/30994750/f3b58725-67cf-448e-bf81-68821f7d57f9)

**Comment by tangguofeng** [comment]
redis数据一丢失，就不能复原了吗？重新禁用启用也不行

**Comment by tangguofeng** [comment]
而且redis是在服务器上的，好像没有关机过，也没设置密码

**Comment by zhou-hao** [comment]
多半是redis被黑了。重新安装redis。设置好密码。最好关闭公网访问。然后重新发布协议包，产品，设备。

**Comment by tangguofeng** [comment]
重新发布协议包，产品，设备是指删了再重新加？这样如果设备很多，那不是累死

**Comment by tangguofeng** [comment]
其实还有个场景我试了下，就是我本地的都是连了本地的redis是没问题的，然后我后台改了服务器的redis，启动后报错，再改回来启动本地的也报错了，这个也有影响的吗，这期间本地的redis不会动的

**Comment by zhou-hao** [comment]
产品的话，重新保存一下。 设备的话有批量操作 激活

**Comment by 491134648** [comment]
我也是碰到这问题，redis是内网的，有设置密码，应该不存在被黑，重新上传jar包，过一段时间后才有，就算是redis数据删了，重启后不会重新加载吗？
