### ISSUE TITLE
场景联动404

### ISSUE THREAD

**Issue by sanwanliu** [jetlinks/jetlinks-community#32]
![image](https://user-images.githubusercontent.com/23079982/103620554-ab11cf00-4f6e-11eb-8a90-e40ef34d1e69.png)
跑起来后，访问后台管理场景联动，跳404页面，看接口是返回404。这个功能是社区版不支持吗
（前后端都是1.7分支）

**Comment by Lind-pro** [comment]
社区版不支持



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "firo"<notifications@github.com&gt;; 
发送时间: 2021年1月5日(星期二) 下午4:00
收件人: "jetlinks/jetlinks-community"<jetlinks-community@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [jetlinks/jetlinks-community] 场景联动404 (#32)





 

 跑起来后，访问后台管理场景联动，跳404页面，看接口是返回404。这个功能是社区版不支持吗
 （前后端都是1.7分支）
