### ISSUE TITLE
协议管理无法上传jar后缀文件

### ISSUE THREAD

**Issue by philyang7** [jetlinks/jetlinks-community#322]
云服务器公网部署且所有服务部署在一台服务器中。
pgsql，es，tdengine，redis使用docker部署，nginx和jar非docker部署。

base-path设置为本机内网IP地址：
<img width="246" alt="image" src="https://github.com/jetlinks/jetlinks-community/assets/42790947/56aaaad7-7648-4aa3-9bfb-77edc0ff4ae8">
设置成公网IP也试了也不行

以下是nginx.conf
<img width="581" alt="image" src="https://github.com/jetlinks/jetlinks-community/assets/42790947/459b9621-8e0d-495b-a4ee-013ecc381091">

运行后在协议管理中上传文件提示：
<img width="971" alt="image" src="https://github.com/jetlinks/jetlinks-community/assets/42790947/db56891d-39b6-48fb-bfe0-cf935c48c25e">
<img width="730" alt="image" src="https://github.com/jetlinks/jetlinks-community/assets/42790947/74e8a1a0-5272-440b-bb3e-ae3de33bf56c">

我在file/upload方法第一行输出了日志，结果上传jar文件时日志并未输出。

nginx记录的日志状态码显示为400：
"POST /api/file/upload HTTP/1.1" 400 0 "http://36.xxx.xxx.x9:9000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"

而且很奇怪的是，除了.jar后缀以外的文件均能上传：
<img width="763" alt="image" src="https://github.com/jetlinks/jetlinks-community/assets/42790947/3e81ca8b-8d85-4fa5-8772-df17c51f2a63">

盼复

**Comment by zhou-hao** [comment]
通常是服务器防火墙的限制。可以把jar后缀改成zip即可。
