### ISSUE TITLE
Error:(49, 26) java: 名称冲突: 具有相同疑符, 但两者均不覆盖对方

### ISSUE THREAD

**Issue by libertyarow** [jetlinks/jetlinks-community#33]
Error:(49, 26) java: 名称冲突: <匿名org.jetlinks.community.configuration.CommonConfiguration$2>中的<T>convert(java.lang.Class<T>,java.lang.Object)和org.apache.commons.beanutils.Converter中的convert(java.lang.Class,java.lang.Object)具有相同疑符, 但两者均不覆盖对方

**Comment by zhou-hao** [comment]
java版本请使用1.8.0_2xx
