### ISSUE TITLE
自定义协议问题

### ISSUE THREAD

**Issue by BoredMonkey** [jetlinks/jetlinks-community#335]
![image](https://github.com/jetlinks/jetlinks-community/assets/31086873/996a1f78-8404-45b4-8c75-db1ecadd41fe)
当我需要给设备或者平台返回消息的时候调用send 方法是看到代码里是直接返回空的，并且这里是直接创建了一个UnknownHttpDeviceSession 
![image](https://github.com/jetlinks/jetlinks-community/assets/31086873/c823158f-b9bb-4465-bd7d-c136670ba12c)
我想返回给设备会平台的消息应该怎么做，下面是我的测试代码
![image](https://github.com/jetlinks/jetlinks-community/assets/31086873/e7560b05-47b7-48ca-93f9-c6a72d03397a)
![image](https://github.com/jetlinks/jetlinks-community/assets/31086873/d1b1f1b5-a49c-4afc-8374-b191ed756a0d)

**Comment by BoredMonkey** [comment]
我应该怎么做解决这个问题，让我能够自定义返回给设备或者平台消息

**Comment by zhou-hao** [comment]
参照官方http协议。https://github.com/jetlinks/jetlinks-official-protocol/blob/v3/src/main/java/org/jetlinks/protocol/official/http/JetLinksHttpDeviceMessageCodec.java#L115
