### ISSUE TITLE
部署到服务器 添加协议时，接口响应超时。在本机没有这个问题，也无报错信息。

### ISSUE THREAD

**Issue by Roioi** [jetlinks/jetlinks-community#339]
![image](https://github.com/jetlinks/jetlinks-community/assets/109651260/9ac6c614-2043-46cb-b139-092c8c81e8e7)

**Comment by Roioi** [comment]
部署到服务器，点击确认显示响应超时，在本机运行确没有这个问题

**Comment by zhou-hao** [comment]
检查在服务器上能否访问到协议文件地址

**Comment by Roioi** [comment]
![image](https://github.com/jetlinks/jetlinks-community/assets/109651260/53d447dc-71ef-439f-a144-4fa9d56eb71c)
感谢回复！我检查了一下是可以访问到协议文件地址的。我看了文档感觉应该是我的base-path出现问题。但base-path登陆后自动填写的。检查了一下域名也没错。但还是报
![image](https://github.com/jetlinks/jetlinks-community/assets/109651260/059368f2-0b21-4c56-a4b3-b7dad2292963)

**Comment by zhou-hao** [comment]
服务器中无法访问这个地址。建议在服务器上 配置hosts文件，映射域名到内网ip。
