### ISSUE TITLE
mongo的jar包也要引用？

### ISSUE THREAD

**Issue by libertyarow** [jetlinks/jetlinks-community#35]
Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.boot.autoconfigure.mongo.MongoClientFactorySupport.applyUuidRepresentation(MongoClientFactorySupport.java:85)

The following method did not exist:

    com.mongodb.MongoClientSettings$Builder.uuidRepresentation(Lorg/bson/UuidRepresentation;)Lcom/mongodb/MongoClientSettings$Builder;

The method's class, com.mongodb.MongoClientSettings$Builder, is available from the following locations:

    jar:file:/D:/mongo-java-driver-3.11.0.jar!/com/mongodb/MongoClientSettings$Builder.class

The class hierarchy was loaded from the following locations:

    com.mongodb.MongoClientSettings.Builder: file:/D:/mongo-java-driver-3.11.0.jar

**Comment by zhou-hao** [comment]
你修改了啥配置？
