### ISSUE TITLE
自定义jar包协议修改重新发布不生效

### ISSUE THREAD

**Issue by zhoufa** [jetlinks/jetlinks-community#37]
jetlinks版本： 1.8.0
项目可正常启动，操作。在修改自定义jar包协议，并重新上传关重新发布后，未生效，本地项目重启后可正常使用
jdk: 1.8
其它的都按代码版本进行安装，windows10
问： 修改协议后，在重新发布之后，未生效的原因。

**Comment by zhou-hao** [comment]
怎么验证的

**Comment by zhoufa** [comment]
自己写的协议，可正常上下线和通信， 添加一行 log.info("========周期数据=====");重新打包，上传并重新发布，此日志不生效，  在项目重启之后，这行日志即可正常打印

**Comment by zhoufa** [comment]
2021年2月27号11点半，下载最新的master分支，此功能OK了
