### ISSUE TITLE
设备管理，设备状态不正确

### ISSUE THREAD

**Issue by 4FYamedeaR** [jetlinks/jetlinks-community#371]
删除es索引、修改mysql设备表状态字段、重启后台都不行。麻烦帮忙看一下
![1689932832080](https://github.com/jetlinks/jetlinks-community/assets/105576840/7036df28-face-4d1d-8249-41e043abc27d)

**Comment by 4FYamedeaR** [comment]
代码版本为1.13版本，一直使用的这个版本代码，有时会出现这种情况

**Comment by zhou-hao** [comment]
更新下代码试试？或者升级到1.20。
