### ISSUE TITLE
CompositeProtocolSupport 无法设置 deviceStateChecker

### ISSUE THREAD

**Issue by andaren** [jetlinks/jetlinks-community#375]
CompositeProtocolSupport 无法设置 deviceStateChecker，getStateChecker() 方法结果必然是空的，是不是漏掉了set方法？

**Comment by zhou-hao** [comment]
怎么设置的

**Comment by andaren** [comment]
比如: setStateChecker(DeviceStateChecker deviceStateChecker)

**Comment by zhou-hao** [comment]
在哪看的 `getStateChecker() `为空

**Comment by andaren** [comment]
啊，看的Pro...
