### ISSUE TITLE
BUG：设备-标签-标签选择枚举类型相关

### ISSUE THREAD

**Issue by PengyuDeng** [jetlinks/jetlinks-community#390]
首先物模型定义一个枚举类型的标签：![image](https://github.com/jetlinks/jetlinks-community/assets/89559616/9fac31f2-abf0-43d6-8040-65db3b1b9936)
现在去设备选择标签并确认：
![image](https://github.com/jetlinks/jetlinks-community/assets/89559616/21a528c1-8d9b-4f13-b09a-a8c0527283c5)
BUG 1： 标签值这里应该显示的是定义的text吧，不应该是value
![image](https://github.com/jetlinks/jetlinks-community/assets/89559616/b903152f-d295-4636-9a37-2acc48cc4cb5)
BUG 2：当我想更改我的标签时，显示的无数据
![image](https://github.com/jetlinks/jetlinks-community/assets/89559616/6c031ec1-3514-4077-9d4b-fb93f875ebc0)
经过查询后端和前端，发现后端返回的数据是这样子的。
![image](https://github.com/jetlinks/jetlinks-community/assets/89559616/1f201bee-6524-491f-b66f-ebc65ffc936a)

**Comment by bestfeng1020** [comment]
更新最新代码
