### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by 15610026157** [jetlinks/jetlinks-community#395]
在Ubuntu服务器上部署的jetlinks服务，在局域网下通过WiFi能正常登录进去，但是通过网线连接就登录不上，但是能获取到ip信息，后台jar包也是正常启动的，后端文件里都是用的127.0.0.1

**Comment by zhou-hao** [comment]
检查网络是否正常

**Comment by 15610026157** [comment]
网络是正常的 可以和局域网下其他设备ping通

**Comment by zhou-hao** [comment]
提供详细的信息，如错误信息等。

**Comment by 15610026157** [comment]
没有提示错误 后端jar包也是正常运行的 我换Wi-Fi连接局域网就能正常登录了 路由什么的也都查过 正常显示
