### ISSUE TITLE
BUG:日志查出不相干的IP信息。

### ISSUE THREAD

**Issue by PengyuDeng** [jetlinks/jetlinks-community#397]
多条件下请求数据，由于第一个terms的type永久为or（测试了N种组合，第一个trems都是or），引发出查询数据不正常。
![image](https://github.com/jetlinks/jetlinks-community/assets/89559616/ca68c4b6-62ec-4f04-ad03-614b5e908c4b)
当我用postman把第一个terms的type修改为and的时候，就变成正常的数据了。
![image](https://github.com/jetlinks/jetlinks-community/assets/89559616/d7b1e3cc-3a72-46cf-9938-7140396d49af)

**Comment by PengyuDeng** [comment]
经过测试，首个terms可以不传type，组合起来就是常规的where条件。可读性也高。
现在的前端多筛选条件用到这个组件，第一个terms写死为or。

**Comment by zhou-hao** [comment]
@bestfeng1020  问题复现 解决没

**Comment by zhou-hao** [comment]
@bestfeng1020

**Comment by zhou-hao** [comment]
https://github.com/jetlinks/jetlinks-community/pull/421
