### ISSUE TITLE
建立一个微信群来做技术交流嘛

### ISSUE THREAD

**Issue by redwolf2019** [jetlinks/jetlinks-community#40]

**Comment by Lind-pro** [comment]
QQ群2021514

**Comment by zhou-hao** [comment]
微信群人数限制太少了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: redwolf2019 <notifications@github.com&gt;
发送时间: 2021年3月5日 11:27
收件人: jetlinks/jetlinks-community <jetlinks-community@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[jetlinks/jetlinks-community] 建立一个微信群来做技术交流嘛 (#40)
