### ISSUE TITLE
协议管理中使用自定义的jar包可能会影响服务的正常使用

### ISSUE THREAD

**Issue by TanMengyuan** [jetlinks/jetlinks-community#41]
你好，我现在使用jetlinks的community版本的代码在自己的服务器上部署了一套。目前发现在添加协议管理的jar包时，如果在jar中使用了一些危险的方法，如死循环 while(true){} 或者 System.exit(1) 等类似的方法可以导致服务本身CPU打满或者服务进程被退出等情况，看了下代码似乎没有一个沙箱的环境以保证脚本或者jar的独立运行。不知道在专业版或企业版中是否有对该问题修复，或者是否有对该问题的修复的计划？

**Comment by zhou-hao** [comment]
这个自定义协议 并不是面向用户的，而是面向开发和运维人员的，如果要限制相应的类调用，可以自己实现一个`ProtocolSupportLoaderProvider`
