### ISSUE TITLE
[求助]jetlink里的告警规则，关掉再打开，无法收到mqtt消息。但是重启服务后是正常的

### ISSUE THREAD

**Issue by fx820** [jetlinks/jetlinks-community#411]
springBoot：2.6.6
hsweb: 4.0.16
jetlink的ruleEngine：1.2.1
复现步骤：基于jetlink二次开发，同时开启2个订阅相同topic的告警规则，stop一个，另一个也不能再正常收到消息；此外，再次启动已经是开启状态的规则，会导致同个订阅topic下的规则都没法正常工作。推测是调用ruleEngine的shutDown方法时出了问题，导致规则开启异常
![image](https://github.com/jetlinks/jetlinks-community/assets/28852158/a8684146-288a-4cd9-8d22-84c692cf6de4)

**Comment by zhou-hao** [comment]
jetlinks什么版本。 使用最新版本是否能复现此问题。提供具体的复现步骤，如系统操作截图，步骤等。

**Comment by fx820** [comment]
这个开关规则的bug是我代码写的有问题，现在改好了。
但是又发现一个新bug。。同一个设备下的不同告警规则，只要关了一个，就会导致其他的规则无法被触发。由于topic只含有产品id和设备id，是不是要加入规则id到topic里才能解决这个问题呢？
![image](https://github.com/jetlinks/jetlinks-community/assets/28852158/0a580f81-a3a1-487f-b267-74dd57bb9a60)

**Comment by bestfeng1020** [comment]
设备告警里面有对应的规则ID，你指的topic是啥

**Comment by fx820** [comment]
topic是告警设备对应emqx订阅的主题。$share/开头表示共享订阅，我在$share/后面加上规则id也无法区分，且重启告警规则后，规则失效。请问jetlink里是如何做的呢？

**Comment by fx820** [comment]
这个topic是我们定义的，和jetlink平台略有不同。
我看jetlink1.x版本的代码只看到产品id和设备id，目前没看懂jetlink的topic是怎么区分不同规则的
![image](https://github.com/jetlinks/jetlinks-community/assets/28852158/cbd6833e-751c-4154-9e2a-b33560fd2024)

**Comment by zhou-hao** [comment]
平台内部的topic和mqtt无关。
https://doc.v1.jetlinks.cn/best-practices/start.html#%E8%AE%BE%E5%A4%87%E6%B6%88%E6%81%AF%E5%AF%B9%E5%BA%94%E4%BA%8B%E4%BB%B6%E6%80%BB%E7%BA%BFtopic
