### ISSUE TITLE
网关类型是在项目启动的时候通过什么方式把网关类型放入providers的?

### ISSUE THREAD

**Issue by wangxueping520** [jetlinks/jetlinks-community#417]
![image](https://github.com/jetlinks/jetlinks-community/assets/41947857/2fd196d0-b707-4966-af1d-d688948c8e9b)

![image](https://github.com/jetlinks/jetlinks-community/assets/41947857/1ef1d5b4-0648-44e6-9e42-daea15cfc335)

**Comment by wangxueping520** [comment]
> 你的图不是已经解释了？

还是不太明天这个参数对象，是通过加载配置文件加进去的网关，还是怎么传进去的?
![image](https://github.com/jetlinks/jetlinks-community/assets/41947857/545162a1-e3f5-4b37-94ee-4608f34c4f1a)

**Comment by zhou-hao** [comment]
> > 你的图不是已经解释了？
> 
> 
> 
> 还是不太明天这个参数对象，是通过加载配置文件加进去的网关，还是怎么传进去的?
> 
> ![image](https://github.com/jetlinks/jetlinks-community/assets/41947857/545162a1-e3f5-4b37-94ee-4608f34c4f1a)
> 
> 

spring 提供的啊

**Comment by wangxueping520** [comment]
> > > 你的图不是已经解释了？
> > 
> > 
> > 还是不太明天这个参数对象，是通过加载配置文件加进去的网关，还是怎么传进去的?
> > ![image](https://user-images.githubusercontent.com/41947857/264279721-545162a1-e3f5-4b37-94ee-4608f34c4f1a.png)
> 
> spring 提供的啊

我想问的是jetlinks能自定义拓展网关吗？因为按照现有的模式代码，在gatewayProvides始终获取不到自定义的网关类型

**Comment by zhou-hao** [comment]
注入到spring

**Comment by wangxueping520** [comment]
> 注入到spring
搞了两种方式一种是直接复制现有的maven tcp模块，修改网关名，也获取不到。另一种是自己写的格式和其他网关模块是一样的，实现DeviceGatewayProvider接口，在类上添加@Component注解，好像也不行
![image](https://github.com/jetlinks/jetlinks-community/assets/41947857/8f1c0cd6-1777-4336-a8a1-5d8c225ae579)

**Comment by zhou-hao** [comment]
启动模块引入你自己创建的模块没

**Comment by wangxueping520** [comment]
没仔细看maven模块，我以为启动模块直接引入的network-component这个。解决了感谢jetlinks的官方指导，爱你们哟，比♥
