### ISSUE TITLE
登录逻辑在哪呢，没找到，包括下发token

### ISSUE THREAD

**Issue by xxll569** [jetlinks/jetlinks-community#437]

**Comment by bestfeng1020** [comment]
参考项目中Maven依赖相关代码
  <dependency>
            <groupId>org.hswebframework.web</groupId>
            <artifactId>hsweb-authorization-basic</artifactId>
            <version>${hsweb.framework.version}</version>
 </dependency>

**Comment by xxll569** [comment]
谢谢大佬
