### ISSUE TITLE
怎么可以不校验密码，只需校验账号就能登录呢

### ISSUE THREAD

**Issue by xxll569** [jetlinks/jetlinks-community#440]

**Comment by zhou-hao** [comment]
https://hanta.yuque.com/px7kg1/dev/gg5mynbel3ozfe2i#zZRTJ

**Comment by xxll569** [comment]
大佬如何监听这个类呢AuthorizationBeforeEvent

**Comment by zhou-hao** [comment]
> 大佬如何监听这个类呢AuthorizationBeforeEvent

spring event。参考平台其他地方使用。 https://hanta.yuque.com/px7kg1/dev/twut674rm9gv47mf

**Comment by xxll569** [comment]
@EventListener
    public void customLogin(AuthorizationBeforeEvent event){
        //用户名
        String userUame = event.getUsername();
        event.async(
            getUserIdByUserName(userUame)
                //设置当前已经认证了的用户信息
                .doOnNext(event::setAuthorized)
        );
    }

    public Mono<String> getUserIdByUserName(String username) {
        System.out.println("监控到登录啦！！！！！！！！！");
        userInfoService.createQuery()
            .where(UserInfo::getId, Objects.requireNonNull(username))
            .fetch();

        return ？？？？;
    }
            

这里这个返回类型怎么可以反回string呢

**Comment by xxll569** [comment]
public void customLogin(AuthorizationBeforeEvent event){
        //用户名
        String userUame = event.getUsername();
        event.async(
            getUserIdByUserName(userUame)
                //设置当前已经认证了的用户信息
                .doOnNext(event::setAuthorized)
        );
    }

    public Mono<String> getUserIdByUserName(String username) {
        System.out.println("监控到登录啦！！！！！！！！！");
        userInfoService.createQuery()
            .where(UserInfo::getId, Objects.requireNonNull(username))
            .fetch();

        return ？？？ ;
    }

这里怎么返回string呢

**Comment by zhou-hao** [comment]
```java
return  userInfoService
      .findById(Objects.requireNonNull(username))
      .map(UserEntity::getId);
```

**Comment by xxll569** [comment]
![image](https://github.com/jetlinks/jetlinks-community/assets/114725071/9a40c966-58b0-41b3-bf27-7a9018bcfdfa)

**Comment by zhou-hao** [comment]
只是举例，把UserEntity换成你实际实体类型

**Comment by xxll569** [comment]
看错了哈哈哈
