### ISSUE TITLE
[疑问]如何通过当前token获得此租户下的资产

### ISSUE THREAD

**Issue by kakascx** [jetlinks/jetlinks-community#445]
背景：
使用第三方平台的页面新建的clientId和secureKey，通过Oath接口生成了token，同时生成了一个同名的用户
将这个用户作为成员绑定到通过这个token创建的租户下，

目的：
想通过这个token，获得这个用户所在租户下持有的设备资产

代码片段：
![image](https://github.com/jetlinks/jetlinks-community/assets/15819504/1563e098-bd09-42a8-82b0-71656c84882d)

问题：
查询的设备结果是所有的设备，并不是绑定到这个租户下的，`AssetsHolder.injectConditional()`这个方法的使用是否正确，有没有合理的解决方案或者其他的方法可以实现这个场景

**Comment by zhou-hao** [comment]
通过token获取用户信息`/authorzie/me`接口,看一看 有没有对应的 dimension信息。

**Comment by kakascx** [comment]
> 通过token获取用户信息`/authorzie/me`接口,看一看 有没有对应的 dimension信息。

用生成的token调用了下`authorzie/me` ，dimension下包含生成的client和同名用户
![image](https://github.com/jetlinks/jetlinks-community/assets/15819504/70d8c80c-af83-4ecf-ba29-91a68e9fd0c1)

**Comment by zhou-hao** [comment]
看上去这个用户并没有和`租户`(2.x版本是角色)关联啊。角色也没有。

**Comment by kakascx** [comment]
> 看上去这个用户并没有和`租户`(2.x版本是角色)关联啊。角色也没有。

是不是需要和租户绑定后再生成token（但是这个租户是用生成的token创建的），或者绑定后刷新token

**Comment by zhou-hao** [comment]
token对应的用户需要和租户绑定

**Comment by kakascx** [comment]
> token对应的用户需要和租户绑定

已经绑定了，但是我是写了个接口，通过client生成的token来创建的租户，AssetsHolder.injectConditional()接口用的有问题吗

**Comment by zhou-hao** [comment]
数据权限是基于角色控制的。你需要设置对应的角色给你创建的用户。并且设置对应的功能权限
