### ISSUE TITLE
安装ES后启动项目时卡死在banner位置

### ISSUE THREAD

**Issue by xxll569** [jetlinks/jetlinks-community#450]
新装的ES测试连接时可以访问
项目启动时卡死在banner位置
日志也是debug

测试es：
![image](https://github.com/jetlinks/jetlinks-community/assets/114725071/d93f8922-52cb-4666-b2c4-3baae3d268e8)

**Comment by zhou-hao** [comment]
检查`spring.profiles.active`配置，加上dev再试试

**Comment by xxll569** [comment]
可以了！ 我刚扩展出来一个dev和一个prd文件 怎么样可以多个配置文件切换呢

**Comment by zhou-hao** [comment]
`dev,prod`呗。
