### ISSUE TITLE
分子 2.1 @Subscribe注解在SpringMessageBroker中为什么每个方法都重新生成一个静态代理？

### ISSUE THREAD

**Issue by cqzaiercn** [jetlinks/jetlinks-community#456]
SpringMessageBroker类中
// 代理方法: 当前bean实例和方法
ProxyMessageListener listener = new ProxyMessageListener(bean, method);

`/**
静态代理后的方法  
public Object apply(Object target,Object param){
		org.jetlinks.community.rule.engine.alarm.DefaultAlarmRuleHandler _target = 			(org.jetlinks.community.rule.engine.alarm.DefaultAlarmRuleHandler)target;
			org.jetlinks.community.rule.engine.entity.AlarmConfigEntity _param = 			(org.jetlinks.community.rule.engine.entity.AlarmConfigEntity)param;
return  _target.removeAlarmConfig(_param);	
}
**/
this.proxy = Proxy.create(BiFunction.class)
    .addMethod(code.toString())
    .newInstance();

// onMessage方法
Object val = proxy.apply(target, paramVoid ? null : convert(message));

`

**Comment by cqzaiercn** [comment]
为什么不直接反射调用？ ReflectUtil.invoke(target,meaasge);

**Comment by zhou-hao** [comment]
反射性能低
