### ISSUE TITLE
[疑问]设备导入物模型时物模型类型问题

### ISSUE THREAD

**Issue by kakascx** [jetlinks/jetlinks-community#457]
调用/metadata/codecs接口返回结果为空

![0c7b2e96096d6f6e3ccbd93d1dad766](https://github.com/jetlinks/jetlinks-community/assets/15819504/c6b7f661-602d-48c0-b50b-f05629ca782b)

![183440cd97bebd9602b4a194100a496](https://github.com/jetlinks/jetlinks-community/assets/15819504/ae270a94-3a70-450c-bed0-4fdd91d2c2d5)

看前端代码物模型下拉列表的值是写死的，/metadata/codecs接口目前没有作用？

**Comment by liu4410** [comment]
> 调用/metadata/codecs接口返回结果为空
> 
> ![0c7b2e96096d6f6e3ccbd93d1dad766](https://private-user-images.githubusercontent.com/15819504/290431402-c6b7f661-602d-48c0-b50b-f05629ca782b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjM0MTUsIm5iZiI6MTcwMzEyMzExNSwicGF0aCI6Ii8xNTgxOTUwNC8yOTA0MzE0MDItYzZiN2Y2NjEtNjAyZC00OGMwLWI1MGItZjA1NjI5Y2E3ODJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAxNDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZWU0NDJmOTYyMzA5ZThlYTg2ZWM3NThhZjI1NzhlNjQ4MTM1NGQ4ODcwMmRhNjMzYjIxZWEyZTQ2ZDdhOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PlpbCbqzkz7BTgt7H-vOwmGemhCRyH3qp4b8CVGMhsY)
> 
> ![183440cd97bebd9602b4a194100a496](https://private-user-images.githubusercontent.com/15819504/290431470-ae270a94-3a70-450c-bed0-4fdd91d2c2d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjM0MTUsIm5iZiI6MTcwMzEyMzExNSwicGF0aCI6Ii8xNTgxOTUwNC8yOTA0MzE0NzAtYWUyNzBhOTQtM2E3MC00NTBjLWJlZDAtNGZkZDkxZDJjMmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAxNDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YWEzMWRkYzAzNTYyNDkyYThjNTZiZjM0MWYzNWI4NDlmZDM3MGRiN2M0OTczNGIxNjdiYjNlNWIzZGE3MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h4kpy6cwBQ0ogLhLdYEE6P8IsT78I9Ri98JyccmFMlo)
> 
> 看前端代码物模型下拉列表的值是写死的，/metadata/codecs接口目前没有作用？

社区版没有对应模块，/metadata/codecs 接口返回空，逻辑为存在默认物模型类型，拓展从接口获取，社区版前端已优化
