### ISSUE TITLE
TAOS设备管理-运行状态-设备详情数据展示不完整

### ISSUE THREAD

**Issue by Rosning** [jetlinks/jetlinks-community#461]
![1703299192138](https://github.com/jetlinks/jetlinks-community/assets/23734062/7cd8fa26-53b7-4b2d-ad47-d885f2b10d13)
使用TDengine-行存储数据时，发现设备详情图标展示不能展示完毕。只能展示一分钟的数据

**Comment by zhou-hao** [comment]
更新最新代码。
