### ISSUE TITLE
TCP数据报文接收问题

### ISSUE THREAD

**Issue by Wpeng-Stronger** [jetlinks/jetlinks-community#462]
![536d78bb3eeaa49dd599c562c3f0254](https://github.com/jetlinks/jetlinks-community/assets/73539392/bfc4f41e-a6f6-4f32-ad84-732ce2bc7f94)
![image](https://github.com/jetlinks/jetlinks-community/assets/73539392/4e383612-99b5-4ea8-99c8-3b36e9451d0e)

问题：设备的一条数据报，通过工具接收没有问题，平台接收一条数据报分两条接收。根据厂商反馈是netty的缓冲区大小的问题。有人知道怎么解决吗

**Comment by zhou-hao** [comment]
在网络组件中配置 对应的粘拆包规则
