### ISSUE TITLE
在一对多时，动态查询条件怎样可以对从表生效

### ISSUE THREAD

**Issue by xxll569** [jetlinks/jetlinks-community#469]

**Comment by zhou-hao** [comment]
怎么查询的

**Comment by xxll569** [comment]
![image](https://github.com/jetlinks/jetlinks-community/assets/114725071/ab1e88b8-60b9-452a-bc50-4d158f9d9d98)
准备使用这个方式

**Comment by zhou-hao** [comment]
在leftJoin里增加条件试试。

**Comment by xxll569** [comment]
spec.is(ExtendedEntity::getExampleId, ExampleEntity::getId)这个里面吗

**Comment by zhou-hao** [comment]
嗯。

**Comment by xxll569** [comment]
这样的话是不是就写死了 我想动态查询

**Comment by zhou-hao** [comment]
动态添加条件呗。  `spec.accept(term)` ;

**Comment by zhou-hao** [comment]
或者使用 `QueryHelper#combineOneToMany`方法

**Comment by xxll569** [comment]
![image](https://github.com/jetlinks/jetlinks-community/assets/114725071/3947a71b-a720-4f4f-9a50-ef32b0b463b2)
文档中那个ExampleInfo不是主表吗

**Comment by xxll569** [comment]
我是想标签和设备进行关联

**Comment by zhou-hao** [comment]
根据标签查询设备？ 见 `DeviceTagTerm`

**Comment by xxll569** [comment]
不是，我是想查询设备列表然后标签也要展示出来
![image](https://github.com/jetlinks/jetlinks-community/assets/114725071/2ad20bf9-cc1e-481b-8dc1-2187d78b77d2)
这样写了一个也可以

**Comment by zhou-hao** [comment]
不是有现成的接口？

**Comment by xxll569** [comment]
嗯 现成的是查看详情的我是想 查某个产品的所有设备

**Comment by xxll569** [comment]
还有个问题就是前端的查询框适合表格进行了绑定吗  怎么样可以单独的使用查询框呢

**Comment by zhou-hao** [comment]
什么叫单独使用查询框？

**Comment by xxll569** [comment]
额 没啥 那个关联应该怎么写呢

**Comment by zhou-hao** [comment]
啥关联
