### ISSUE TITLE
设备属性数据存储位置是哪里

### ISSUE THREAD

**Issue by xxll569** [jetlinks/jetlinks-community#473]
是ES?
还是数据库

**Comment by zhou-hao** [comment]
默认es

**Comment by xxll569** [comment]
存储策略可以配置修改吗 还是需要编码

**Comment by zhou-hao** [comment]
社区版还支持 tdengine。或者编码实现拓展，

**Comment by xxll569** [comment]
在设备数据在es中保存多久呢

**Comment by xxll569** [comment]
![image](https://github.com/jetlinks/jetlinks-community/assets/114725071/0f727526-9962-4c32-bc80-a5e4fca2ba28)
设备属性数据在哪个库中呢

**Comment by zhou-hao** [comment]
properties_..... 

https://hanta.yuque.com/px7kg1/yfac2l/rz0160n1s3y4enk6
