### ISSUE TITLE
属性为数组类型的场景联动触发异常

### ISSUE THREAD

**Issue by liunanhao** [jetlinks/jetlinks-community#474]
## 描述
当属性为数组类型时，尝试在场景联动中设置触发条件为不包含或全部包含在时，场景联动判断异常。
![1707036189838](https://github.com/jetlinks/jetlinks-community/assets/41946722/bd700e60-dd5b-4d18-9b97-456d4cab78c7)

```
物模型只有一个温度数组属性
{
  "properties": [
    {
      "id": "temps",
      "name": "分布式温度",
      "expands": {
        "source": "device",
        "type": [
          "report"
        ]
      },
      "valueType": {
        "elementType": {
          "type": "float",
          "scale": 2
        },
        "type": "array"
      }
    }
  ]
}
```
## 异常结果
设置条件为不包含（20，60）时，以下输入结果仍旧触发
```
{
	"deviceId": "1754018387737407488",
	"properties": {
		"temps": [23.2,33.4]
	}
}
```
触发结果如下
![1707036512006](https://github.com/jetlinks/jetlinks-community/assets/41946722/0b0a66f5-2ee4-4cab-859a-85bc3b296eef)

## 疑问
请问是代码出现了问题，还是本人物模型或者场景联动设置错误，抑或是数据上报的json结构有误，望解答，谢谢

**Comment by bestfeng1020** [comment]
23.2,33.4确实不包含在20  60数字之中。应该触发结果

**Comment by liunanhao** [comment]
> 23.2,33.4确实不包含在20 60数字之中。应该触发结果

不好意思，我没理解这个回答，我提的这个问题不是一个问题，是我对”23.2,33.4确实不包含在20 60数字之中“这句话理解错了？

**Comment by liunanhao** [comment]
> 23.2,33.4确实不包含在20 60数字之中。应该触发结果

不好意思，我没理解这个回答？是您已经确认了有问题需要修正？还是说我提的这个问题是我自己理解错了，没有需要修正代码的地方？

**Comment by liunanhao** [comment]
> 23.2,33.4确实不包含在20 60数字之中。应该触发结果

不好意思，我没理解这个回答？是您已经确认了有问题需要修正？还是说我提的这个问题是我自己理解错了，没有需要修正代码的地方？

**Comment by bestfeng1020** [comment]
你上报的数据，确实不在设置的数据中，所以代码逻辑没问题。没有需要修正的代码

**Comment by liunanhao** [comment]
我理解的数字是23.2比20大，比60小，在区间[20,60]范围内，"20 <  23.2 < 60",

不知道您程序是按照那样的逻辑进行判断的呢

**Comment by bestfeng1020** [comment]
他是数组，不是区间。不存在范围的概念

**Comment by bestfeng1020** [comment]
这个界面我们后续版本会优化
