### ISSUE TITLE
jar 包依赖问题

### ISSUE THREAD

**Issue by MoonBottle** [jetlinks/jetlinks-community#479]
jetlinks 1.2.0 的 jar 包依赖的 `hsweb.framework.version` 是 `4.0.15-SNAPSHOT` 版本，似乎仓库里这个快照版本已经被删了，导致无法下载

![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/39720311-9ab3-4993-a5ee-a2a165e0f831)

![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/e712de76-d925-4170-afe9-97187b4879d7)

**Comment by zhou-hao** [comment]
修改仓库域名为 `nexus.jetlinks.cn`

**Comment by zhou-hao** [comment]
或者使用`1.2.2-SNAPSHOT`

**Comment by MoonBottle** [comment]
试了下，改成 `nexus.jetlinks.cn` 还是不行，不知道是不是因为下载的 1.2.0 的 pom 文件里的仓库域名还是旧的
![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/3704f7cf-dae0-41fe-86ee-28fe6827a6cf)

然后想问下 `1.2.2-SNAPSHOT` 升级了啥内容，完全兼容 1.2.0 么？

**Comment by zhou-hao** [comment]
理论上兼容

**Comment by MoonBottle** [comment]
> 理论上兼容

多谢，我升级 1.2.2-SNAPSHOT 可以了
