### ISSUE TITLE
hsweb 支持 IS DISTINCT FROM 吗？

### ISSUE THREAD

**Issue by MoonBottle** [jetlinks/jetlinks-community#481]
数据库是 pgsql， 有 null 值，使用 neq 无法查询到是转换成 != 无法查询到，是不是要自定义 Term

**Comment by zhou-hao** [comment]
termType用isnull。 value随便填。

**Comment by MoonBottle** [comment]
条件是这样的 isnull 似乎搞不定？
```json
{
  "column": "firmwareId",
  "value": "1772093289253195776",
  "termType": "neq"
}
```

**Comment by zhou-hao** [comment]
用2个组合条件试试?   firmwareId neq 1772093289253195776 or firmwareId isnull true

**Comment by MoonBottle** [comment]
> 用2个组合条件试试? firmwareId neq 1772093289253195776 or firmwareId isnull true

这样可以，多谢大佬
