### ISSUE TITLE
规则编排

### ISSUE THREAD

**Issue by liuzhihao-but** [jetlinks/jetlinks-community#483]
方便说一下项目中的规则编排中的规则设计器是怎么实现的吗

**Comment by zhou-hao** [comment]
前端 node-red

**Comment by liuzhihao-but** [comment]
node-red不是依赖于本地启动然后使用的吗那是怎么把他跟项目结合在一起的

**Comment by zhou-hao** [comment]
只使用node-red的前端部分呗。

**Comment by liuzhihao-but** [comment]
node-red的git项目里不是就只有js吗

**Comment by zhou-hao** [comment]
也有前端哦

**Comment by liuzhihao-but** [comment]
能发个网址吗

**Comment by zhou-hao** [comment]
https://github.com/node-red/node-red/tree/master/packages/node_modules/node-red

**Comment by liuzhihao-but** [comment]
能指点一下在那个文件夹吗我翻了翻就只有js有的html只有引入各种js呀

**Comment by zhou-hao** [comment]
发错了 是这个 https://github.com/node-red/node-red/tree/master/packages/node_modules/%40node-red/editor-client
