### ISSUE TITLE
场景联动下执行动作通过标签选择设备类型为非string报错

### ISSUE THREAD

**Issue by wuzhaozhongguo** [jetlinks/jetlinks-community#489]
**版本:**
docker安装的jetlinks-standalone:2.1.0-SNAPSHOT
**场景：**
场景联动下执行动作，通过标签选择设备，类型为非string报错
**症状：**
我发现两种情况
1.如果我设备类型为非string,这里是int,则会报错,SQL是d.KEY = NULL AND d.VALUE LIKE 1，错误是operator does not exist: character varying ~~ integer
2.如果我是string，则不报错，但是不执行。我怀疑sql也是d.KEY = NULL，匹配不到但是没报错
**贴图：**
![image](https://github.com/jetlinks/jetlinks-community/assets/7008778/a93a25c9-d06b-4cc8-b73b-02defc5eb451)

![image](https://github.com/jetlinks/jetlinks-community/assets/7008778/c384fcc4-99f7-4394-87fb-1f873a479d98)

**Comment by wuzhaozhongguo** [comment]
![8626048bbc16933a4468cd62d57411c](https://github.com/jetlinks/jetlinks-community/assets/7008778/daf87f65-fe15-42dd-81c0-5bbbbff635e7)
应该是这个问题吧，能不能更新个版本呢。docker里面的

**Comment by zhou-hao** [comment]
使用master分支。 docker使用 2.2.0-SNAPSHOT

**Comment by wuzhaozhongguo** [comment]
> 使用master分支。 docker使用 2.2.0-SNAPSHOT

其他的组件不用改版本吗

**Comment by zhou-hao** [comment]
前后端一致

**Comment by wuzhaozhongguo** [comment]
> 前后端一致

上面的代码截图bug依然存在，tag中的字段是column,这里去获取key,是空的

**Comment by zhou-hao** [comment]
再更新试试

**Comment by wuzhaozhongguo** [comment]
可以了，用最新版的2.2.0.镜像要换registry.cn-shenzhen.aliyuncs.com/jetlinks/jetlinks-community:2.2.0-SNAPSHOT
