### ISSUE TITLE
相同字段塞了两遍导致 sql 异常

### ISSUE THREAD

**Issue by MoonBottle** [jetlinks/jetlinks-community#494]
![image](https://github.com/hs-web/hsweb-easy-orm/assets/12904505/3fe7b0ad-b791-4be1-aeb2-c93c45cd1f51)
![image](https://github.com/hs-web/hsweb-easy-orm/assets/12904505/e12a3ac1-3178-464c-9750-ffa64f66fa3a)

关联提交记录 https://github.com/hs-web/hsweb-easy-orm/commit/b9af42a75203063f42efa7333d0cd54e8fe0e2fa

**Comment by MoonBottle** [comment]
似乎还会把 set 的值覆盖掉
![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/7eb0a229-07b2-4073-835d-57b7da39b69c)

**Comment by zhou-hao** [comment]
刷新一下maven再试试

**Comment by MoonBottle** [comment]
测试了下是可以的，不过有个小问题，就是 `operator` 里的值会被短暂的覆盖

entry 遍历的时候，因为 key 有 modifyTime 和 modify_time（update 的时候代码里塞的）

图中是运行到 modifyTime 的 key
![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/0c0dae4e-064f-4185-9a6c-460a07c5e42e)

运行之后，modify_time 的 value 变成了 modifyTime 的值

**Comment by zhou-hao** [comment]
` operator.set(column, tempInstance.getOrDefault(entry.getKey(), entry.getValue()));` 无法实现真实的覆盖修改。

更新hsweb的依赖再试试？

**Comment by MoonBottle** [comment]
![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/5d466d56-52a0-4a12-8289-8e3aa1b4720b)
刷新了，好像没啥变化？我的 jar 是最新的么

这次 modify_time 先被遍历，modifyTime 的值覆盖了
![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/123bd47c-99d7-4755-8d82-09c1233b833e)

**Comment by zhou-hao** [comment]
`hsweb-commons-crud`

**Comment by MoonBottle** [comment]
> `hsweb-commons-crud`

![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/7b17a320-e007-4525-b383-24a98daf6fd4)
4.0.16 要改成 4.0.17-SNAPSHOT 吗

**Comment by zhou-hao** [comment]
嗯

**Comment by zhou-hao** [comment]
只能这样曲线救国了 😂
