### ISSUE TITLE
网络流量统计是读取的物联卡还是自己计算上报数据来的

### ISSUE THREAD

**Issue by jyy1990** [jetlinks/jetlinks-community#496]
![image](https://github.com/jetlinks/jetlinks-community/assets/35125132/5c08408c-4fce-4f87-b12a-f1dac9daa58a)
社区版屏蔽了这个功能，我猜测它是读取的物联卡流量数据？因为社区版没有物联卡管理。

如果它是自己计算上报数据大小，那这个计算的逻辑社区版有没有保留呢？

**Comment by zhou-hao** [comment]
这个是平台内部网络组件的监控流量。
