### ISSUE TITLE
找不到协议jar包

### ISSUE THREAD

**Issue by Git4Mark** [jetlinks/jetlinks-community#50]
windows启动和k8s启动
设备接入-》协议管理-》创建协议
找不到协议jar包 目录 `/home/pi` 下没有协议jar包（服务器上不存在 `/home/pi`目录）

**Comment by zhou-hao** [comment]
请确定上传后的协议文件能否访问

**Comment by Git4Mark** [comment]
@zhou-hao 文档中提到协议包在`/home/pi`下面，但是我并没有这个目录，所以我现在无法完成创建协议

**Comment by Git4Mark** [comment]
@zhou-hao 请问在哪里可以获取到协议包和模型文件

**Comment by Git4Mark** [comment]
@zhou-hao http://doc.jetlinks.cn/basics-guide/DemoDevice.html#%E5%88%9B%E5%BB%BA%E5%8D%8F%E8%AE%AE
文档上说这两个文件在`/home/pi`下

**Comment by zhou-hao** [comment]
![image](https://user-images.githubusercontent.com/7791838/115213995-ac899080-a134-11eb-9e53-594f95d61774.png)

**Comment by Git4Mark** [comment]
@zhou-hao 那请问编译后的jar包能提供吗

**Comment by zhou-hao** [comment]
加群联系商务
