### ISSUE TITLE
EntityPrepareModifyEvent 修改字段后 update 未生效

### ISSUE THREAD

**Issue by MoonBottle** [jetlinks/jetlinks-community#505]
![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/1f3cee2d-48dd-4fca-930f-312bc23978b4)

监听了 `EntityPrepareModifyEvent` 事件，修改了某个字段
![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/f1bbd47d-57b4-4888-83db-c846c229ff1a)

最终执行的 sql 还是原先的字段，请问下这个事件不能修改字段值么
![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/80665d0b-2a9c-4fed-acf7-6d2495c56531)

![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/3a3781fb-ad61-4c5a-855f-db9984a789fe)

**Comment by zhou-hao** [comment]
好像 修复过。是最新的hsweb-framework和 easyorm版本吗？ 

debug看看这里

https://github.com/hs-web/hsweb-framework/blob/c3643ecfcafa778b065e26857b4e6b0c708d7c0c/hsweb-commons/hsweb-commons-crud/src/main/java/org/hswebframework/web/crud/events/EntityEventListener.java#L225-L232

**Comment by MoonBottle** [comment]
hsweb-framework 版本：4.0.17-SNAPSHOT
easy-ormb 版本：4.1.2-SNAPSHOT
![版本信息](https://github.com/jetlinks/jetlinks-community/assets/12904505/c295da80-5693-4860-8430-3e9a8523878a)

步骤：
1、update 前设置了 -1
![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/4176cecc-ea01-4ff3-b3ea-786f738149a2)
2、EntityPrepareModifyEvent 事件中给更新前后的事体分别设置成了-2 和 -3
![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/8e9ff556-4e61-49b4-9845-37a1c298c207)
3、debug 看 entry.setValue 是塞成功了，取到了 -3
![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/f0b86558-8767-433a-870d-1c237baf5044)
4、最终执行的 sql 是 -1
![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/ce62b5fd-ba18-46d7-b301-975762211348)

**Comment by zhou-hao** [comment]
在这个单元测试 复现看看

https://github.com/hs-web/hsweb-framework/blob/1ba900746587f17c6a512ed04733c0c1f7c33305/hsweb-commons/hsweb-commons-crud/src/test/java/org/hswebframework/web/crud/events/EntityEventListenerTest.java#L87-L105

**Comment by MoonBottle** [comment]
在这个代码仓库中复现了：https://github.com/MoonBottle/hsweb-framework
1、update 前赋值
2、监听事件并修改变量值
3、最终执行的 sql
![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/e3328147-924d-40ff-aeca-fe5b37710cf9)

**Comment by zhou-hao** [comment]
试试这个PR https://github.com/hs-web/hsweb-framework/pull/288

**Comment by MoonBottle** [comment]
> 试试这个PR [hs-web/hsweb-framework#288](https://github.com/hs-web/hsweb-framework/pull/288)

测试了下，修改的值是预期的 -3，大佬👍
![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/59826386-f518-4565-9e63-cfd5e7df3a8e)

**Comment by zhou-hao** [comment]
字段类型是包装器类型还是基本数据类型

**Comment by zhou-hao** [comment]
再试试

**Comment by zhou-hao** [comment]
不过目前不能通过EntityPrepareModifyEvent设置null值

**Comment by MoonBottle** [comment]
> 不过目前不能通过EntityPrepareModifyEvent设置null值

抱歉，我有点没说清楚，现在这个现象和 `EntityPrepareModifyEvent` 没有关系了，是一个单独的问题

刚才又试了下，setNull 似乎不生效了，最终执行的 sql 中没有 set null 的语句

已确认刷新过 maven 

![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/4b7f3396-3363-4054-ba1d-b6cc265b95d9)

**Comment by zhou-hao** [comment]
<img width="854" alt="image" src="https://github.com/jetlinks/jetlinks-community/assets/7791838/78d22707-5561-4dc0-85c8-27c95b5418f2">
<img width="701" alt="image" src="https://github.com/jetlinks/jetlinks-community/assets/7791838/63080e23-9e0b-402a-9d80-6a1106e8b9b5">

**Comment by MoonBottle** [comment]
奇怪，我本地确实不行，maven 也刷新了

![image](https://github.com/jetlinks/jetlinks-community/assets/12904505/8914bf16-ff99-4512-acc7-9cc610d49470)


测试代码地址：https://github.com/MoonBottle/hsweb-framework/blob/358e783a7ffc4ec51848afa3cb1e4d3eb9bcc14f/hsweb-commons/hsweb-commons-crud/src/test/java/org/hswebframework/web/crud/events/EntityEventListenerTest.java#L88

**Comment by zhou-hao** [comment]
代码 没同步完？  https://github.com/hs-web/hsweb-framework/pull/288/commits/74d7421e53401b3df7db439a9bb67b39f3335648

**Comment by MoonBottle** [comment]
> 代码 没同步完？ [hs-web/hsweb-framework@74d7421](https://github.com/hs-web/hsweb-framework/commit/74d7421e53401b3df7db439a9bb67b39f3335648)

抱歉抱歉，我没注意到 PR 有新的 commit，代码没同步完

同步后测试成功了，大佬🐂🍺，非常感谢！🙏

**Comment by zhou-hao** [comment]
好的。没有问题我就合并了。
