### ISSUE TITLE
平台的消息总线/消息网关能否使用除Redis外的其他中间件？

### ISSUE THREAD

**Issue by MR-Yang07** [jetlinks/jetlinks-community#506]
如题所示，目前平台的消息总线/消息网关里的发布订阅功能有使用的是Redis的RedisClusterManager.getQueue()等相关的方法。
请问平台是否支持其他中间件完成订阅发布功能?比如RabbitMQ、Kafka等。
如果支持，应该怎么接入这些中间件呢？
如果不支持，那我该怎么办才能成功替换Redis的发布订阅功能呢？
![a3473b2acae3efd36da021ff8d5310c](https://github.com/jetlinks/jetlinks-community/assets/30631026/78871e94-212a-49d2-834b-3a1e272a0859)

**Comment by zhou-hao** [comment]
这个应该是已经弃用了的。  参考: https://github.com/jetlinks/jetlinks/issues/9

**Comment by MR-Yang07** [comment]
已看完参考内容，受益匪浅!
请问是在哪一个版本彻底废弃redis_list？

**Comment by zhou-hao** [comment]
`1.20` 之后

**Comment by MR-Yang07** [comment]
感谢回答！ヾ(o′▽`o)ノ°° .°谢谢ｰ° .°
