### ISSUE TITLE
自定义协议包是如何加载，使用的。

### ISSUE THREAD

**Issue by zhaochong-byte** [jetlinks/jetlinks-community#51]
请问，我自定义协议并发布协议之后，jetlinks是如何找到自定义协议中的认证器和编解码的？

**Comment by zhou-hao** [comment]
反射

**Comment by zhaochong-byte** [comment]
嗯嗯，刚刚看了下源码，基本看懂了。感谢大佬的回复

**Comment by zhaochong-byte** [comment]
问题暂不关闭，如果还有不懂 的  再请教大佬

**Comment by zhaochong-byte** [comment]
![image](https://user-images.githubusercontent.com/73687296/115359228-0fd8f880-a1f1-11eb-8e09-b3b42a22b449.png)

您好，周老板，关于CompositeProtocolSupport这个类中的属性，有相关文档参考吗？

**Comment by zhou-hao** [comment]
看ProtocolSupport这个接口，IDEA右上角 Download Sources

**Comment by zhaochong-byte** [comment]
OK

**Comment by zhaochong-byte** [comment]
您好，周老板，十分抱歉又来请教你，以MQTT为例，请问代码是在哪一步调用协议包中的编解码方法的呀？

**Comment by zhou-hao** [comment]
https://github.com/jetlinks/jetlinks-community/blob/master/jetlinks-components/network-component/mqtt-component/src/main/java/org/jetlinks/community/network/mqtt/gateway/device/MqttServerDeviceGateway.java

**Comment by zhaochong-byte** [comment]
抱歉，您刚发的类名，我都找到了，只是不明白他们之间的逻辑调用关系，因为我在这之前从未用过响应式编程。

**Comment by zhou-hao** [comment]
这就说来话长了，建议先看一下 https://projectreactor.io/docs/core/3.3.12.RELEASE/reference/

**Comment by zhaochong-byte** [comment]
我想请问下，我通过web页面发送设备指令，是如何调用协议包中的encode方法的，，这次我连在哪调用都没找到- -

**Comment by zhou-hao** [comment]
DeviceMessageSender

**Comment by zhaochong-byte** [comment]
在send方法及其实现吗？
