### ISSUE TITLE
设备管理-设备-日志管理部分内容乱码？

### ISSUE THREAD

**Issue by becage** [jetlinks/jetlinks-community#515]
<img width="1244" alt="image" src="https://github.com/jetlinks/jetlinks-community/assets/41765271/0acc6a53-27c2-40f4-a06c-4e2b64467f3c">
使用 `TDEngine-列式存储`

  tdengine:
    image: tdengine/tdengine

redis:
    image: redis

mysql:
    image: mysql:5.7.18

elasticsearch:
    image: elasticsearch:7.17.21

ui:
    image: registry.cn-shenzhen.aliyuncs.com/jetlinks/jetlinks-ui-vue:2.1.0-SNAPSHOT

<img width="890" alt="image" src="https://github.com/jetlinks/jetlinks-community/assets/41765271/bdab9b68-f7aa-4d23-b7f3-d46555e4ae9b">

**Comment by becage** [comment]
taos存储的数据就是乱码的，但是看配置默认是utf8,
MQTTX软件的问题吗，哪里可以设置
<img width="520" alt="image" src="https://github.com/jetlinks/jetlinks-community/assets/41765271/1812b199-6db9-42b0-b046-72d8112ecf6b">
<img width="668" alt="image" src="https://github.com/jetlinks/jetlinks-community/assets/41765271/7448a939-86d9-4aa8-bfd3-a030078cd097">

**Comment by bestfeng1020** [comment]
-Dfile.encoding=utf-8   指定下java运行时字符集试下

**Comment by becage** [comment]
> -Dfile.encoding=utf-8 指定下java运行时字符集试下
我对jetlinks后端代码做了修改后，在Dockerfile增加了字符集，重新打镜像，然后docker-compose up 运行还是乱码 
ENTRYPOINT ["java", "-Dfile.encoding=utf-8", "-jar", "jetlinks.jar"]

**Comment by becage** [comment]
```   
tdengine:
    image: tdengine/tdengine:3.0.1.8
 ```
原来是latest镜像，换成低版本不乱码了，是tdengin版本的问题

<img width="1041" alt="image" src="https://github.com/jetlinks/jetlinks-community/assets/41765271/30a9ab6e-23e9-4294-ab77-04e60f5388df">
