### ISSUE TITLE
国产数据库支持

### ISSUE THREAD

**Issue by wangguanfei** [jetlinks/jetlinks-community#518]
看文档写的支持达梦数据V8，但是代码里并没有引入相关驱动。单独引入驱动后，项目启动各种语法报错。是社区版不支持国产化吗？
![image](https://github.com/jetlinks/jetlinks-community/assets/8002945/03152ec9-111c-4bee-94ff-238fae781015)
dm-r2dbc只有达梦官方提供的版本，并且必须使用jdk11
![image](https://github.com/jetlinks/jetlinks-community/assets/8002945/40bd19be-91b3-4797-8cee-27498d3e0406)
![image](https://github.com/jetlinks/jetlinks-community/assets/8002945/8815e1ce-6a68-4f81-9a66-9012a4a05ba7)

**Comment by zhou-hao** [comment]
1. dm官方只提供java11的驱动支持，使用java11，设置方言为oracle。
2. 企业版有单独适配dm。
