### ISSUE TITLE
设备事件无法查看记录

### ISSUE THREAD

**Issue by Xuyilinya** [jetlinks/jetlinks-community#52]
步骤：在设备物模型下添加事件 ==》设备上报事件 ==》事件记录查询为空
上报后事件次数会加一，刷新后会为零，记录显示为空，可以确定ElasticSearch中有该事件记录。

**Comment by zhou-hao** [comment]
设备是否更改过产品。 是不是物模型还没有应用配置，就上报了数据。

**Comment by Xuyilinya** [comment]
是不是只有在产品那边新增物模型才有效呢，经过测试我发现，查不到事件的数据是因为我直接在设备那边添加的，然后还有一个问题就是在产品那边新增物模型之后，已有的设备那边是看不到新增的物模型，新添加的设备会有。

**Comment by zhou-hao** [comment]
目前需要在产品里添加事件。 设备里到物模型通常只是修改拓展配置信息，不建议进行添加，不过这个也和具体到存储策略有关。

**Comment by Xuyilinya** [comment]
好的，多谢回复，那产品里面添加新的物模型属性后，已存在的设备不会继承过来，每次都要重新再添加一次设备信息才能生效，这个是因为开源版的问题么。

**Comment by zhou-hao** [comment]
目前是这样设计的，可以点击设备物模型里的重置，恢复为产品的物模型。

**Comment by Xuyilinya** [comment]
好的，多谢指点
