### ISSUE TITLE
断开Http设备的连接，报超时错误，算是bug吗

### ISSUE THREAD

**Issue by jyy1990** [jetlinks/jetlinks-community#521]
这个接口：api/device-instance/1777885051477221376/disconnect

报超时我认为也是正常的，毕竟http设备根本就没有连接一说， 但是从产品角度看，这个问题不处理一下吗。或者说我有没有办法操作让它可以不报错
![image](https://github.com/jetlinks/jetlinks-community/assets/35125132/c36e0839-ee64-4c1b-8210-50b6578a880b)

**Comment by zhou-hao** [comment]
官方协议？

**Comment by jyy1990** [comment]
> 官方协议？

是啊，其他协议可以断，就这个报错

**Comment by jyy1990** [comment]
我现在的处理办法是HTTP设备的断连接口重新写一个，和其他断连接口区分开，然后在后端通过http调用
/{productId:产品ID}/{deviceId:设备ID}/offline，相当于直接从设备发起断连请求，这样倒是可以解决问题。

**Comment by zhou-hao** [comment]
需要调整一些协议包处理。 https://github.com/jetlinks/jetlinks-official-protocol/blob/37378a6a4935aa73e5aa4a337e552d575bd617e0/src/main/java/org/jetlinks/protocol/official/http/JetLinksHttpDeviceMessageCodec.java#L65-L68
