### ISSUE TITLE
IDEA运行失败的

### ISSUE THREAD

**Issue by LordHumphrey** [jetlinks/jetlinks-community#523]
1. 使用java8，提示如下
![image](https://github.com/jetlinks/jetlinks-community/assets/43847411/df3dcd6d-8049-4c21-a63a-e68405e3e1df)
2. 使用java11，无论是否启用maven 里面的java 11 profile都提示如下：
运行参数已经添加`--add-exports java.base/com.sun.nio.file=ALL-UNNAMED`
![image](https://github.com/jetlinks/jetlinks-community/assets/43847411/f740c4e6-db31-40d1-a807-86b4d508ab0c)

谢谢您的回复，折腾了很久也解决不了😂

**Comment by zhou-hao** [comment]
百度搜索： idea command line is too long
