### ISSUE TITLE
queryHelper leftJoin 失效

### ISSUE THREAD

**Issue by MoonBottle** [jetlinks/jetlinks-community#529]
return queryHelper
            .select(PigstyAlarmRecordDTO.class)
            .all(PigstyEntity.class, PigstyAlarmRecordDTO::setPigstyInfo)
            .all(AlarmRecordEntity.class)
            .from(AlarmRecordEntity.class)
            .leftJoin(PigstyEntity.class, join -> join.is(PigstyEntity::getDeviceId, AlarmRecordEntity::getTargetId))
            .where(query)
            .fetchPaged()
            
最终执行sql：`
 select alarm_record."id" as "all_1.id" , alarm_record."alarm_config_id" as "all_1.alarmConfigId" , alarm_record."alarm_name" as "all_1.alarmName" , alarm_record."target_type" as "all_1.targetType" , alarm_record."target_id" as "all_1.targetId" , alarm_record."target_key" as "all_1.targetKey" , alarm_record."target_name" as "all_1.targetName" , alarm_record."source_type" as "all_1.sourceType" , alarm_record."source_id" as "all_1.sourceId" , alarm_record."source_name" as "all_1.sourceName" , alarm_record."first_alarm_time" as "all_1.firstAlarmTime" , alarm_record."alarm_time" as "all_1.alarmTime" , alarm_record."handle_time" as "all_1.handleTime" , alarm_record."level" as "all_1.level" , alarm_record."state" as "all_1.state" , alarm_record."read_state" as "all_1.readState" , alarm_record."description" as "all_1.description" , alarm_record."alarm_info" as "all_1.alarmInfo" , alarm_record."business_type" as "all_1.businessType" , alarm_record."disable_trigger_time" as "all_1.disableTriggerTime" , alarm_record."last_alarm_notify_id" as "all_1.lastAlarmNotifyId" from "public"."alarm_record" alarm_record where alarm_record."state" = 'warning' order by alarm_record."alarm_time" desc limit 10 offset 0
`
执行 sql 缺少 left join 语句

**Comment by MoonBottle** [comment]
昨天正常，今天开始不行的

**Comment by zhou-hao** [comment]
刷新依赖试试。

改一个bug ，引起的另外的bug。。。。。

**Comment by MoonBottle** [comment]
可以了，多谢大佬 🚀
