### ISSUE TITLE
通知模板里的收件人如果不填会报错

### ISSUE THREAD

**Issue by jyy1990** [jetlinks/jetlinks-community#530]
我理解通知模板里收件人如果不填
![image](https://github.com/jetlinks/jetlinks-community/assets/35125132/9036c013-fa45-442a-830c-04e89ff98929)

那我应该在场景联动里面的执行规则里填写具体收件人
![image](https://github.com/jetlinks/jetlinks-community/assets/35125132/a5e9f429-4d10-4d9f-a3d7-17b429dbdef8)

然后当我触发联动后，首先控制台会报第一个错误
![image](https://github.com/jetlinks/jetlinks-community/assets/35125132/e094c5e7-2848-4d75-8bf7-4b1e04c0232d)

当我把这个throw注释掉后，会报第二个错误
![image](https://github.com/jetlinks/jetlinks-community/assets/35125132/b19965d7-1ee2-485e-b620-ed0a3f90f4d2)

**Comment by jyy1990** [comment]
实测，如果通知模板里的收件人填上，是可以发邮件的

**Comment by zhou-hao** [comment]
什么版本

**Comment by jyy1990** [comment]
> 什么版本

三个月前拉的代码，应该是2.1分支的版本

**Comment by zhou-hao** [comment]
用最新master分支测试看看

**Comment by jyy1990** [comment]
> 用最新master分支测试看看

大佬，我用了master试了
![image](https://github.com/jetlinks/jetlinks-community/assets/35125132/230bc507-cb7f-4e15-ad70-926eaacdf46f)
当收件人选平台用户可以发邮件，选固定邮箱还是发不了，而且这块前端有bug，当你选固定邮箱填好邮箱后，下拉选又会变成平台用户
