### ISSUE TITLE
新拉master分支代码，ES报错服务起不来

### ISSUE THREAD

**Issue by jyy1990** [jetlinks/jetlinks-community#531]
就改了redis mysql es配置，别的还没动呢，内置es改true也是报一样的错
![image](https://github.com/jetlinks/jetlinks-community/assets/35125132/969125d4-4165-4b9c-80da-ef05e9de4b5c)

**Comment by zhou-hao** [comment]
1. 独立运行es。确定es启动完成后再启动jetlinks。
2. es使用7.x版本

**Comment by jyy1990** [comment]
从6.8换成7.8可以起来了
