### ISSUE TITLE
企业微服务版本使用docker容器化部署之后 文件服务有问题

### ISSUE THREAD

**Issue by zecuuzzeu7611** [jetlinks/jetlinks-community#532]
操作步骤

**Comment by zecuuzzeu7611** [comment]
操作步骤
1. 上传协议jar包
2. 重启文件微服务
3. 协议jar包读取不到

问题描述
即使通过url去下载也下载不到  但是如果不重启文件服务就不会有这个问题  一旦重启或者重新构建文件服务之后  过去上传的所有协议包都下载不到了   请问是我哪里的配置有问题嘛？  docker 映射已查 确认没有问题  在文件服务写了个新的接口  可以正常下载到文件  重启之后也可以正常下载到文件  但是原本的获取文件接口就是下载不到
PS 本地运行没有该问题 只有docker容器化运行微服务版本会出现这个问题

新写的接口如下
`@GetMapping("/test/{fileId}")
    public Mono<ResponseEntity<Resource>> testExistFile(@PathVariable String fileId) {
        File file = new File("/application/data/files/20240703/" + fileId + ".jar");
        if (file.exists()) {
            Resource resource = new FileSystemResource(file);
            return Mono.just(ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION, ContentDisposition.attachment().filename(file.getName()).build().toString())
                .contentType(MediaType.APPLICATION_OCTET_STREAM)
                .body(resource));
        } else {
            return Mono.just(ResponseEntity.notFound().build());
        }
    }`

请问怎么处理这个问题

**Comment by zhou-hao** [comment]
检查data目录是否挂载。

**Comment by zecuuzzeu7611** [comment]
通过原来的/api/file/{fileId} 接口 下载协议包会报404错误   日志一切正常   data目前确定已经挂载   容器内均可查到文件

**Comment by zecuuzzeu7611** [comment]
![image](https://github.com/jetlinks/jetlinks-community/assets/117173160/3c440118-f3cd-4c8b-ae58-f1b3d830dc57)

**Comment by zhou-hao** [comment]
是最新代码么。 看FileManager 实际是获取的什么文件

**Comment by zhou-hao** [comment]
应该是路由配置不对吧。 是最新版本吗？

**Comment by zhou-hao** [comment]
看看数据库里的 s_file 数据内容

**Comment by zecuuzzeu7611** [comment]
不确定是否是最新版本  旧版本有这个问题嘛？    路由配置没有问题的 文件服务不重启是可以正常上传下载的  
s_file的内容
![image](https://github.com/jetlinks/jetlinks-community/assets/117173160/20a8401d-e1b0-4983-9032-a61161c7774f)

**Comment by zhou-hao** [comment]
文件服务重启后就访问不到了？

**Comment by zecuuzzeu7611** [comment]
dev_protocol 表内容如下
![image](https://github.com/jetlinks/jetlinks-community/assets/117173160/e78c4c5a-62a4-46e7-8e8d-2c006c33443b)
文件服务不重启之前都是正常的  全都可以正常运行  文件服务一重启之后就会出现这样的问题   必须重新上传才能正常使用  不需要accessKey的文件都是正常的  只有需要accessKey的才会有这种情况

**Comment by zecuuzzeu7611** [comment]
本地Windows idea 运行 测试 不会有这个问题   只有docker容器化部署会有这种问题  微服务版本

**Comment by zhou-hao** [comment]
进入 /api/system/monitor.html 看看集群状态

**Comment by zecuuzzeu7611** [comment]
![image](https://github.com/jetlinks/jetlinks-community/assets/117173160/c098eabb-3047-4439-808f-ec99d1088ed8)
版本是这个

**Comment by zhou-hao** [comment]
更新最新的2.1分支或者 用master分支试试？

**Comment by zhou-hao** [comment]
或者远程debug  `ClusterFileManager`看看
