### ISSUE TITLE
不能针对某个设备下发消息

### ISSUE THREAD

**Issue by tom055** [jetlinks/jetlinks-community#54]
你好，老周，有个问题

mqtt协议的设备test001和test002，当我想要上线test001设备时，我发了一个主题的消息/device_online_status 
内容{
"status":"1",
"deviceId":"test001"
}
我的设备test001 订阅了/device_online_status 能获取信息 但是设备test002 也订阅了/device_online_status 也能获取信息
同样/read-property 我去获取设备信息 所有的设备都能获取订阅信息

**Comment by tom055** [comment]
![20210508153107](https://user-images.githubusercontent.com/17687356/117530933-755f1e80-b012-11eb-9409-0f59ec772eb2.png)

**Comment by zhou-hao** [comment]
怎么接入的

**Comment by zhou-hao** [comment]
使用 broker方式接入，建议使用自定义的topic规则以及解析协议。

**Comment by tom055** [comment]
现在单个的设备能上线 但是所有订阅该主题的设备都能收到消息 当要获取一个设备的信息的时候/read-property，所有的设备订阅了该主题都能获取这个设备的信息

**Comment by zhou-hao** [comment]
这个是mqtt borker的功能。 demo协议不适合在mqtt broker的场景。你可以把mqtt broker堪称一个消息中间件。只要订阅了相同topic的客户端，都会收到消息。

**Comment by tom055** [comment]
谢谢 好的 那我试试用通配符的方式 去发布主题消息 /read-property/{deviceId} /device_online_status/{deviceId}
