### ISSUE TITLE
common-component IntervalUnit 中 写死UTC时区是什么原因 可否修改呢？

### ISSUE THREAD

**Issue by zecuuzzeu7611** [jetlinks/jetlinks-community#540]
![image](https://github.com/user-attachments/assets/715a0dda-e02f-4496-9482-4ec4aa9a6682)
如图所示 这段代码写死了时区  我想知道为什么要这样做   我这边所有的环境都是UTC+8时区   现在我装的clickhouse是UTC+8的时区  导致聚合查询设备图标多返回了前一天的数据  确定是这里写死时区问题导致   请问我如果改成获取JVM时区会有什么影响吗？

**Comment by zhou-hao** [comment]
因为传入的时间戳都是utc时间戳？

**Comment by zecuuzzeu7611** [comment]
![image](https://github.com/user-attachments/assets/330edfab-7df9-466d-adc6-7b1f76adb37a)
如图所示 这个功能是查询设备某个数据 按天分组取最大值的情况 jetlinks自带的功能  我查询的是7月9日到7月15日  返回的数据却有7月8日的数据  正是因为上面那个UTC导致的  我想问的是 这块如果我把UTC改成了systemDefault  会不会对其余功能有影响？

**Comment by zhou-hao** [comment]
企业版？ 印象中clickhouse好像没有用到这个类啊
