### ISSUE TITLE
优化: 多参数轮询流控操作

### ISSUE THREAD

**Issue by PengyuDeng** [jetlinks/jetlinks-community#541]
现在读取属性一次性下发400个读取，设备性能受不了，我想大部分低成本芯片的工控机都有性能限制，故做了一个流控TaskExecutorProvider。

实现功能如下
1. 启用流控
2. 可设置分批发送的间隔
3. 可设置读取属性，一条读取下发指令中属性数量
4. 可自动配置2 3项功能。

这个社区版需要不？我提个PR？

**Comment by zhou-hao** [comment]
提上来看看？

**Comment by PengyuDeng** [comment]
提啰
