### ISSUE TITLE
tcp拆包问题

### ISSUE THREAD

**Issue by laoliucxy** [jetlinks/jetlinks-community#553]
在网络组件里这样加拆包脚本对吗？为什么我反而收不到设备发送的协议包，是不是我加的脚本有问题？
![tcp-8808-1](https://github.com/user-attachments/assets/54c4a208-d770-4a2a-a29a-13535e6d87b2)

**Comment by zhou-hao** [comment]
看看日志

**Comment by laoliucxy** [comment]
大佬，看哪个日志，控制台没有东西输出，Wireshark里抓到了设备向后台发送的数据包
![工具](https://github.com/user-attachments/assets/6c514c3e-2508-4b50-a172-9605e9b4ed0b)
![控制台](https://github.com/user-attachments/assets/8800d01d-ec24-404b-bb27-82495f67f3bb)

**Comment by zhou-hao** [comment]
你这也没有256字节啊。 多发送一些数据看会报错不。 或者先使用单元测试测试看看 
![QQ_1723703046912](https://github.com/user-attachments/assets/363bc9ea-8f14-4cb8-9eed-4601ae0bcae0)

**Comment by laoliucxy** [comment]
谢谢大佬，拆包可以了，是我在脚本里写的数太大了，改小一点就行。还有一个问题发过来的tcp包既有拆包也有粘包，我需要把2个脚本写在一起吗？这样写
![tcp-8808-1](https://github.com/user-attachments/assets/874d15c5-34f9-4287-944d-6548994fbc8a)

**Comment by zhou-hao** [comment]
不可以。需要先分析规则

**Comment by laoliucxy** [comment]
好的明白了，我先试试
