### ISSUE TITLE
请教下repository 可以在创建sql的时候就进行sql的group by吗

### ISSUE THREAD

**Issue by zhangle1** [jetlinks/jetlinks-community#555]
deviceErrorDetailHisEntityRepository.createQuery() 
.groupby('time',‘deviceCode’).fetch()

**Comment by zhou-hao** [comment]
请使用`deviceErrorDetailHisEntityRepository.nativeQuery` 或者使用`QueryHelper`执行原生查询

**Comment by zhangle1** [comment]
deviceErrorDetailHisEntityRepository.nativeQuery() 有orm的文档吗 。 大佬。 救救孩子

**Comment by zhangle1** [comment]
大佬有相关的jetlinks的开发群吗

**Comment by PengyuDeng** [comment]
> 大佬有相关的jetlinks的开发群吗

这个项目的README.md开头就是啊

**Comment by zhou-hao** [comment]
https://hanta.yuque.com/px7kg1/dev/pm29nrpt7ysudh86#ZjL4N
