### ISSUE TITLE
EventBus的疑问.

### ISSUE THREAD

**Issue by siaron** [jetlinks/jetlinks-community#56]
看代码中自己实现基于redis的pub/sub消费. 如果启动两个jetlink实例. 发布者发布消息. 订阅者这两个实例是都会受到. 还是并发消费只有一个会受到?

**Comment by siaron** [comment]
http://doc.jetlinks.cn/install-deployment/cluster.html#jetlinks%E9%9B%86%E7%BE%A4%E5%AE%89%E8%A3%85%E9%85%8D%E7%BD%AE
看着个文档. 如果实例id不同消息只会被某一个订阅者消费?

**Comment by zhou-hao** [comment]
从EventBus中订阅消息时可以指定订阅方式。订阅本地(订阅当前进程生产的消息)，订阅集群(订阅其他节点生产的消息)，共享订阅(相同的订阅者,只有一个订阅者收到消息)。
