### ISSUE TITLE
请教下为什么这里的时间设置成了 -1

### ISSUE THREAD

**Issue by MoonBottle** [jetlinks/jetlinks-community#579]
![image](https://github.com/user-attachments/assets/0cd654cf-79c9-4b8a-897d-b39532580753)

这样设置似乎会导致本地缓存永不失效？ 本地调试的程序修改了 redis 缓存值，如果不重启测试服务器，会导致测试服务器上的值一直是旧的

**Comment by zhou-hao** [comment]
这个通常是管理设备的缓存数据，实际场景中读取可能非常频繁，使用过期策略可能会导致间歇性的cpu过高等情况。 你可以根据实际情况调整。 不建议手动修改程序中会读取的redis缓存值，或者多个不同的应用共享同一个key。

**Comment by MoonBottle** [comment]
告警记录的缓存也用的此处，给他单独配缓存时间合适吗？
![image](https://github.com/user-attachments/assets/37f32bc2-01aa-4f74-b2ed-a85d722f176e)

**Comment by zhou-hao** [comment]
性能低一些

**Comment by MoonBottle** [comment]
> 性能低一些

明白了，谢谢大佬
