### ISSUE TITLE
bug: 子设备注册未正确设置parentId

### ISSUE THREAD

**Issue by MoonBottle** [jetlinks/jetlinks-community#580]
![image](https://github.com/user-attachments/assets/32aebf10-12b1-428c-8307-331a96a412b5)

当接受到子设备的注册消息后，截图中 1、2 两处地方都会触发执行，想请教下，为啥要执行两次，并且子设备在 device_instance 表新增后 parentId 还是空的，要再次发送一个注册消息，执行以下 update 才可以和父设备绑定成功
![image](https://github.com/user-attachments/assets/fc4c15be-6592-4b6d-9b1a-59f7a1be8766)

**Comment by zhou-hao** [comment]
这块似乎是有问题。我瞅瞅。

**Comment by zhou-hao** [comment]
更新试试。 执行2次时因为，有可能只有设备注册消息，而没有子设备注册。

**Comment by MoonBottle** [comment]
parentId 可以正确被 set 了，但是调试过程中发现一个新的现象，当我把设备删除后，redis 中的缓存没有被清理（图中 1 所示），从而导致再次接收到注册报文后，会走到图中 2 位置，不会走到图中 3 位置进行设备新增

![image](https://github.com/user-attachments/assets/8b647734-a0be-463c-8d6b-d8ce9906bdd2)

**Comment by MoonBottle** [comment]
好像是偶现的，又删了几次， redis 缓存正常被清理了 🥲

**Comment by MoonBottle** [comment]
> parentId 可以正确被 set 了，但是调试过程中发现一个新的现象，当我把设备删除后，redis 中的缓存没有被清理（图中 1 所示），从而导致再次接收到注册报文后，会走到图中 2 位置，不会走到图中 3 位置进行设备新增
> 
> ![image](https://private-user-images.githubusercontent.com/12904505/381032520-8b647734-a0be-463c-8d6b-d8ce9906bdd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODkxNDMsIm5iZiI6MTczMDE4ODg0MywicGF0aCI6Ii8xMjkwNDUwNS8zODEwMzI1MjAtOGI2NDc3MzQtYTBiZS00NjNjLThkNmItZDhjZTk5MDZiZGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA4MDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZmM5NjYyYmFkZjY4MzBjNTAxZmFiOTI1ODIyYmRlMjE3ZmE4N2MzYjYxZGQ4YmYwNjNlOTlmOTdjZmI0ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VWRw_FoV0lJ-xG2p2ecNZI_PdmWxYHUTKPHbmcBKRdU)

知道了，是我操作有问题。我在本地创建了设备，然后在测试服务上删了此设备（此时 redis 缓存被清理了），但是我本地服务还在运行的情况下，我再次发送了注册报文，走到了图 2 位置，就出现了上面所说的情况，只能手动清理缓存了 🥲
