### ISSUE TITLE
@Subscribe 在发生异常时订阅关系失效

### ISSUE THREAD

**Issue by MoonBottle** [jetlinks/jetlinks-community#581]
![image](https://github.com/user-attachments/assets/1864821d-3d7c-4f5a-ac34-142bc38b4f41)

如图中所示 1 处抛出异常，会在 2 处进行异常日志打印，但后续设备再上报属性时，不会进行 1 的方法中，导致消息无法被正确处理。

我本地尝试进行如下修改后异常可以被正确打印并且设备再上报属性时可以进入 1 的方法，但是感觉直接返回 Mono.empty() 好像不太好? 所以来请教下这里如何处理合适
![image](https://github.com/user-attachments/assets/9b59c75e-0fa9-47a6-8ede-abd4bd8549ab)

**Comment by zhou-hao** [comment]
应该是EventBus的问题 ，检查是否使用的`InternalEventBus`。

**Comment by MoonBottle** [comment]
> 应该是EventBus的问题 ，检查是否使用的`InternalEventBus`。

明白了，我用的是 `BrokerEventBus` ，谢谢大佬
