### ISSUE TITLE
接口返回的采样时间是时间戳，转换之后是17：58,但是在平台上展示的是5：58，请问是什么原因呢？

### ISSUE THREAD

**Issue by yumingyaya** [jetlinks/jetlinks-community#582]
![1](https://github.com/user-attachments/assets/80e5d5c0-3851-41e5-8c52-7b1a5d7f86d5)
![2](https://github.com/user-attachments/assets/00a32417-fcff-4194-8b6a-be74de36e973)
![3](https://github.com/user-attachments/assets/eff22c66-38a5-4902-9514-9434dc7f80e7)

**Comment by zhou-hao** [comment]
时间格式使用 HH:mm:ss  HH才是24小时制

**Comment by yumingyaya** [comment]
好的，非常感谢答疑！



在 2024-11-14 09:09:03，"老周" ***@***.***> 写道：

时间格式使用 HH:mm:ss HH才是24小时制

**Comment by yumingyaya** [comment]
你好，还有个问提想请教下，就是我的站点没有安装设备，按理说监测指标的值都是Null，但是物联网里面直接展示了0，这个在哪里可以配置吗



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月14日 10:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [jetlinks/jetlinks-community] 接口返回的采样时间是时间戳，转换之后是17：58,但是在平台上展示的是5：58，请问是什么原因呢？ (Issue #582) |

Closed #582 as completed.

**Comment by zhou-hao** [comment]
看设备日志里上报的数据是什么

**Comment by yumingyaya** [comment]
日志里面返回的是0



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月14日 18:15 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [jetlinks/jetlinks-community] 接口返回的采样时间是时间戳，转换之后是17：58,但是在平台上展示的是5：58，请问是什么原因呢？ (Issue #582) |

看设备日志里上报的数据是什么

**Comment by zhou-hao** [comment]
那不就对了？

**Comment by yumingyaya** [comment]
好的，谢谢，我们再看下
















在 2024-11-14 18:59:03，"老周" ***@***.***> 写道：

那不就对了？
