### ISSUE TITLE
mqtt设备数据大批量上报后，mqtt服务的服务总线消息总是滞后。怎么办？

### ISSUE THREAD

**Issue by zzj957091** [jetlinks/jetlinks-community#586]
我的mqtt设备将信息发送到了jetlinks平台后，另一个平台监听jetlinks的mqtt服务总线。发现消息多了之后，服务总线的消息总是滞后。有什么解决办法吗

**Comment by zhou-hao** [comment]
通过什么方式监听的。 平台没有提供mqtt服务总线啊？

**Comment by zhou-hao** [comment]
JetLinks 里没有mqtt服务总线这个东西。不清楚你具体是怎么使用的。
