### ISSUE TITLE
关于服务性能问题

### ISSUE THREAD

**Issue by GoneGo1ng** [jetlinks/jetlinks-community#589]
请问，目前社区版的服务能否支持百万级数量的设备接入，如果可以支持的话大概需要消耗多少服务器资源，是否有相应的性能测试报告。如果社区版不支持，企业版是否提供高并发设备接入的服务，价格怎么了解。

**Comment by zhou-hao** [comment]
社区版不完全支持集群，所以比较困难。 对于百万级数量需要多少服务器资源很难评估：不同的设备连接方式，数据上报频率，服务器网络环境等差异都可能较大。 企业版加入[QQ⑤群 554591908](https://qm.qq.com/cgi-bin/qm/qr?k=jiirLiyFUecy_gsankzVQ-cl6SrZCnv9&&jump_from=webapi)联系群管理商务咨询

**Comment by GoneGo1ng** [comment]
> 社区版不完全支持集群，所以比较困难。 对于百万级数量需要多少服务器资源很难评估：不同的设备连接方式，数据上报频率，服务器网络环境等差异都可能较大。 企业版加入[QQ⑤群 554591908](https://qm.qq.com/cgi-bin/qm/qr?k=jiirLiyFUecy_gsankzVQ-cl6SrZCnv9&&jump_from=webapi)联系群管理商务咨询

感谢
