### ISSUE TITLE
采用docker运行，报错后端容器报访问不了redis

### ISSUE THREAD

**Issue by hotsmile** [jetlinks/jetlinks-community#6]
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to redis:6379
jetlinks-ce | at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
jetlinks-ce | at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
jetlinks-ce | at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:234)
jetlinks-ce | at io.lettuce.core.RedisClient.connect(RedisClient.java:207)

Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: No route to host: redis/172.18.0.3:6379
jetlinks-ce | Caused by: java.net.ConnectException: finishConnect(..) failed: No route to host

**Comment by zhou-hao** [comment]
看看redis使用docker启动起来了没

**Comment by hotsmile** [comment]
启动了，我宿主机都可以访问，我map到宿主机的6379端口，都是可以访问的

**Comment by zhou-hao** [comment]
看之前的日志`No route to host: redis/172.18.0.3:6379`,可能是docker网络问题,关闭防火墙试试呢。
