### ISSUE TITLE
[QUESTION]How JETLINKS maintains the connection status of the device

### ISSUE THREAD

**Issue by LLLLimbo** [jetlinks/jetlinks-community#63]
I have some questions about the way JETLINKS maintains and stores the connection status of devices:

### Update Strategy

- Whenever the server side receives a message or heartbeat from the device 
- Timed scan of last activity time

### Storage

- Using Redis to store the last active time of a device
- Using Postgres to store the last active time of a device

Please help me understand it

**Comment by zhou-hao** [comment]
1. Device real status will managed by `DeviceSessionManager` in memory.
2. When device register to `DeviceSessionManager`, device `state`,`server id` will save to `DeviceRegistry`(Redis).
3. Publish `DeviceOnlineMessage` to `EventBus` `/device/{productId}/{deviceId}/online`.
4. `DeviceMessageBusinessHandler` subscribe topic `/device/*/*/online,offline` from `EventBus` when server started.
5.  Synchronization device real state to `PostgreSQL` when `EventBus` sent `/device/*/*/online,offline` message ,( get `state` from DeviceRegsitry )
6. Check real state when api request: `/device/instance/{deviceId}/detail`  and synchronization it.

**Comment by LLLLimbo** [comment]
> 1. Device real status will managed by `DeviceSessionManager` in memory.
> 2. When device register to `DeviceSessionManager`, device `state`,`server id` will save to `DeviceRegistry`(Redis).
> 3. Publish `DeviceOnlineMessage` to `EventBus` `/device/{productId}/{deviceId}/online`.
> 4. `DeviceMessageBusinessHandler` subscribe topic `/device/*/*/online,offline` from `EventBus` when server started.
> 5. Synchronization device real state to `PostgreSQL` when `EventBus` sent `/device/*/*/online,offline` message ,( get `state` from DeviceRegsitry )
> 6. Check real state when api request: `/device/instance/{deviceId}/detail`  and synchronization it.

Thank you for your answer, but I still have a question:

Is it not quite appropriate to store the real state of the device in memory? This is not conducive to horizontal scaling. Perhaps it would be better to use Redis' ZSET to store the device ID and use the device's last active time as its score?

**Comment by zhou-hao** [comment]
> 2. When device register to `DeviceSessionManager`, device `state`,`server id` will save to `DeviceRegistry`(Redis).

In fact, Redis can not keep real-time for device state:
e.g. When the service restarts or crashes, the state does not have time to synchronize.

JetLinks device state check strategy :

1. Get `server id` info in `DeviceRegistry` (store in redis, cache in memory.).
2. RPC the `server id`: Get device real state. 
3. If cached `state` not equals RPC response, synchronization to `PostgreSQL `

TIP:  The same principle was used in a send device message (when cluster).

**Comment by ttanyan** [comment]
牛逼
