### ISSUE TITLE
关于自定义TCP协议的拆包问题

### ISSUE THREAD

**Issue by ws1990** [jetlinks/jetlinks-community#65]
1. 场景：
tcp客户端通过消息头指定整个数据的大小，比如##0248表示后面的整个数据有248个字符
2. 问题：
客户端数据比较长的时候会被拆成两个包，导致解析失败
3. 期望：
通过netty的LengthFieldBasedFrameDecoder进行合并处理
4. 结果：
在ProtocolSupportProvider类以及DeviceMessageCodec类，没有找到可以介入的地方

**Comment by zhou-hao** [comment]
网络组件配置里可以配置粘拆包处理规则



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ws1990 ***@***.***&gt;
发送时间: 2021年6月26日 21:33
收件人: jetlinks/jetlinks-community ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[jetlinks/jetlinks-community] 关于自定义TCP协议的拆包问题 (#65)





  
场景：
 tcp客户端通过消息头指定整个数据的大小，比如##0248表示后面的整个数据有248个字符 

问题：
 客户端数据比较长的时候会被拆成两个包，导致解析失败 

期望：
 通过netty的LengthFieldBasedFrameDecoder进行合并处理 

结果：
 在ProtocolSupportProvider类以及DeviceMessageCodec类，没有找到可以介入的地方

**Comment by ws1990** [comment]
我看了下，网络组件那里有四种方式，1. 不处理；2. 分割符；3. 自定义脚本；4. 固定长度；我尝试过使用分割符\r\n，但是不起作用，1和4不满足需求，3不是很清楚应该怎么去写？有相关的示例吗？

**Comment by zhou-hao** [comment]
https://github.com/jetlinks/jetlinks-community/blob/master/jetlinks-components/network-component/tcp-component/src/test/java/org/jetlinks/community/network/tcp/parser/strateies/ScriptPayloadParserBuilderTest.java



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ws1990 ***@***.***&gt;
发送时间: 2021年6月26日 21:46
收件人: jetlinks/jetlinks-community ***@***.***&gt;
抄送: 老周 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[jetlinks/jetlinks-community] 关于自定义TCP协议的拆包问题 (#65)





 
我看了下，网络组件那里有四种方式，1. 不处理；2. 分割符；3. 自定义脚本；4. 固定长度；我尝试过使用分割符\r\n，但是不起作用，1和4不满足需求，3不是很清楚应该怎么去写？有相关的示例吗？

**Comment by ws1990** [comment]
我看了下示例的代码，老实说，看不太明白。而且我觉得，对于拆包粘包这种比较复杂的问题，通过脚本的方式去解决，总感觉有点奇怪，如果可以的话，还是希望能在自定义协议那儿提供更多的可扩展点。

**Comment by ws1990** [comment]
我看了下示例的代码，老实说，看不太明白。而且我觉得，对于拆包粘包这种比较复杂的问题，通过脚本的方式去解决，总感觉有点奇怪，如果可以的话，还是希望能在自定义协议那儿提供更多的可扩展点。

**Comment by ws1990** [comment]
不管怎么说，还是感谢你的回答，这个问题我先关了哈
