### ISSUE TITLE
IDEA编译源码报错

### ISSUE THREAD

**Issue by Wislove** [jetlinks/jetlinks-community#66]
我使用IDEA2018.3运行源码，build出错是什么原因，有多处build出错
![image](https://user-images.githubusercontent.com/12807316/123937901-3b364b80-d9c9-11eb-9725-55b40b3206a1.png)

**Comment by zhou-hao** [comment]
使用最新的java 8版本(`1.8.0_2xx`),你的是`1.8.0_05`
