### ISSUE TITLE
新增子模块访问404

### ISSUE THREAD

**Issue by xiangjiezhao** [jetlinks/jetlinks-community#67]
在jetlinks-manager下新增子模块，通过postMan访问后台接口路径，返回404
![image](https://user-images.githubusercontent.com/40494033/124058100-4a65d980-da5b-11eb-94ce-b6cae767e84b.png)

**Comment by xiangjiezhao** [comment]
访问device/instance这些已有接口会返回405 Method Not Allowed，所以新增模块要在哪里设置权限吗

**Comment by zhou-hao** [comment]
依赖是否引入到 standalone

**Comment by xiangjiezhao** [comment]
![image](https://user-images.githubusercontent.com/40494033/124059800-4a1b0d80-da5e-11eb-9bc4-6e2f79af990f.png)
依赖到了业务管理模块上

**Comment by xiangjiezhao** [comment]
> 依赖是否引入到 standalone

好的，谢谢

**Comment by tom055** [comment]
@zhou-hao 已经将module引入到 standalone里面了 接口还是木有生效 是怎么回事儿呢？
![22](https://user-images.githubusercontent.com/17687356/130744873-9dfaff89-f43f-454c-8512-6c4186037fb0.png)
![33](https://user-images.githubusercontent.com/17687356/130744884-7c9c7e4e-e95e-4f5a-af73-9ebc37391373.png)

**Comment by tom055** [comment]
失误了 找到原因了
