### ISSUE TITLE
接口调试权限问题

### ISSUE THREAD

**Issue by xiangjiezhao** [jetlinks/jetlinks-community#68]
通过postMan调试后台接口，返回
401，用户未登录

**Comment by xiangjiezhao** [comment]
![image](https://user-images.githubusercontent.com/40494033/124076235-907d6600-da78-11eb-822e-d6d59ed2f44b.png)

**Comment by zhou-hao** [comment]
1. 调用接口或者浏览器F12查看头`X-Access-Token`
```js
POST /authorize/me
Content-Type application/json

{"username":"","password":""}
```

2. 请求时添加头`X-Access-Token`

**Comment by xiangjiezhao** [comment]
> 1. 调用接口或者浏览器F12查看头`X-Access-Token`
> 
> ```js
> POST /authorize/me
> Content-Type application/json
> 
> {"username":"","password":""}
> ```
> 
> 1. 请求时添加头`X-Access-Token`

感谢，已解决
