### ISSUE TITLE
Error creating bean with name 'autoResolveI18nMessageSource' defined in class path resource

### ISSUE THREAD

**Issue by acercom** [jetlinks/jetlinks-community#70]
这是源包错误吗，启动不了官网DEMO
![image](https://user-images.githubusercontent.com/13848222/124728344-19494580-df42-11eb-9489-6735e8322ca4.png)

**Comment by zhou-hao** [comment]
提供一下完整的异常栈

**Comment by acercom** [comment]
这个是maven的自定义仓库路径名字有“_”(下划线)就读不到源包就报错，现在问题了
![image](https://user-images.githubusercontent.com/13848222/124735806-f79f8c80-df48-11eb-91b0-72f5e7e43265.png)
