### ISSUE TITLE
Unable to connect to Redis; nested exception is org.springframework.data.redis.connection.PoolException

### ISSUE THREAD

**Issue by acercom** [jetlinks/jetlinks-community#71]
已启动redis,就是说连不上redis,版本5.0.10
![image](https://user-images.githubusercontent.com/13848222/124728603-4f86c500-df42-11eb-994e-8740c71a336f.png)
![image](https://user-images.githubusercontent.com/13848222/124728657-59102d00-df42-11eb-94e8-f1a6b7e1f5f6.png)

**Comment by zhou-hao** [comment]
上面应该还有错误

**Comment by acercom** [comment]
读不到源码包就一系列报错。这边已解决
