### ISSUE TITLE
根本就不是开源，代码具有后门，丢中国人的脸

### ISSUE THREAD

**Issue by 3328350766** [jetlinks/jetlinks-community#73]
这个jetlinks与物联网根本就没有任何关系，只是一套web系统，而且代码里面加了后门，依赖不开源的jetlinks-support包，而jetlinks-support包又依赖jetlinks-core包，所谓的作者老周，根本就不懂物联网的概念，代码写的稀巴乱，大家千万不要为这款不开源东西浪费时间！

**Comment by zhou-hao** [comment]
嗯，没你懂，代码不会看也就算了，给你了源代码你都找不到，哈哈哈。

**Comment by 3328350766** [comment]
你这个欺世盗名的狗渣渣，代码写得象狗屎一样，还来卖钱，你把你妈和老婆拉出来卖算了！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月15日(星期四) 中午1:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jetlinks/jetlinks-community] 根本就不是开源，代码具有后门，丢中国人的脸 (#73)





 
嗯，没你懂，代码不会看也就算了，给你了源代码你都找不到，哈哈哈。

**Comment by zhou-hao** [comment]
这货是职业喷子，大家不用理会 。
![image](https://user-images.githubusercontent.com/7791838/125735546-6334151a-40dc-42c5-be3f-df99a783bcd9.png)

**Comment by zhou-hao** [comment]
SB年年有，今年特别多。
