### ISSUE TITLE
关于部署的问题，Nginx 部署后访问Nginx 后，访问不了

### ISSUE THREAD

**Issue by ljxqxq** [jetlinks/jetlinks-community#75]
关于部署的问题(jar打包部署后台，Nginx部署前台)，Nginx 部署后访问Nginx 后，访问不了，如下图：。
![image](https://user-images.githubusercontent.com/10807375/125917111-7bdf1fa8-d766-4c3a-92ec-6f3dbd886a6f.png)
 Nginx 的conf文件如下配置：
![image](https://user-images.githubusercontent.com/10807375/125917348-9ce6e7c7-3b1d-43f9-8085-120708c15cc9.png)

后台jar包已经启动成功了，配置的端口是8848

_Originally posted by @ljxqxq in https://github.com/jetlinks/jetlinks-community/issues/74#issuecomment-881272764_

**Comment by zhou-hao** [comment]
你应该直接访问前端啊

**Comment by ljxqxq** [comment]
被自己蠢哭了，直接访问ip就可以了
