### ISSUE TITLE
获取事件信息为空

### ISSUE THREAD

**Issue by erma66** [jetlinks/jetlinks-community#76]
定义了这样一个事件
![image](https://user-images.githubusercontent.com/42696199/125938282-2d3c724b-67f5-4749-99bb-8dd3a6f5c5cd.png)
日志中也有数据
![image](https://user-images.githubusercontent.com/42696199/125938362-948de29e-792f-4451-b811-c0c1a83b2702.png)
页面显示一直是0
![image](https://user-images.githubusercontent.com/42696199/125938486-ec7cf336-f7ba-42bc-b2eb-5df89c719b19.png)
用postman查询elasticsearch是这样的
![image](https://user-images.githubusercontent.com/42696199/125938592-1b1129f2-d7fc-428e-b179-081b60e93acf.png)
跟踪代码发现代码中查询时没有用带*的匹配查询，而是后面拼了一个_alias，应该是这个原因导致的，请问该怎么解决

**Comment by zhou-hao** [comment]
事件在哪定义的。增加事件后有没有应用配置

**Comment by erma66** [comment]
抱歉，没有点应用配置，点了之后就好了，只是经常出现这个报错，是不是因为用了内嵌的elasticsearch
![image](https://user-images.githubusercontent.com/42696199/126107770-409a2d97-6813-4b48-b8c5-5d2fb8d3a0b3.png)
![image](https://user-images.githubusercontent.com/42696199/126107789-f8d72d27-5b32-4d34-a9ba-e27ed8ae1b0f.png)

**Comment by zhou-hao** [comment]
删除es的数据，然后再发布。这是因为 还没有发布物模型 就上报了数据，导致es 索引不对。

**Comment by erma66** [comment]
好的，谢谢
