### ISSUE TITLE
自定义token策略不生效问题

### ISSUE THREAD

**Issue by xiangjiezhao** [jetlinks/jetlinks-community#77]
1.自定义UserTokenGenerator
![1626687487(1)](https://user-images.githubusercontent.com/40494033/126139320-ffe3259a-fd22-47fe-b7cd-e2708fa88ee7.jpg)
2.自定义UserTokenParser
![1626687593(1)](https://user-images.githubusercontent.com/40494033/126139607-66ad4cf5-256d-4612-92a4-53d937b0d196.jpg)
3. 在登录时，多传入一个参数: token_type=token
![image](https://user-images.githubusercontent.com/40494033/126139731-df0be05a-268a-41a7-b0e8-44428566fd52.png)

按照教程步骤做的，可为什么还是按照默认方式创建的token

**Comment by zhou-hao** [comment]
请使用`ReactiveUserTokenParser`和`ReactiveUserTokenGenerator`

**Comment by xiangjiezhao** [comment]
![1626747419(1)](https://user-images.githubusercontent.com/40494033/126252108-693245a9-0402-4453-8957-a1d664b1e36d.jpg)

谢谢回复，再请教下
，到这一步获取参数中的token要怎么做
，获取请求体一直为空

**Comment by zhou-hao** [comment]
不能这么操作。你的token是在body里的？

**Comment by xiangjiezhao** [comment]
目的：自定义一个token_type=“app”,实现一个token永不过期
目前进行的尝试：按照教程自定义了ReactiveUserTokenGenerator，ReactiveUserTokenParser，请求体里添加了token_type
遇到的问题：ReactiveUserTokenParser获取参数中的token这一步，token要从哪里得到？
操作方式：
请求里添加了token_type
![image](https://user-images.githubusercontent.com/40494033/126256006-0444d0a0-ac59-4ba8-be0c-25b6bf4ada6e.png)
![image](https://user-images.githubusercontent.com/40494033/126256089-a6472eb7-a9a4-4244-96b1-aa7cb0ed70e0.png)
![image](https://user-images.githubusercontent.com/40494033/126256152-914d63a2-16f6-48fa-8fce-71604c5b1988.png)

**Comment by zhou-hao** [comment]
你实际请求 token放在哪就从哪获取咯。 默认在登录的时候指定`expires:-1`就是不过期。

**Comment by xiangjiezhao** [comment]
有个疑问，我理解的ReactiveUserTokenParser是解析其他接口传的token值的，
那接口authorize/login获取token的时候是不传“X-Access-Token” header的，
所以会一直获取不到token（没传所以没有）
目标：
实现默认时长token（pc）和自定义时长token（app），通过token_type区分
问题：
无法通过authorize/login接口获取自定义时长的token
![image](https://user-images.githubusercontent.com/40494033/126273856-7831bfef-32c6-4b58-88fc-f6f476934aa4.png)
![image](https://user-images.githubusercontent.com/40494033/126274272-696645b2-b830-4768-80dc-ad2bacf977a4.png)
![image](https://user-images.githubusercontent.com/40494033/126274311-28bcd335-4e8a-412c-9553-95b39fdbd3a6.png)

**Comment by xiangjiezhao** [comment]
![image](https://user-images.githubusercontent.com/40494033/126587786-804fedc7-c563-43cd-917c-b2cbe6a17135.png)
![image](https://user-images.githubusercontent.com/40494033/126587803-9d7dd46d-61e8-4a28-a775-d8d760f22b9f.png)
请问一下，这里有两个UserTokenGenPar（default和自定义），传值也带有token_type标识，为什么还是在用默认的generator实现？

**Comment by zhou-hao** [comment]
tokenType？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xiangjiezhao ***@***.***&gt;
发送时间: 2021年7月22日 11:55
收件人: jetlinks/jetlinks-community ***@***.***&gt;
抄送: 老周 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[jetlinks/jetlinks-community] 自定义token策略不生效问题 (#77)





 

 
 请问一下，这里有两个UserTokenGenPar（default和自定义），传值也带有token_type标识，为什么还是在用默认的generator实现？

**Comment by xiangjiezhao** [comment]
谢谢，搞定了
