### ISSUE TITLE
MQTT broker接入，平台无法读取模拟设备的属性

### ISSUE THREAD

**Issue by ezhoureal** [jetlinks/jetlinks-community#78]
你好，我按照官方文档到了[这一步](http://doc.jetlinks.cn/advancement-guide/third-mqtt.html#%E6%A8%A1%E6%8B%9F%E5%B9%B3%E5%8F%B0%E8%AF%BB%E5%8F%96%E8%AE%BE%E5%A4%87%E5%B1%9E%E6%80%A7)，但是平台始终无法收到模拟设备发送的数据。之前模拟设备上下线功能是ok的。

这里发送数据到/read-property，平台收不到
![image](https://user-images.githubusercontent.com/30425920/126617269-c99ffce1-ecee-4200-bd77-5223550a148e.png)

我使用的是官方提供的演示协议，其它配置也都是依照官方文档。

**Comment by zhou-hao** [comment]
topic修改为/read-property-reply 试试

**Comment by ezhoureal** [comment]
成功了
