### ISSUE TITLE
子设备不能自动注册，未发布子设备自注册

### ISSUE THREAD

**Issue by zeje** [jetlinks/jetlinks-community#79]
![_4{D4 TAPF{FF@1RW3MX}XH](https://user-images.githubusercontent.com/10680634/127015681-858731bf-a2c7-49a4-9097-e5cdd9f38141.png)
createDeviceMessageTopic时，没办法eventBus.publish子设备的自注册的topic。
子设备的自注册又期望通过@Subscribe("/device/*/*/message/children/*/register") 能订阅到。

如下topic：需要把childDeviceId去掉，才能够在网关设备上线时，发布相关子设备自注册的topic。
子设备注册
与子设备消息配合使用,实现设备与网关设备进行自动绑定.
topic: /{productId}/{deviceId}/child/{childDeviceId}/register

但是，v2官方协议包对childDeviceId又有依赖，

所以，子设备的自注册：可能可以通过设备的自注册（官方文档没有看到设备自注册的topic，只找到了register("/*/register", DeviceRegisterMessage.class)，）

问题又来了，设备要能正常连接，才能发布topic，而平台没有对应的device信息，又怎么能自己connect，然后register……

求解。

**Comment by zhou-hao** [comment]
目前不支持设备自己进行自注册。只支持通过网关进行自注册。 所以网关需要先接入平台，发送topic ` /{productId}/{deviceId}/child/{childDeviceId}/register`

**Comment by zeje** [comment]
![`RIX23BJH5TSW)CEY6IKT~K](https://user-images.githubusercontent.com/10680634/127082687-1155d955-f4c4-48c6-916a-f54a4dbc1d95.jpg)
就是从 /{productId}/{deviceId}/child/{childDeviceId}/register 进来的，平台没有手动创建childDeviceId相关的设备，jetlinks目前没办法自注册childDeviceId的设备

**Comment by zhou-hao** [comment]
更新代码试试

**Comment by zeje** [comment]
![X8IKKVGA PK9$TD_22BP2CO](https://user-images.githubusercontent.com/10680634/127086186-bd086e24-57e8-48ec-9663-8e50e382f562.png)

已验证，还是不行

**Comment by zhou-hao** [comment]
实际测试是可以的哟。

**Comment by zeje** [comment]
> 实际测试是可以的哟。

是的，目前我重新测试也是可以的，可能是特殊场景有问题（暂时提供不了重现步骤），后续若重现再反馈。
