### ISSUE TITLE
建议物模型里面的告警设置增加防抖功能

### ISSUE THREAD

**Issue by nhbcyz** [jetlinks/jetlinks-community#8]
告警设置里面的触发器这里建议加一个防抖的处理，实际情况会出现设备的属性值在某个边界值来回跳动的情况，可能会出现短时间内可能会产生大量的告警记录。
scada里面一般是有个时间窗口的处理，一个时间窗口内连续报多少条，只报一条出来。或者报一条，但是会加上一个次数。

**Comment by zhou-hao** [comment]
如果时间窗口要计算次数，会出现延迟吧，比如：10秒内只报警一次，那么延迟就有10秒。

**Comment by gyf520** [comment]
https://github.com/jetlinks/jetlinks-ui-antd/commit/74fd07ededb23c5114ba435e0ddb3a57893f8dcc

**Comment by nhbcyz** [comment]
> 如果时间窗口要计算次数，会出现延迟吧，比如：10秒内只报警一次，那么延迟就有10秒。

简单的做法是：第一次有越限报出来，后面10秒内再次产生的话就不报了。
