### ISSUE TITLE
对Date类型的处理问题

### ISSUE THREAD

**Issue by xiangjiezhao** [jetlinks/jetlinks-community#81]
环境：数据库为mysql，表中字段有Date和DateTime两种类型
问题：目前看框架下对时间的处理都是long类型的时间戳，进行保存数据库Date和DateTime类型时，sql执行语句读不出来字段，报错：io.r2dbc.spi.R2dbcDataIntegrityViolationException: Field 'limit_dt' doesn't have a default value
![1627953846(1)](https://user-images.githubusercontent.com/40494033/127943094-92e186d2-c6dc-45e8-9d22-e41933b07984.jpg)

**Comment by zhou-hao** [comment]
你设置了字段为非空吧？ 字段上注解`@DefaultValue(generator=Generators.CURRENT_TIME)` 试试

**Comment by xiangjiezhao** [comment]
加上了还是一样的
![1627956052(1)](https://user-images.githubusercontent.com/40494033/127945915-dbd6a685-f29b-49f8-ab74-ebf49b83e80f.jpg)
sql执行语句里还是不显示该字段：
insert into jetlinks.legal_person ( `address` , `is_delete` , `legal_code` , `remark` , `telephone` , `is_balance` , `link_man` , `user_id` , `industry_code` , `legal_name` , `id` , `legal_state` , `email` , `legal_jpname` ) 
前端传过来的参数：
![image](https://user-images.githubusercontent.com/40494033/127946152-feb9e94e-c865-4025-a329-1b5c87efe1ed.png)

**Comment by zhou-hao** [comment]
你没注解`Column`？

**Comment by xiangjiezhao** [comment]
汗。。感谢大佬，搞定了
