### ISSUE TITLE
【bug】点击 产品--->编辑 会出错

### ISSUE THREAD

**Issue by honggesmile** [jetlinks/jetlinks-community#84]
下载最新的代码： 都是master分支(版本1.10）,源码编译，运行后登录，点击产品---->编辑，会出错。
![screenshot_1](https://user-images.githubusercontent.com/49434431/128149097-2092d0d4-e175-4886-aacb-dd92d8d42e58.png)
![screenshot_2](https://user-images.githubusercontent.com/49434431/128149113-45483180-2944-431b-82e4-2ecb31f67c14.png)
感觉应该是前端代码没更新。

**Comment by zhou-hao** [comment]
f12看看是哪个接口返回404

**Comment by honggesmile** [comment]
> f12看看是哪个接口返回404

{"timestamp":1628074894244,"path":"/device/category/_query/no-paging","status":404,"error":"Not Found","requestId":"10b12ec8-116"}
![2021-08-04 19-02-01屏幕截图](https://user-images.githubusercontent.com/49434431/128170422-8d9e2e57-ab13-4c02-9695-199ccc90fd0d.png)

**Comment by zhou-hao** [comment]
更新代码再试试呢

**Comment by honggesmile** [comment]
> 更新代码再试试呢

已经是最新的代码了，master分支。我看群里也有不少人有这个问题。

**Comment by zhou-hao** [comment]
再更新

**Comment by honggesmile** [comment]
> 再更新

最新的代码正常了。
