### ISSUE TITLE
数据查询问题

### ISSUE THREAD

**Issue by xiangjiezhao** [jetlinks/jetlinks-community#88]
问题：下图红框内的代码，从mysql数据库里取值没有取到，看控制台并没有输出执行语句，请问是什么原因呢？
![1628471075(1)](https://user-images.githubusercontent.com/40494033/128651751-68825b55-4215-42d4-8ee4-801a3813e4f9.jpg)

**Comment by zhou-hao** [comment]
响应式流需要组合在一起，不能有中断。比如:

```java
//错误
return flux.doOnNext(data->this.save(data).subscribe());

//正确
return flux.flatMap(this::save);

//错误,没有将流组合在一起
request.flatMap(this::save);
Mono<Void> result = this.notifySaveSuccess();
return result;

//正确
return request
    .flatMap(this::save)
    .then(this.notifySaveSuccess());

```

**Comment by xiangjiezhao** [comment]
![){KSBM}EWZPAW__T`QGUQ44](https://user-images.githubusercontent.com/40494033/128798600-7b2e0ba2-a286-499e-8cbe-a47a334118f2.png)
大佬，再请教下，红框内的代码只要有return就算中断流操作了吗，那我应该怎么把入参操作完再返回呢？目前这段代码取不到userId这个值

**Comment by zhou-hao** [comment]
响应式必须组合在一起。不能中断。

**Comment by xiangjiezhao** [comment]
![image](https://user-images.githubusercontent.com/40494033/128813911-364db61f-61e1-42b4-97df-3b953fe38d53.png)
现在返回的类型多了一层Mono，这种应该怎么去掉啊，用了cast方法报类型转换异常。。

**Comment by zhou-hao** [comment]
有异步操作的 都返回Mono或者Flux。然后用 flatMap 等api进行组合。

**Comment by zhou-hao** [comment]
参照一下 https://github.com/jetlinks/jetlinks-community/blob/master/jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/web/GatewayDeviceController.java 吧

**Comment by xiangjiezhao** [comment]
解决了，非常感谢！
