### ISSUE TITLE
获取当前操作人问题

### ISSUE THREAD

**Issue by xiangjiezhao** [jetlinks/jetlinks-community#89]
问题描述：
Entity实现了RecordCreationEntity
![1628495016(1)](https://user-images.githubusercontent.com/40494033/128674028-3c9aa21b-feee-49d8-af0a-5f31a8e297f3.jpg)
这里也用编程的方式来获取，还是获取不到操作人信息
![1628495277(1)](https://user-images.githubusercontent.com/40494033/128674336-0c5189ac-7cb8-4daf-a629-7ad48cae82a3.jpg)

**Comment by zhou-hao** [comment]
相同的问题 #88
