### ISSUE TITLE
自定义的http协议中如何校验http请求体json中的token？

### ISSUE THREAD

**Issue by priceou** [jetlinks/jetlinks-community#91]
因为没有写到header中，只写在了body中，没办法通过Authentication.currentReactive()校验

**Comment by zhou-hao** [comment]
通过设备接入网关，在message里获取消息进行处理。http协议平台不会进行鉴权。

**Comment by priceou** [comment]
没有办法在ProtocolSupportProvider中通过ServiceContext.getService()拿到一个可以校验token的spring bean吗？

**Comment by zhou-hao** [comment]
可以。不过也可以直接参照tcp那样，从device.getConfig里获取进行验证。

**Comment by priceou** [comment]
找到了，UserTokenManager。谢谢。
