### ISSUE TITLE
多表更新问题

### ISSUE THREAD

**Issue by xiangjiezhao** [jetlinks/jetlinks-community#93]
描述：一个编辑操作涉及多张表，当第一个表的字段未修改时，界面提示message：“no colums are update”，程序终止并且不执行第二张表的更新操作
![image](https://user-images.githubusercontent.com/40494033/129536735-79ee6511-a176-40d3-8ce1-adc3aee24ae8.png)
问题：
1.怎么让流的进程继续
2.界面如何不提示message：“no colums are update”

**Comment by priceou** [comment]
execute().flatmap(count -> {if  (count > 0) {}})

**Comment by xiangjiezhao** [comment]
已解决
