### ISSUE TITLE
怎么调试协议

### ISSUE THREAD

**Issue by artGlory** [jetlinks/jetlinks-community#94]
![C%EL7K){V(~4 A`JQPK~J62](https://user-images.githubusercontent.com/23271315/130162295-5b4c42f6-fd7e-4f0f-b5dc-27ff0d37f7bf.png)

**Comment by artGlory** [comment]
demo-protocl放入dev后，**需要做什么配置才能让程序使用到这个协议**，然后我接入设备进行debug

**Comment by likuoBlog** [comment]
方法1：通过web入口，上传、发布协议，然后idea断点就可以调试了。
方法2：直接把协议代码写在jetlinks工程里面，这样也可以调试，就不用上传、发布了。

**Comment by likuoBlog** [comment]
方法一：jetlinks平台在web有上传协议、发布协议，发布成功之后，在idea那边打断点就可以了。
方法二：直接把协议写到jetlinks工程里面，同一个工程，打断点肯定会吧。然后调试完之后，再把代码提取出来就好了。
方法三：目前还只是想法，未验证。协议在单独的maven工程里面，然后jetlinks引用这个maven包。这样在协议调试阶段就不用频繁的打包、上传、发布操作了。最后maven中配置打包的时候去除这个协议包即可。

**Comment by zhou-hao** [comment]
http://doc.jetlinks.cn/protocol/faq.html#%E6%9C%AC%E5%9C%B0%E5%BC%80%E5%8F%91%E6%97%B6%E5%A6%82%E4%BD%95%E8%B0%83%E8%AF%95%E5%8D%8F%E8%AE%AE%E5%8C%85
