### ISSUE TITLE
TCP粘包处理方式

### ISSUE THREAD

**Issue by Xuyilinya** [jetlinks/jetlinks-community#97]
文档对于这方面描述较少，能提供更详细的粘包处理方式么。

**Comment by zhou-hao** [comment]
看看单元测试： 

https://github.com/jetlinks/jetlinks-community/blob/master/jetlinks-components/network-component/tcp-component/src/test/java/org/jetlinks/community/network/tcp/parser/strateies/ScriptPayloadParserBuilderTest.java

https://github.com/jetlinks/jetlinks-community/blob/master/jetlinks-components/network-component/tcp-component/src/test/java/org/jetlinks/community/network/tcp/parser/strateies/PipePayloadParserTest.java
