### ISSUE TITLE
实体类创建表字段问题

### ISSUE THREAD

**Issue by qq517634644** [jetlinks/jetlinks-community#98]
```	
        @Column
	@Schema(description = "水质硬度")
	private Integer aData;
```
形如上述代码的变量命名方式“一个小写字母开头”的实体类无法通过ddl-auto自动创建表字段

**Comment by zhou-hao** [comment]
https://stackoverflow.com/questions/40822397/why-does-propertydescriptor-return-a-property-name-with-uppercase-as-first-chara .属性名最好不要一个首字母小写。
