### ISSUE TITLE
设备告警cron表达式无效

### ISSUE THREAD

**Issue by qq517634644** [jetlinks/jetlinks-community#99]
![image](https://user-images.githubusercontent.com/19528899/134038176-7e9ddbd3-1c45-486c-8882-c17e1b179b4a.png)
如图配置的设备告警，cron表达式不起作用，在时间之外依然会有告警产生
![image](https://user-images.githubusercontent.com/19528899/134038404-4401c2f0-5127-4919-b428-163ca10a95b5.png)

**Comment by zhou-hao** [comment]
更新最新代码试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tensai ***@***.***&gt;
发送时间: 2021年9月21日 00:25
收件人: jetlinks/jetlinks-community ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[jetlinks/jetlinks-community] 设备告警cron表达式无效 (#99)





 

 如图配置的设备告警，cron表达式不起作用，在时间之外依然会有告警产生

**Comment by qq517634644** [comment]
最新代码 也是一样的 cron没效果

**Comment by zhou-hao** [comment]
cron表达式的功能： 按cron定时发送读取属性指令，根据指令返回结果判断是否触发告警。
